package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

/**
 * Acoes generated by hbm2java
 */
public class Acoes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private AcoesId id;
	private Atividades atividades;

	public Acoes() {
	}

	public Acoes(AcoesId id, Atividades atividades) {
		this.id = id;
		this.atividades = atividades;
	}

	public AcoesId getId() {
		return this.id;
	}

	public void setId(AcoesId id) {
		this.id = id;
	}

	public Atividades getAtividades() {
		return this.atividades;
	}

	public void setAtividades(Atividades atividades) {
		this.atividades = atividades;
	}

}
