package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * AcoesId generated by hbm2java
 */
public class AcoesId implements java.io.Serializable {

	private long idAcao;
	private String nmPlanoAcao;
	private Date dtInicioAcao;
	private Date dtFimAcao;
	private Date dtPrevInicioAcao;
	private Date dtPrevFimAcao;
	private long atividadesIdAtividade;

	public AcoesId() {
	}

	public AcoesId(long idAcao, String nmPlanoAcao, Date dtInicioAcao, long atividadesIdAtividade) {
		this.idAcao = idAcao;
		this.nmPlanoAcao = nmPlanoAcao;
		this.dtInicioAcao = dtInicioAcao;
		this.atividadesIdAtividade = atividadesIdAtividade;
	}

	public AcoesId(long idAcao, String nmPlanoAcao, Date dtInicioAcao, Date dtFimAcao, Date dtPrevInicioAcao,
			Date dtPrevFimAcao, long atividadesIdAtividade) {
		this.idAcao = idAcao;
		this.nmPlanoAcao = nmPlanoAcao;
		this.dtInicioAcao = dtInicioAcao;
		this.dtFimAcao = dtFimAcao;
		this.dtPrevInicioAcao = dtPrevInicioAcao;
		this.dtPrevFimAcao = dtPrevFimAcao;
		this.atividadesIdAtividade = atividadesIdAtividade;
	}

	public long getIdAcao() {
		return this.idAcao;
	}

	public void setIdAcao(long idAcao) {
		this.idAcao = idAcao;
	}

	public String getNmPlanoAcao() {
		return this.nmPlanoAcao;
	}

	public void setNmPlanoAcao(String nmPlanoAcao) {
		this.nmPlanoAcao = nmPlanoAcao;
	}

	public Date getDtInicioAcao() {
		return this.dtInicioAcao;
	}

	public void setDtInicioAcao(Date dtInicioAcao) {
		this.dtInicioAcao = dtInicioAcao;
	}

	public Date getDtFimAcao() {
		return this.dtFimAcao;
	}

	public void setDtFimAcao(Date dtFimAcao) {
		this.dtFimAcao = dtFimAcao;
	}

	public Date getDtPrevInicioAcao() {
		return this.dtPrevInicioAcao;
	}

	public void setDtPrevInicioAcao(Date dtPrevInicioAcao) {
		this.dtPrevInicioAcao = dtPrevInicioAcao;
	}

	public Date getDtPrevFimAcao() {
		return this.dtPrevFimAcao;
	}

	public void setDtPrevFimAcao(Date dtPrevFimAcao) {
		this.dtPrevFimAcao = dtPrevFimAcao;
	}

	public long getAtividadesIdAtividade() {
		return this.atividadesIdAtividade;
	}

	public void setAtividadesIdAtividade(long atividadesIdAtividade) {
		this.atividadesIdAtividade = atividadesIdAtividade;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AcoesId))
			return false;
		AcoesId castOther = (AcoesId) other;

		return (this.getIdAcao() == castOther.getIdAcao())
				&& ((this.getNmPlanoAcao() == castOther.getNmPlanoAcao())
						|| (this.getNmPlanoAcao() != null && castOther.getNmPlanoAcao() != null
								&& this.getNmPlanoAcao().equals(castOther.getNmPlanoAcao())))
				&& ((this.getDtInicioAcao() == castOther.getDtInicioAcao())
						|| (this.getDtInicioAcao() != null && castOther.getDtInicioAcao() != null
								&& this.getDtInicioAcao().equals(castOther.getDtInicioAcao())))
				&& ((this.getDtFimAcao() == castOther.getDtFimAcao()) || (this.getDtFimAcao() != null
						&& castOther.getDtFimAcao() != null && this.getDtFimAcao().equals(castOther.getDtFimAcao())))
				&& ((this.getDtPrevInicioAcao() == castOther.getDtPrevInicioAcao())
						|| (this.getDtPrevInicioAcao() != null && castOther.getDtPrevInicioAcao() != null
								&& this.getDtPrevInicioAcao().equals(castOther.getDtPrevInicioAcao())))
				&& ((this.getDtPrevFimAcao() == castOther.getDtPrevFimAcao())
						|| (this.getDtPrevFimAcao() != null && castOther.getDtPrevFimAcao() != null
								&& this.getDtPrevFimAcao().equals(castOther.getDtPrevFimAcao())))
				&& (this.getAtividadesIdAtividade() == castOther.getAtividadesIdAtividade());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdAcao();
		result = 37 * result + (getNmPlanoAcao() == null ? 0 : this.getNmPlanoAcao().hashCode());
		result = 37 * result + (getDtInicioAcao() == null ? 0 : this.getDtInicioAcao().hashCode());
		result = 37 * result + (getDtFimAcao() == null ? 0 : this.getDtFimAcao().hashCode());
		result = 37 * result + (getDtPrevInicioAcao() == null ? 0 : this.getDtPrevInicioAcao().hashCode());
		result = 37 * result + (getDtPrevFimAcao() == null ? 0 : this.getDtPrevFimAcao().hashCode());
		result = 37 * result + (int) this.getAtividadesIdAtividade();
		return result;
	}

}
