package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alunos generated by hbm2java
 */
public class Alunos implements java.io.Serializable {

	private long idAluno;
	private PessoasFisicas pessoasFisicas;
	private Unidades unidades;
	private UsuariosSistema usuariosSistemaByIdUsuarioCadastro;
	private UsuariosSistema usuariosSistemaByIdUsuarioAlteracao;
	private String dsProblemaSaude;
	private String dsMedicamentosControlados;
	private String dsOutrasInformacoes;
	private String dsFormaIngressoEntidade;
	private String stAtendidoOrgaoRede;
	private Date dtEntrada;
	private String txObservacoes;
	private Date dtDesligamento;
	private String dsDesligamento;
	private Date dtCadastro;
	private Date dtAlteracaoCadastro;
	private String stMoraPais;
	private String stPaisCasados;
	private String stMatriculadoEscPub;
	private String dsBuscaEscola;
	private String stPublicoPrioritario;
	private Set responsaveisAlunoses = new HashSet(0);
	private Set encaminhaAlunoses = new HashSet(0);
	private Set vulnerabilidadesAlunos = new HashSet(0);
	private Set atividadesAlunos = new HashSet(0);
	private Set atendimentoses = new HashSet(0);
	private Set reprovacoesAlunos = new HashSet(0);

	public Alunos() {
	}

	public Alunos(long idAluno, PessoasFisicas pessoasFisicas, Unidades unidades,
			UsuariosSistema usuariosSistemaByIdUsuarioCadastro, UsuariosSistema usuariosSistemaByIdUsuarioAlteracao,
			Date dtCadastro) {
		this.idAluno = idAluno;
		this.pessoasFisicas = pessoasFisicas;
		this.unidades = unidades;
		this.usuariosSistemaByIdUsuarioCadastro = usuariosSistemaByIdUsuarioCadastro;
		this.usuariosSistemaByIdUsuarioAlteracao = usuariosSistemaByIdUsuarioAlteracao;
		this.dtCadastro = dtCadastro;
	}

	public Alunos(long idAluno, PessoasFisicas pessoasFisicas, Unidades unidades,
			UsuariosSistema usuariosSistemaByIdUsuarioCadastro, UsuariosSistema usuariosSistemaByIdUsuarioAlteracao,
			String dsProblemaSaude, String dsMedicamentosControlados, String dsOutrasInformacoes,
			String dsFormaIngressoEntidade, String stAtendidoOrgaoRede, Date dtEntrada, String txObservacoes,
			Date dtDesligamento, String dsDesligamento, Date dtCadastro, Date dtAlteracaoCadastro, String stMoraPais,
			String stPaisCasados, String stMatriculadoEscPub, String dsBuscaEscola, String stPublicoPrioritario,
			Set responsaveisAlunoses, Set encaminhaAlunoses, Set vulnerabilidadesAlunos, Set atividadesAlunos,
			Set atendimentoses, Set reprovacoesAlunos) {
		this.idAluno = idAluno;
		this.pessoasFisicas = pessoasFisicas;
		this.unidades = unidades;
		this.usuariosSistemaByIdUsuarioCadastro = usuariosSistemaByIdUsuarioCadastro;
		this.usuariosSistemaByIdUsuarioAlteracao = usuariosSistemaByIdUsuarioAlteracao;
		this.dsProblemaSaude = dsProblemaSaude;
		this.dsMedicamentosControlados = dsMedicamentosControlados;
		this.dsOutrasInformacoes = dsOutrasInformacoes;
		this.dsFormaIngressoEntidade = dsFormaIngressoEntidade;
		this.stAtendidoOrgaoRede = stAtendidoOrgaoRede;
		this.dtEntrada = dtEntrada;
		this.txObservacoes = txObservacoes;
		this.dtDesligamento = dtDesligamento;
		this.dsDesligamento = dsDesligamento;
		this.dtCadastro = dtCadastro;
		this.dtAlteracaoCadastro = dtAlteracaoCadastro;
		this.stMoraPais = stMoraPais;
		this.stPaisCasados = stPaisCasados;
		this.stMatriculadoEscPub = stMatriculadoEscPub;
		this.dsBuscaEscola = dsBuscaEscola;
		this.stPublicoPrioritario = stPublicoPrioritario;
		this.responsaveisAlunoses = responsaveisAlunoses;
		this.encaminhaAlunoses = encaminhaAlunoses;
		this.vulnerabilidadesAlunos = vulnerabilidadesAlunos;
		this.atividadesAlunos = atividadesAlunos;
		this.atendimentoses = atendimentoses;
		this.reprovacoesAlunos = reprovacoesAlunos;
	}

	public long getIdAluno() {
		return this.idAluno;
	}

	public void setIdAluno(long idAluno) {
		this.idAluno = idAluno;
	}

	public PessoasFisicas getPessoasFisicas() {
		return this.pessoasFisicas;
	}

	public void setPessoasFisicas(PessoasFisicas pessoasFisicas) {
		this.pessoasFisicas = pessoasFisicas;
	}

	public Unidades getUnidades() {
		return this.unidades;
	}

	public void setUnidades(Unidades unidades) {
		this.unidades = unidades;
	}

	public UsuariosSistema getUsuariosSistemaByIdUsuarioCadastro() {
		return this.usuariosSistemaByIdUsuarioCadastro;
	}

	public void setUsuariosSistemaByIdUsuarioCadastro(UsuariosSistema usuariosSistemaByIdUsuarioCadastro) {
		this.usuariosSistemaByIdUsuarioCadastro = usuariosSistemaByIdUsuarioCadastro;
	}

	public UsuariosSistema getUsuariosSistemaByIdUsuarioAlteracao() {
		return this.usuariosSistemaByIdUsuarioAlteracao;
	}

	public void setUsuariosSistemaByIdUsuarioAlteracao(UsuariosSistema usuariosSistemaByIdUsuarioAlteracao) {
		this.usuariosSistemaByIdUsuarioAlteracao = usuariosSistemaByIdUsuarioAlteracao;
	}

	public String getDsProblemaSaude() {
		return this.dsProblemaSaude;
	}

	public void setDsProblemaSaude(String dsProblemaSaude) {
		this.dsProblemaSaude = dsProblemaSaude;
	}

	public String getDsMedicamentosControlados() {
		return this.dsMedicamentosControlados;
	}

	public void setDsMedicamentosControlados(String dsMedicamentosControlados) {
		this.dsMedicamentosControlados = dsMedicamentosControlados;
	}

	public String getDsOutrasInformacoes() {
		return this.dsOutrasInformacoes;
	}

	public void setDsOutrasInformacoes(String dsOutrasInformacoes) {
		this.dsOutrasInformacoes = dsOutrasInformacoes;
	}

	public String getDsFormaIngressoEntidade() {
		return this.dsFormaIngressoEntidade;
	}

	public void setDsFormaIngressoEntidade(String dsFormaIngressoEntidade) {
		this.dsFormaIngressoEntidade = dsFormaIngressoEntidade;
	}

	public String getStAtendidoOrgaoRede() {
		return this.stAtendidoOrgaoRede;
	}

	public void setStAtendidoOrgaoRede(String stAtendidoOrgaoRede) {
		this.stAtendidoOrgaoRede = stAtendidoOrgaoRede;
	}

	public Date getDtEntrada() {
		return this.dtEntrada;
	}

	public void setDtEntrada(Date dtEntrada) {
		this.dtEntrada = dtEntrada;
	}

	public String getTxObservacoes() {
		return this.txObservacoes;
	}

	public void setTxObservacoes(String txObservacoes) {
		this.txObservacoes = txObservacoes;
	}

	public Date getDtDesligamento() {
		return this.dtDesligamento;
	}

	public void setDtDesligamento(Date dtDesligamento) {
		this.dtDesligamento = dtDesligamento;
	}

	public String getDsDesligamento() {
		return this.dsDesligamento;
	}

	public void setDsDesligamento(String dsDesligamento) {
		this.dsDesligamento = dsDesligamento;
	}

	public Date getDtCadastro() {
		return this.dtCadastro;
	}

	public void setDtCadastro(Date dtCadastro) {
		this.dtCadastro = dtCadastro;
	}

	public Date getDtAlteracaoCadastro() {
		return this.dtAlteracaoCadastro;
	}

	public void setDtAlteracaoCadastro(Date dtAlteracaoCadastro) {
		this.dtAlteracaoCadastro = dtAlteracaoCadastro;
	}

	public String getStMoraPais() {
		return this.stMoraPais;
	}

	public void setStMoraPais(String stMoraPais) {
		this.stMoraPais = stMoraPais;
	}

	public String getStPaisCasados() {
		return this.stPaisCasados;
	}

	public void setStPaisCasados(String stPaisCasados) {
		this.stPaisCasados = stPaisCasados;
	}

	public String getStMatriculadoEscPub() {
		return this.stMatriculadoEscPub;
	}

	public void setStMatriculadoEscPub(String stMatriculadoEscPub) {
		this.stMatriculadoEscPub = stMatriculadoEscPub;
	}

	public String getDsBuscaEscola() {
		return this.dsBuscaEscola;
	}

	public void setDsBuscaEscola(String dsBuscaEscola) {
		this.dsBuscaEscola = dsBuscaEscola;
	}

	public String getStPublicoPrioritario() {
		return this.stPublicoPrioritario;
	}

	public void setStPublicoPrioritario(String stPublicoPrioritario) {
		this.stPublicoPrioritario = stPublicoPrioritario;
	}

	public Set getResponsaveisAlunoses() {
		return this.responsaveisAlunoses;
	}

	public void setResponsaveisAlunoses(Set responsaveisAlunoses) {
		this.responsaveisAlunoses = responsaveisAlunoses;
	}

	public Set getEncaminhaAlunoses() {
		return this.encaminhaAlunoses;
	}

	public void setEncaminhaAlunoses(Set encaminhaAlunoses) {
		this.encaminhaAlunoses = encaminhaAlunoses;
	}

	public Set getVulnerabilidadesAlunos() {
		return this.vulnerabilidadesAlunos;
	}

	public void setVulnerabilidadesAlunos(Set vulnerabilidadesAlunos) {
		this.vulnerabilidadesAlunos = vulnerabilidadesAlunos;
	}

	public Set getAtividadesAlunos() {
		return this.atividadesAlunos;
	}

	public void setAtividadesAlunos(Set atividadesAlunos) {
		this.atividadesAlunos = atividadesAlunos;
	}

	public Set getAtendimentoses() {
		return this.atendimentoses;
	}

	public void setAtendimentoses(Set atendimentoses) {
		this.atendimentoses = atendimentoses;
	}

	public Set getReprovacoesAlunos() {
		return this.reprovacoesAlunos;
	}

	public void setReprovacoesAlunos(Set reprovacoesAlunos) {
		this.reprovacoesAlunos = reprovacoesAlunos;
	}

}
