package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * AlunosTrabalhando generated by hbm2java
 */
public class AlunosTrabalhando implements java.io.Serializable {

	private long idAlunoTrabalhando;
	private AtividadesAluno atividadesAluno;
	private String nmEmpreendimento;
	private String dsTipoEmpreendimento;
	private Date dtInicioAlunoTrabalhando;
	private Date dtFimAlunoTrabalhando;

	public AlunosTrabalhando() {
	}

	public AlunosTrabalhando(long idAlunoTrabalhando, AtividadesAluno atividadesAluno) {
		this.idAlunoTrabalhando = idAlunoTrabalhando;
		this.atividadesAluno = atividadesAluno;
	}

	public AlunosTrabalhando(long idAlunoTrabalhando, AtividadesAluno atividadesAluno, String nmEmpreendimento,
			String dsTipoEmpreendimento, Date dtInicioAlunoTrabalhando, Date dtFimAlunoTrabalhando) {
		this.idAlunoTrabalhando = idAlunoTrabalhando;
		this.atividadesAluno = atividadesAluno;
		this.nmEmpreendimento = nmEmpreendimento;
		this.dsTipoEmpreendimento = dsTipoEmpreendimento;
		this.dtInicioAlunoTrabalhando = dtInicioAlunoTrabalhando;
		this.dtFimAlunoTrabalhando = dtFimAlunoTrabalhando;
	}

	public long getIdAlunoTrabalhando() {
		return this.idAlunoTrabalhando;
	}

	public void setIdAlunoTrabalhando(long idAlunoTrabalhando) {
		this.idAlunoTrabalhando = idAlunoTrabalhando;
	}

	public AtividadesAluno getAtividadesAluno() {
		return this.atividadesAluno;
	}

	public void setAtividadesAluno(AtividadesAluno atividadesAluno) {
		this.atividadesAluno = atividadesAluno;
	}

	public String getNmEmpreendimento() {
		return this.nmEmpreendimento;
	}

	public void setNmEmpreendimento(String nmEmpreendimento) {
		this.nmEmpreendimento = nmEmpreendimento;
	}

	public String getDsTipoEmpreendimento() {
		return this.dsTipoEmpreendimento;
	}

	public void setDsTipoEmpreendimento(String dsTipoEmpreendimento) {
		this.dsTipoEmpreendimento = dsTipoEmpreendimento;
	}

	public Date getDtInicioAlunoTrabalhando() {
		return this.dtInicioAlunoTrabalhando;
	}

	public void setDtInicioAlunoTrabalhando(Date dtInicioAlunoTrabalhando) {
		this.dtInicioAlunoTrabalhando = dtInicioAlunoTrabalhando;
	}

	public Date getDtFimAlunoTrabalhando() {
		return this.dtFimAlunoTrabalhando;
	}

	public void setDtFimAlunoTrabalhando(Date dtFimAlunoTrabalhando) {
		this.dtFimAlunoTrabalhando = dtFimAlunoTrabalhando;
	}

}
