package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Arquivos generated by hbm2java
 */
public class Arquivos implements java.io.Serializable {

	private long idArquivo;
	private String nmArquivo;
	private String dsTipoArquivo;
	private BigDecimal nrTamanhoArquivo;
	private String hash;
	private Date dtCriacao;
	private byte[] blob;
	private Set unidadeses = new HashSet(0);
	private Set entidadeses = new HashSet(0);
	private Set pessoasFisicases = new HashSet(0);

	public Arquivos() {
	}

	public Arquivos(long idArquivo, String nmArquivo) {
		this.idArquivo = idArquivo;
		this.nmArquivo = nmArquivo;
	}

	public Arquivos(long idArquivo, String nmArquivo, String dsTipoArquivo, BigDecimal nrTamanhoArquivo, String hash,
			Date dtCriacao, byte[] blob, Set unidadeses, Set entidadeses, Set pessoasFisicases) {
		this.idArquivo = idArquivo;
		this.nmArquivo = nmArquivo;
		this.dsTipoArquivo = dsTipoArquivo;
		this.nrTamanhoArquivo = nrTamanhoArquivo;
		this.hash = hash;
		this.dtCriacao = dtCriacao;
		this.blob = blob;
		this.unidadeses = unidadeses;
		this.entidadeses = entidadeses;
		this.pessoasFisicases = pessoasFisicases;
	}

	public long getIdArquivo() {
		return this.idArquivo;
	}

	public void setIdArquivo(long idArquivo) {
		this.idArquivo = idArquivo;
	}

	public String getNmArquivo() {
		return this.nmArquivo;
	}

	public void setNmArquivo(String nmArquivo) {
		this.nmArquivo = nmArquivo;
	}

	public String getDsTipoArquivo() {
		return this.dsTipoArquivo;
	}

	public void setDsTipoArquivo(String dsTipoArquivo) {
		this.dsTipoArquivo = dsTipoArquivo;
	}

	public BigDecimal getNrTamanhoArquivo() {
		return this.nrTamanhoArquivo;
	}

	public void setNrTamanhoArquivo(BigDecimal nrTamanhoArquivo) {
		this.nrTamanhoArquivo = nrTamanhoArquivo;
	}

	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

	public Date getDtCriacao() {
		return this.dtCriacao;
	}

	public void setDtCriacao(Date dtCriacao) {
		this.dtCriacao = dtCriacao;
	}

	public byte[] getBlob() {
		return this.blob;
	}

	public void setBlob(byte[] blob) {
		this.blob = blob;
	}

	public Set getUnidadeses() {
		return this.unidadeses;
	}

	public void setUnidadeses(Set unidadeses) {
		this.unidadeses = unidadeses;
	}

	public Set getEntidadeses() {
		return this.entidadeses;
	}

	public void setEntidadeses(Set entidadeses) {
		this.entidadeses = entidadeses;
	}

	public Set getPessoasFisicases() {
		return this.pessoasFisicases;
	}

	public void setPessoasFisicases(Set pessoasFisicases) {
		this.pessoasFisicases = pessoasFisicases;
	}

}
