package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * Atendimentos generated by hbm2java
 */
public class Atendimentos implements java.io.Serializable {

	private long idAtendimento;
	private Alunos alunos;
	private Diagnosticos diagnosticos;
	private Familiares familiares;
	private Funcionarios funcionarios;
	private Responsaveis responsaveis;
	private Solucoes solucoes;
	private Date dtAtendimento;
	private String dsDiagnostico;
	private String dsSolucao;

	public Atendimentos() {
	}

	public Atendimentos(long idAtendimento, Alunos alunos, Diagnosticos diagnosticos, Funcionarios funcionarios,
			Solucoes solucoes, Date dtAtendimento) {
		this.idAtendimento = idAtendimento;
		this.alunos = alunos;
		this.diagnosticos = diagnosticos;
		this.funcionarios = funcionarios;
		this.solucoes = solucoes;
		this.dtAtendimento = dtAtendimento;
	}

	public Atendimentos(long idAtendimento, Alunos alunos, Diagnosticos diagnosticos, Familiares familiares,
			Funcionarios funcionarios, Responsaveis responsaveis, Solucoes solucoes, Date dtAtendimento,
			String dsDiagnostico, String dsSolucao) {
		this.idAtendimento = idAtendimento;
		this.alunos = alunos;
		this.diagnosticos = diagnosticos;
		this.familiares = familiares;
		this.funcionarios = funcionarios;
		this.responsaveis = responsaveis;
		this.solucoes = solucoes;
		this.dtAtendimento = dtAtendimento;
		this.dsDiagnostico = dsDiagnostico;
		this.dsSolucao = dsSolucao;
	}

	public long getIdAtendimento() {
		return this.idAtendimento;
	}

	public void setIdAtendimento(long idAtendimento) {
		this.idAtendimento = idAtendimento;
	}

	public Alunos getAlunos() {
		return this.alunos;
	}

	public void setAlunos(Alunos alunos) {
		this.alunos = alunos;
	}

	public Diagnosticos getDiagnosticos() {
		return this.diagnosticos;
	}

	public void setDiagnosticos(Diagnosticos diagnosticos) {
		this.diagnosticos = diagnosticos;
	}

	public Familiares getFamiliares() {
		return this.familiares;
	}

	public void setFamiliares(Familiares familiares) {
		this.familiares = familiares;
	}

	public Funcionarios getFuncionarios() {
		return this.funcionarios;
	}

	public void setFuncionarios(Funcionarios funcionarios) {
		this.funcionarios = funcionarios;
	}

	public Responsaveis getResponsaveis() {
		return this.responsaveis;
	}

	public void setResponsaveis(Responsaveis responsaveis) {
		this.responsaveis = responsaveis;
	}

	public Solucoes getSolucoes() {
		return this.solucoes;
	}

	public void setSolucoes(Solucoes solucoes) {
		this.solucoes = solucoes;
	}

	public Date getDtAtendimento() {
		return this.dtAtendimento;
	}

	public void setDtAtendimento(Date dtAtendimento) {
		this.dtAtendimento = dtAtendimento;
	}

	public String getDsDiagnostico() {
		return this.dsDiagnostico;
	}

	public void setDsDiagnostico(String dsDiagnostico) {
		this.dsDiagnostico = dsDiagnostico;
	}

	public String getDsSolucao() {
		return this.dsSolucao;
	}

	public void setDsSolucao(String dsSolucao) {
		this.dsSolucao = dsSolucao;
	}

}
