package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Atividades generated by hbm2java
 */
public class Atividades implements java.io.Serializable {

	private long idAtividade;
	private PlanosAcao planosAcao;
	private Projetos projetos;
	private Unidades unidades;
	private String dsAtividade;
	private Date dtPrevInicio;
	private Date dtPrevTermino;
	private Date dtInicioAtividade;
	private Date dtFimAtividade;
	private BigDecimal periodoAtividade;
	private String stSegunda;
	private String stTerca;
	private String stQuarta;
	private String stQuinta;
	private String stSexta;
	private String stSabado;
	private String stDomingo;
	private Short hrInicio;
	private Short hrFim;
	private BigDecimal nrMaximoParticipantes;
	private Long nrAulas;
	private BigDecimal nrCargaHoraria;
	private String stLocalExecucao;
	private String dsLocalExecucao;
	private String stHorarioFixo;
	private BigDecimal vlCustoAtividade;
	private String txObservacoes;
	private Set documentosAtividadeses = new HashSet(0);
	private Set acoeses = new HashSet(0);
	private Set cadastroReservaAtividadeses = new HashSet(0);
	private Set atividadesAlunos = new HashSet(0);
	private Set colaboradoresAtividadeses = new HashSet(0);
	private Set produtosAtividadeses = new HashSet(0);

	public Atividades() {
	}

	public Atividades(long idAtividade, Unidades unidades, String dsAtividade, Date dtPrevInicio) {
		this.idAtividade = idAtividade;
		this.unidades = unidades;
		this.dsAtividade = dsAtividade;
		this.dtPrevInicio = dtPrevInicio;
	}

	public Atividades(long idAtividade, PlanosAcao planosAcao, Projetos projetos, Unidades unidades, String dsAtividade,
			Date dtPrevInicio, Date dtPrevTermino, Date dtInicioAtividade, Date dtFimAtividade,
			BigDecimal periodoAtividade, String stSegunda, String stTerca, String stQuarta, String stQuinta,
			String stSexta, String stSabado, String stDomingo, Short hrInicio, Short hrFim,
			BigDecimal nrMaximoParticipantes, Long nrAulas, BigDecimal nrCargaHoraria, String stLocalExecucao,
			String dsLocalExecucao, String stHorarioFixo, BigDecimal vlCustoAtividade, String txObservacoes,
			Set documentosAtividadeses, Set acoeses, Set cadastroReservaAtividadeses, Set atividadesAlunos,
			Set colaboradoresAtividadeses, Set produtosAtividadeses) {
		this.idAtividade = idAtividade;
		this.planosAcao = planosAcao;
		this.projetos = projetos;
		this.unidades = unidades;
		this.dsAtividade = dsAtividade;
		this.dtPrevInicio = dtPrevInicio;
		this.dtPrevTermino = dtPrevTermino;
		this.dtInicioAtividade = dtInicioAtividade;
		this.dtFimAtividade = dtFimAtividade;
		this.periodoAtividade = periodoAtividade;
		this.stSegunda = stSegunda;
		this.stTerca = stTerca;
		this.stQuarta = stQuarta;
		this.stQuinta = stQuinta;
		this.stSexta = stSexta;
		this.stSabado = stSabado;
		this.stDomingo = stDomingo;
		this.hrInicio = hrInicio;
		this.hrFim = hrFim;
		this.nrMaximoParticipantes = nrMaximoParticipantes;
		this.nrAulas = nrAulas;
		this.nrCargaHoraria = nrCargaHoraria;
		this.stLocalExecucao = stLocalExecucao;
		this.dsLocalExecucao = dsLocalExecucao;
		this.stHorarioFixo = stHorarioFixo;
		this.vlCustoAtividade = vlCustoAtividade;
		this.txObservacoes = txObservacoes;
		this.documentosAtividadeses = documentosAtividadeses;
		this.acoeses = acoeses;
		this.cadastroReservaAtividadeses = cadastroReservaAtividadeses;
		this.atividadesAlunos = atividadesAlunos;
		this.colaboradoresAtividadeses = colaboradoresAtividadeses;
		this.produtosAtividadeses = produtosAtividadeses;
	}

	public long getIdAtividade() {
		return this.idAtividade;
	}

	public void setIdAtividade(long idAtividade) {
		this.idAtividade = idAtividade;
	}

	public PlanosAcao getPlanosAcao() {
		return this.planosAcao;
	}

	public void setPlanosAcao(PlanosAcao planosAcao) {
		this.planosAcao = planosAcao;
	}

	public Projetos getProjetos() {
		return this.projetos;
	}

	public void setProjetos(Projetos projetos) {
		this.projetos = projetos;
	}

	public Unidades getUnidades() {
		return this.unidades;
	}

	public void setUnidades(Unidades unidades) {
		this.unidades = unidades;
	}

	public String getDsAtividade() {
		return this.dsAtividade;
	}

	public void setDsAtividade(String dsAtividade) {
		this.dsAtividade = dsAtividade;
	}

	public Date getDtPrevInicio() {
		return this.dtPrevInicio;
	}

	public void setDtPrevInicio(Date dtPrevInicio) {
		this.dtPrevInicio = dtPrevInicio;
	}

	public Date getDtPrevTermino() {
		return this.dtPrevTermino;
	}

	public void setDtPrevTermino(Date dtPrevTermino) {
		this.dtPrevTermino = dtPrevTermino;
	}

	public Date getDtInicioAtividade() {
		return this.dtInicioAtividade;
	}

	public void setDtInicioAtividade(Date dtInicioAtividade) {
		this.dtInicioAtividade = dtInicioAtividade;
	}

	public Date getDtFimAtividade() {
		return this.dtFimAtividade;
	}

	public void setDtFimAtividade(Date dtFimAtividade) {
		this.dtFimAtividade = dtFimAtividade;
	}

	public BigDecimal getPeriodoAtividade() {
		return this.periodoAtividade;
	}

	public void setPeriodoAtividade(BigDecimal periodoAtividade) {
		this.periodoAtividade = periodoAtividade;
	}

	public String getStSegunda() {
		return this.stSegunda;
	}

	public void setStSegunda(String stSegunda) {
		this.stSegunda = stSegunda;
	}

	public String getStTerca() {
		return this.stTerca;
	}

	public void setStTerca(String stTerca) {
		this.stTerca = stTerca;
	}

	public String getStQuarta() {
		return this.stQuarta;
	}

	public void setStQuarta(String stQuarta) {
		this.stQuarta = stQuarta;
	}

	public String getStQuinta() {
		return this.stQuinta;
	}

	public void setStQuinta(String stQuinta) {
		this.stQuinta = stQuinta;
	}

	public String getStSexta() {
		return this.stSexta;
	}

	public void setStSexta(String stSexta) {
		this.stSexta = stSexta;
	}

	public String getStSabado() {
		return this.stSabado;
	}

	public void setStSabado(String stSabado) {
		this.stSabado = stSabado;
	}

	public String getStDomingo() {
		return this.stDomingo;
	}

	public void setStDomingo(String stDomingo) {
		this.stDomingo = stDomingo;
	}

	public Short getHrInicio() {
		return this.hrInicio;
	}

	public void setHrInicio(Short hrInicio) {
		this.hrInicio = hrInicio;
	}

	public Short getHrFim() {
		return this.hrFim;
	}

	public void setHrFim(Short hrFim) {
		this.hrFim = hrFim;
	}

	public BigDecimal getNrMaximoParticipantes() {
		return this.nrMaximoParticipantes;
	}

	public void setNrMaximoParticipantes(BigDecimal nrMaximoParticipantes) {
		this.nrMaximoParticipantes = nrMaximoParticipantes;
	}

	public Long getNrAulas() {
		return this.nrAulas;
	}

	public void setNrAulas(Long nrAulas) {
		this.nrAulas = nrAulas;
	}

	public BigDecimal getNrCargaHoraria() {
		return this.nrCargaHoraria;
	}

	public void setNrCargaHoraria(BigDecimal nrCargaHoraria) {
		this.nrCargaHoraria = nrCargaHoraria;
	}

	public String getStLocalExecucao() {
		return this.stLocalExecucao;
	}

	public void setStLocalExecucao(String stLocalExecucao) {
		this.stLocalExecucao = stLocalExecucao;
	}

	public String getDsLocalExecucao() {
		return this.dsLocalExecucao;
	}

	public void setDsLocalExecucao(String dsLocalExecucao) {
		this.dsLocalExecucao = dsLocalExecucao;
	}

	public String getStHorarioFixo() {
		return this.stHorarioFixo;
	}

	public void setStHorarioFixo(String stHorarioFixo) {
		this.stHorarioFixo = stHorarioFixo;
	}

	public BigDecimal getVlCustoAtividade() {
		return this.vlCustoAtividade;
	}

	public void setVlCustoAtividade(BigDecimal vlCustoAtividade) {
		this.vlCustoAtividade = vlCustoAtividade;
	}

	public String getTxObservacoes() {
		return this.txObservacoes;
	}

	public void setTxObservacoes(String txObservacoes) {
		this.txObservacoes = txObservacoes;
	}

	public Set getDocumentosAtividadeses() {
		return this.documentosAtividadeses;
	}

	public void setDocumentosAtividadeses(Set documentosAtividadeses) {
		this.documentosAtividadeses = documentosAtividadeses;
	}

	public Set getAcoeses() {
		return this.acoeses;
	}

	public void setAcoeses(Set acoeses) {
		this.acoeses = acoeses;
	}

	public Set getCadastroReservaAtividadeses() {
		return this.cadastroReservaAtividadeses;
	}

	public void setCadastroReservaAtividadeses(Set cadastroReservaAtividadeses) {
		this.cadastroReservaAtividadeses = cadastroReservaAtividadeses;
	}

	public Set getAtividadesAlunos() {
		return this.atividadesAlunos;
	}

	public void setAtividadesAlunos(Set atividadesAlunos) {
		this.atividadesAlunos = atividadesAlunos;
	}

	public Set getColaboradoresAtividadeses() {
		return this.colaboradoresAtividadeses;
	}

	public void setColaboradoresAtividadeses(Set colaboradoresAtividadeses) {
		this.colaboradoresAtividadeses = colaboradoresAtividadeses;
	}

	public Set getProdutosAtividadeses() {
		return this.produtosAtividadeses;
	}

	public void setProdutosAtividadeses(Set produtosAtividadeses) {
		this.produtosAtividadeses = produtosAtividadeses;
	}

}
