package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AtividadesAluno generated by hbm2java
 */
public class AtividadesAluno implements java.io.Serializable {

	private long idAtividadeAluno;
	private Alunos alunos;
	private Atividades atividades;
	private UsuariosSistema usuariosSistemaByUsAlteracaIdUsuario;
	private UsuariosSistema usuariosSistemaByUsCadastroIdUsuario;
	private Date dtInicioAtividade;
	private Date dsDesligamento;
	private Date dtDesvinculacao;
	private Date dtCadastroAtividade;
	private Date dtAlteracaoAtividade;
	private Set avaliacoesAlunoses = new HashSet(0);
	private Set uniformesAlunos = new HashSet(0);
	private Set frequenciasAlunoses = new HashSet(0);
	private Set alunosTrabalhandos = new HashSet(0);

	public AtividadesAluno() {
	}

	public AtividadesAluno(long idAtividadeAluno, Alunos alunos, Atividades atividades,
			UsuariosSistema usuariosSistemaByUsAlteracaIdUsuario,
			UsuariosSistema usuariosSistemaByUsCadastroIdUsuario) {
		this.idAtividadeAluno = idAtividadeAluno;
		this.alunos = alunos;
		this.atividades = atividades;
		this.usuariosSistemaByUsAlteracaIdUsuario = usuariosSistemaByUsAlteracaIdUsuario;
		this.usuariosSistemaByUsCadastroIdUsuario = usuariosSistemaByUsCadastroIdUsuario;
	}

	public AtividadesAluno(long idAtividadeAluno, Alunos alunos, Atividades atividades,
			UsuariosSistema usuariosSistemaByUsAlteracaIdUsuario, UsuariosSistema usuariosSistemaByUsCadastroIdUsuario,
			Date dtInicioAtividade, Date dsDesligamento, Date dtDesvinculacao, Date dtCadastroAtividade,
			Date dtAlteracaoAtividade, Set avaliacoesAlunoses, Set uniformesAlunos, Set frequenciasAlunoses,
			Set alunosTrabalhandos) {
		this.idAtividadeAluno = idAtividadeAluno;
		this.alunos = alunos;
		this.atividades = atividades;
		this.usuariosSistemaByUsAlteracaIdUsuario = usuariosSistemaByUsAlteracaIdUsuario;
		this.usuariosSistemaByUsCadastroIdUsuario = usuariosSistemaByUsCadastroIdUsuario;
		this.dtInicioAtividade = dtInicioAtividade;
		this.dsDesligamento = dsDesligamento;
		this.dtDesvinculacao = dtDesvinculacao;
		this.dtCadastroAtividade = dtCadastroAtividade;
		this.dtAlteracaoAtividade = dtAlteracaoAtividade;
		this.avaliacoesAlunoses = avaliacoesAlunoses;
		this.uniformesAlunos = uniformesAlunos;
		this.frequenciasAlunoses = frequenciasAlunoses;
		this.alunosTrabalhandos = alunosTrabalhandos;
	}

	public long getIdAtividadeAluno() {
		return this.idAtividadeAluno;
	}

	public void setIdAtividadeAluno(long idAtividadeAluno) {
		this.idAtividadeAluno = idAtividadeAluno;
	}

	public Alunos getAlunos() {
		return this.alunos;
	}

	public void setAlunos(Alunos alunos) {
		this.alunos = alunos;
	}

	public Atividades getAtividades() {
		return this.atividades;
	}

	public void setAtividades(Atividades atividades) {
		this.atividades = atividades;
	}

	public UsuariosSistema getUsuariosSistemaByUsAlteracaIdUsuario() {
		return this.usuariosSistemaByUsAlteracaIdUsuario;
	}

	public void setUsuariosSistemaByUsAlteracaIdUsuario(UsuariosSistema usuariosSistemaByUsAlteracaIdUsuario) {
		this.usuariosSistemaByUsAlteracaIdUsuario = usuariosSistemaByUsAlteracaIdUsuario;
	}

	public UsuariosSistema getUsuariosSistemaByUsCadastroIdUsuario() {
		return this.usuariosSistemaByUsCadastroIdUsuario;
	}

	public void setUsuariosSistemaByUsCadastroIdUsuario(UsuariosSistema usuariosSistemaByUsCadastroIdUsuario) {
		this.usuariosSistemaByUsCadastroIdUsuario = usuariosSistemaByUsCadastroIdUsuario;
	}

	public Date getDtInicioAtividade() {
		return this.dtInicioAtividade;
	}

	public void setDtInicioAtividade(Date dtInicioAtividade) {
		this.dtInicioAtividade = dtInicioAtividade;
	}

	public Date getDsDesligamento() {
		return this.dsDesligamento;
	}

	public void setDsDesligamento(Date dsDesligamento) {
		this.dsDesligamento = dsDesligamento;
	}

	public Date getDtDesvinculacao() {
		return this.dtDesvinculacao;
	}

	public void setDtDesvinculacao(Date dtDesvinculacao) {
		this.dtDesvinculacao = dtDesvinculacao;
	}

	public Date getDtCadastroAtividade() {
		return this.dtCadastroAtividade;
	}

	public void setDtCadastroAtividade(Date dtCadastroAtividade) {
		this.dtCadastroAtividade = dtCadastroAtividade;
	}

	public Date getDtAlteracaoAtividade() {
		return this.dtAlteracaoAtividade;
	}

	public void setDtAlteracaoAtividade(Date dtAlteracaoAtividade) {
		this.dtAlteracaoAtividade = dtAlteracaoAtividade;
	}

	public Set getAvaliacoesAlunoses() {
		return this.avaliacoesAlunoses;
	}

	public void setAvaliacoesAlunoses(Set avaliacoesAlunoses) {
		this.avaliacoesAlunoses = avaliacoesAlunoses;
	}

	public Set getUniformesAlunos() {
		return this.uniformesAlunos;
	}

	public void setUniformesAlunos(Set uniformesAlunos) {
		this.uniformesAlunos = uniformesAlunos;
	}

	public Set getFrequenciasAlunoses() {
		return this.frequenciasAlunoses;
	}

	public void setFrequenciasAlunoses(Set frequenciasAlunoses) {
		this.frequenciasAlunoses = frequenciasAlunoses;
	}

	public Set getAlunosTrabalhandos() {
		return this.alunosTrabalhandos;
	}

	public void setAlunosTrabalhandos(Set alunosTrabalhandos) {
		this.alunosTrabalhandos = alunosTrabalhandos;
	}

}
