package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Avaliacoes generated by hbm2java
 */
public class Avaliacoes implements java.io.Serializable {

	private long idAvaliacao;
	private String dsAvaliacao;
	private Date dtInicioAvaliacao;
	private Date dtFimAvaliacao;
	private String nmAvaliacao;
	private Set avaliacoesAlunoses = new HashSet(0);

	public Avaliacoes() {
	}

	public Avaliacoes(long idAvaliacao) {
		this.idAvaliacao = idAvaliacao;
	}

	public Avaliacoes(long idAvaliacao, String dsAvaliacao, Date dtInicioAvaliacao, Date dtFimAvaliacao,
			String nmAvaliacao, Set avaliacoesAlunoses) {
		this.idAvaliacao = idAvaliacao;
		this.dsAvaliacao = dsAvaliacao;
		this.dtInicioAvaliacao = dtInicioAvaliacao;
		this.dtFimAvaliacao = dtFimAvaliacao;
		this.nmAvaliacao = nmAvaliacao;
		this.avaliacoesAlunoses = avaliacoesAlunoses;
	}

	public long getIdAvaliacao() {
		return this.idAvaliacao;
	}

	public void setIdAvaliacao(long idAvaliacao) {
		this.idAvaliacao = idAvaliacao;
	}

	public String getDsAvaliacao() {
		return this.dsAvaliacao;
	}

	public void setDsAvaliacao(String dsAvaliacao) {
		this.dsAvaliacao = dsAvaliacao;
	}

	public Date getDtInicioAvaliacao() {
		return this.dtInicioAvaliacao;
	}

	public void setDtInicioAvaliacao(Date dtInicioAvaliacao) {
		this.dtInicioAvaliacao = dtInicioAvaliacao;
	}

	public Date getDtFimAvaliacao() {
		return this.dtFimAvaliacao;
	}

	public void setDtFimAvaliacao(Date dtFimAvaliacao) {
		this.dtFimAvaliacao = dtFimAvaliacao;
	}

	public String getNmAvaliacao() {
		return this.nmAvaliacao;
	}

	public void setNmAvaliacao(String nmAvaliacao) {
		this.nmAvaliacao = nmAvaliacao;
	}

	public Set getAvaliacoesAlunoses() {
		return this.avaliacoesAlunoses;
	}

	public void setAvaliacoesAlunoses(Set avaliacoesAlunoses) {
		this.avaliacoesAlunoses = avaliacoesAlunoses;
	}

}
