package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * AvaliacoesAlunos generated by hbm2java
 */
public class AvaliacoesAlunos implements java.io.Serializable {

	private long idAvaliacaoAluno;
	private AtividadesAluno atividadesAluno;
	private Avaliacoes avaliacoes;
	private String dsAvaliacaoAluno;
	private Date dtAvaliacaoAluno;
	private String nrAvaliacao;

	public AvaliacoesAlunos() {
	}

	public AvaliacoesAlunos(long idAvaliacaoAluno, AtividadesAluno atividadesAluno, Avaliacoes avaliacoes) {
		this.idAvaliacaoAluno = idAvaliacaoAluno;
		this.atividadesAluno = atividadesAluno;
		this.avaliacoes = avaliacoes;
	}

	public AvaliacoesAlunos(long idAvaliacaoAluno, AtividadesAluno atividadesAluno, Avaliacoes avaliacoes,
			String dsAvaliacaoAluno, Date dtAvaliacaoAluno, String nrAvaliacao) {
		this.idAvaliacaoAluno = idAvaliacaoAluno;
		this.atividadesAluno = atividadesAluno;
		this.avaliacoes = avaliacoes;
		this.dsAvaliacaoAluno = dsAvaliacaoAluno;
		this.dtAvaliacaoAluno = dtAvaliacaoAluno;
		this.nrAvaliacao = nrAvaliacao;
	}

	public long getIdAvaliacaoAluno() {
		return this.idAvaliacaoAluno;
	}

	public void setIdAvaliacaoAluno(long idAvaliacaoAluno) {
		this.idAvaliacaoAluno = idAvaliacaoAluno;
	}

	public AtividadesAluno getAtividadesAluno() {
		return this.atividadesAluno;
	}

	public void setAtividadesAluno(AtividadesAluno atividadesAluno) {
		this.atividadesAluno = atividadesAluno;
	}

	public Avaliacoes getAvaliacoes() {
		return this.avaliacoes;
	}

	public void setAvaliacoes(Avaliacoes avaliacoes) {
		this.avaliacoes = avaliacoes;
	}

	public String getDsAvaliacaoAluno() {
		return this.dsAvaliacaoAluno;
	}

	public void setDsAvaliacaoAluno(String dsAvaliacaoAluno) {
		this.dsAvaliacaoAluno = dsAvaliacaoAluno;
	}

	public Date getDtAvaliacaoAluno() {
		return this.dtAvaliacaoAluno;
	}

	public void setDtAvaliacaoAluno(Date dtAvaliacaoAluno) {
		this.dtAvaliacaoAluno = dtAvaliacaoAluno;
	}

	public String getNrAvaliacao() {
		return this.nrAvaliacao;
	}

	public void setNrAvaliacao(String nrAvaliacao) {
		this.nrAvaliacao = nrAvaliacao;
	}

}
