package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * CadastroReservaAtividades generated by hbm2java
 */
public class CadastroReservaAtividades implements java.io.Serializable {

	private long idCadastroReserva;
	private Atividades atividades;
	private PessoasFisicas pessoasFisicas;
	private UsuariosSistema usuariosSistemaByUsAlteracaIdUsuario;
	private UsuariosSistema usuariosSistemaByUsCadastroIdUsuario;
	private Date dtCadastroReserva;
	private Date dsCadastroReserva;
	private Date dtCancelamentoCadastro;
	private Date dtCadastroAtividade;
	private String dsCancelamentoCadastro;
	private Date dtAlteracaoAtividade;

	public CadastroReservaAtividades() {
	}

	public CadastroReservaAtividades(long idCadastroReserva, Atividades atividades, PessoasFisicas pessoasFisicas,
			UsuariosSistema usuariosSistemaByUsAlteracaIdUsuario,
			UsuariosSistema usuariosSistemaByUsCadastroIdUsuario) {
		this.idCadastroReserva = idCadastroReserva;
		this.atividades = atividades;
		this.pessoasFisicas = pessoasFisicas;
		this.usuariosSistemaByUsAlteracaIdUsuario = usuariosSistemaByUsAlteracaIdUsuario;
		this.usuariosSistemaByUsCadastroIdUsuario = usuariosSistemaByUsCadastroIdUsuario;
	}

	public CadastroReservaAtividades(long idCadastroReserva, Atividades atividades, PessoasFisicas pessoasFisicas,
			UsuariosSistema usuariosSistemaByUsAlteracaIdUsuario, UsuariosSistema usuariosSistemaByUsCadastroIdUsuario,
			Date dtCadastroReserva, Date dsCadastroReserva, Date dtCancelamentoCadastro, Date dtCadastroAtividade,
			String dsCancelamentoCadastro, Date dtAlteracaoAtividade) {
		this.idCadastroReserva = idCadastroReserva;
		this.atividades = atividades;
		this.pessoasFisicas = pessoasFisicas;
		this.usuariosSistemaByUsAlteracaIdUsuario = usuariosSistemaByUsAlteracaIdUsuario;
		this.usuariosSistemaByUsCadastroIdUsuario = usuariosSistemaByUsCadastroIdUsuario;
		this.dtCadastroReserva = dtCadastroReserva;
		this.dsCadastroReserva = dsCadastroReserva;
		this.dtCancelamentoCadastro = dtCancelamentoCadastro;
		this.dtCadastroAtividade = dtCadastroAtividade;
		this.dsCancelamentoCadastro = dsCancelamentoCadastro;
		this.dtAlteracaoAtividade = dtAlteracaoAtividade;
	}

	public long getIdCadastroReserva() {
		return this.idCadastroReserva;
	}

	public void setIdCadastroReserva(long idCadastroReserva) {
		this.idCadastroReserva = idCadastroReserva;
	}

	public Atividades getAtividades() {
		return this.atividades;
	}

	public void setAtividades(Atividades atividades) {
		this.atividades = atividades;
	}

	public PessoasFisicas getPessoasFisicas() {
		return this.pessoasFisicas;
	}

	public void setPessoasFisicas(PessoasFisicas pessoasFisicas) {
		this.pessoasFisicas = pessoasFisicas;
	}

	public UsuariosSistema getUsuariosSistemaByUsAlteracaIdUsuario() {
		return this.usuariosSistemaByUsAlteracaIdUsuario;
	}

	public void setUsuariosSistemaByUsAlteracaIdUsuario(UsuariosSistema usuariosSistemaByUsAlteracaIdUsuario) {
		this.usuariosSistemaByUsAlteracaIdUsuario = usuariosSistemaByUsAlteracaIdUsuario;
	}

	public UsuariosSistema getUsuariosSistemaByUsCadastroIdUsuario() {
		return this.usuariosSistemaByUsCadastroIdUsuario;
	}

	public void setUsuariosSistemaByUsCadastroIdUsuario(UsuariosSistema usuariosSistemaByUsCadastroIdUsuario) {
		this.usuariosSistemaByUsCadastroIdUsuario = usuariosSistemaByUsCadastroIdUsuario;
	}

	public Date getDtCadastroReserva() {
		return this.dtCadastroReserva;
	}

	public void setDtCadastroReserva(Date dtCadastroReserva) {
		this.dtCadastroReserva = dtCadastroReserva;
	}

	public Date getDsCadastroReserva() {
		return this.dsCadastroReserva;
	}

	public void setDsCadastroReserva(Date dsCadastroReserva) {
		this.dsCadastroReserva = dsCadastroReserva;
	}

	public Date getDtCancelamentoCadastro() {
		return this.dtCancelamentoCadastro;
	}

	public void setDtCancelamentoCadastro(Date dtCancelamentoCadastro) {
		this.dtCancelamentoCadastro = dtCancelamentoCadastro;
	}

	public Date getDtCadastroAtividade() {
		return this.dtCadastroAtividade;
	}

	public void setDtCadastroAtividade(Date dtCadastroAtividade) {
		this.dtCadastroAtividade = dtCadastroAtividade;
	}

	public String getDsCancelamentoCadastro() {
		return this.dsCancelamentoCadastro;
	}

	public void setDsCancelamentoCadastro(String dsCancelamentoCadastro) {
		this.dsCancelamentoCadastro = dsCancelamentoCadastro;
	}

	public Date getDtAlteracaoAtividade() {
		return this.dtAlteracaoAtividade;
	}

	public void setDtAlteracaoAtividade(Date dtAlteracaoAtividade) {
		this.dtAlteracaoAtividade = dtAlteracaoAtividade;
	}

}
