package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Cargos generated by hbm2java
 */
public class Cargos implements java.io.Serializable {

	private long idCargo;
	private String cdCargo;
	private String nmCargo;
	private String stTipoCargo;
	private Set contatosEmpresas = new HashSet(0);
	private Set colaboradoresAtividadeses = new HashSet(0);
	private Set colaboradoresProjetoses = new HashSet(0);
	private Set colaboradoresProgramases = new HashSet(0);
	private Set funcionarioses = new HashSet(0);

	public Cargos() {
	}

	public Cargos(long idCargo, String cdCargo, String nmCargo, String stTipoCargo) {
		this.idCargo = idCargo;
		this.cdCargo = cdCargo;
		this.nmCargo = nmCargo;
		this.stTipoCargo = stTipoCargo;
	}

	public Cargos(long idCargo, String cdCargo, String nmCargo, String stTipoCargo, Set contatosEmpresas,
			Set colaboradoresAtividadeses, Set colaboradoresProjetoses, Set colaboradoresProgramases,
			Set funcionarioses) {
		this.idCargo = idCargo;
		this.cdCargo = cdCargo;
		this.nmCargo = nmCargo;
		this.stTipoCargo = stTipoCargo;
		this.contatosEmpresas = contatosEmpresas;
		this.colaboradoresAtividadeses = colaboradoresAtividadeses;
		this.colaboradoresProjetoses = colaboradoresProjetoses;
		this.colaboradoresProgramases = colaboradoresProgramases;
		this.funcionarioses = funcionarioses;
	}

	public long getIdCargo() {
		return this.idCargo;
	}

	public void setIdCargo(long idCargo) {
		this.idCargo = idCargo;
	}

	public String getCdCargo() {
		return this.cdCargo;
	}

	public void setCdCargo(String cdCargo) {
		this.cdCargo = cdCargo;
	}

	public String getNmCargo() {
		return this.nmCargo;
	}

	public void setNmCargo(String nmCargo) {
		this.nmCargo = nmCargo;
	}

	public String getStTipoCargo() {
		return this.stTipoCargo;
	}

	public void setStTipoCargo(String stTipoCargo) {
		this.stTipoCargo = stTipoCargo;
	}

	public Set getContatosEmpresas() {
		return this.contatosEmpresas;
	}

	public void setContatosEmpresas(Set contatosEmpresas) {
		this.contatosEmpresas = contatosEmpresas;
	}

	public Set getColaboradoresAtividadeses() {
		return this.colaboradoresAtividadeses;
	}

	public void setColaboradoresAtividadeses(Set colaboradoresAtividadeses) {
		this.colaboradoresAtividadeses = colaboradoresAtividadeses;
	}

	public Set getColaboradoresProjetoses() {
		return this.colaboradoresProjetoses;
	}

	public void setColaboradoresProjetoses(Set colaboradoresProjetoses) {
		this.colaboradoresProjetoses = colaboradoresProjetoses;
	}

	public Set getColaboradoresProgramases() {
		return this.colaboradoresProgramases;
	}

	public void setColaboradoresProgramases(Set colaboradoresProgramases) {
		this.colaboradoresProgramases = colaboradoresProgramases;
	}

	public Set getFuncionarioses() {
		return this.funcionarioses;
	}

	public void setFuncionarioses(Set funcionarioses) {
		this.funcionarioses = funcionarioses;
	}

}
