package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

/**
 * CausasEfeitos generated by hbm2java
 */
public class CausasEfeitos implements java.io.Serializable {

	private long idCausaEfeito;
	private Indicadores indicadores;
	private String dsCausaEfeito;

	public CausasEfeitos() {
	}

	public CausasEfeitos(long idCausaEfeito, Indicadores indicadores, String dsCausaEfeito) {
		this.idCausaEfeito = idCausaEfeito;
		this.indicadores = indicadores;
		this.dsCausaEfeito = dsCausaEfeito;
	}

	public long getIdCausaEfeito() {
		return this.idCausaEfeito;
	}

	public void setIdCausaEfeito(long idCausaEfeito) {
		this.idCausaEfeito = idCausaEfeito;
	}

	public Indicadores getIndicadores() {
		return this.indicadores;
	}

	public void setIndicadores(Indicadores indicadores) {
		this.indicadores = indicadores;
	}

	public String getDsCausaEfeito() {
		return this.dsCausaEfeito;
	}

	public void setDsCausaEfeito(String dsCausaEfeito) {
		this.dsCausaEfeito = dsCausaEfeito;
	}

}
