package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * CentrosCusto generated by hbm2java
 */
public class CentrosCusto implements java.io.Serializable {

	private long idCentroCusto;
	private String nmCentroCusto;
	private String nrCentroCusto;
	private Set pedidoses = new HashSet(0);
	private Set itensFaturases = new HashSet(0);

	public CentrosCusto() {
	}

	public CentrosCusto(long idCentroCusto) {
		this.idCentroCusto = idCentroCusto;
	}

	public CentrosCusto(long idCentroCusto, String nmCentroCusto, String nrCentroCusto, Set pedidoses,
			Set itensFaturases) {
		this.idCentroCusto = idCentroCusto;
		this.nmCentroCusto = nmCentroCusto;
		this.nrCentroCusto = nrCentroCusto;
		this.pedidoses = pedidoses;
		this.itensFaturases = itensFaturases;
	}

	public long getIdCentroCusto() {
		return this.idCentroCusto;
	}

	public void setIdCentroCusto(long idCentroCusto) {
		this.idCentroCusto = idCentroCusto;
	}

	public String getNmCentroCusto() {
		return this.nmCentroCusto;
	}

	public void setNmCentroCusto(String nmCentroCusto) {
		this.nmCentroCusto = nmCentroCusto;
	}

	public String getNrCentroCusto() {
		return this.nrCentroCusto;
	}

	public void setNrCentroCusto(String nrCentroCusto) {
		this.nrCentroCusto = nrCentroCusto;
	}

	public Set getPedidoses() {
		return this.pedidoses;
	}

	public void setPedidoses(Set pedidoses) {
		this.pedidoses = pedidoses;
	}

	public Set getItensFaturases() {
		return this.itensFaturases;
	}

	public void setItensFaturases(Set itensFaturases) {
		this.itensFaturases = itensFaturases;
	}

}
