package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * ColaboradoresAtividades generated by hbm2java
 */
public class ColaboradoresAtividades implements java.io.Serializable {

	private long idColaboradorAtividade;
	private Atividades atividades;
	private Cargos cargos;
	private Funcionarios funcionarios;
	private Date dtEntradaAtividade;
	private Date dtSaidaAtividade;

	public ColaboradoresAtividades() {
	}

	public ColaboradoresAtividades(long idColaboradorAtividade, Atividades atividades, Cargos cargos,
			Funcionarios funcionarios, Date dtEntradaAtividade) {
		this.idColaboradorAtividade = idColaboradorAtividade;
		this.atividades = atividades;
		this.cargos = cargos;
		this.funcionarios = funcionarios;
		this.dtEntradaAtividade = dtEntradaAtividade;
	}

	public ColaboradoresAtividades(long idColaboradorAtividade, Atividades atividades, Cargos cargos,
			Funcionarios funcionarios, Date dtEntradaAtividade, Date dtSaidaAtividade) {
		this.idColaboradorAtividade = idColaboradorAtividade;
		this.atividades = atividades;
		this.cargos = cargos;
		this.funcionarios = funcionarios;
		this.dtEntradaAtividade = dtEntradaAtividade;
		this.dtSaidaAtividade = dtSaidaAtividade;
	}

	public long getIdColaboradorAtividade() {
		return this.idColaboradorAtividade;
	}

	public void setIdColaboradorAtividade(long idColaboradorAtividade) {
		this.idColaboradorAtividade = idColaboradorAtividade;
	}

	public Atividades getAtividades() {
		return this.atividades;
	}

	public void setAtividades(Atividades atividades) {
		this.atividades = atividades;
	}

	public Cargos getCargos() {
		return this.cargos;
	}

	public void setCargos(Cargos cargos) {
		this.cargos = cargos;
	}

	public Funcionarios getFuncionarios() {
		return this.funcionarios;
	}

	public void setFuncionarios(Funcionarios funcionarios) {
		this.funcionarios = funcionarios;
	}

	public Date getDtEntradaAtividade() {
		return this.dtEntradaAtividade;
	}

	public void setDtEntradaAtividade(Date dtEntradaAtividade) {
		this.dtEntradaAtividade = dtEntradaAtividade;
	}

	public Date getDtSaidaAtividade() {
		return this.dtSaidaAtividade;
	}

	public void setDtSaidaAtividade(Date dtSaidaAtividade) {
		this.dtSaidaAtividade = dtSaidaAtividade;
	}

}
