package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * ColaboradoresProgramas generated by hbm2java
 */
public class ColaboradoresProgramas implements java.io.Serializable {

	private long idColaboradorPrgrama;
	private Cargos cargos;
	private Funcionarios funcionarios;
	private Programas programas;
	private Date dtEntradaPrograma;
	private Date dtSaidaPrograma;

	public ColaboradoresProgramas() {
	}

	public ColaboradoresProgramas(long idColaboradorPrgrama, Cargos cargos, Funcionarios funcionarios,
			Programas programas, Date dtEntradaPrograma) {
		this.idColaboradorPrgrama = idColaboradorPrgrama;
		this.cargos = cargos;
		this.funcionarios = funcionarios;
		this.programas = programas;
		this.dtEntradaPrograma = dtEntradaPrograma;
	}

	public ColaboradoresProgramas(long idColaboradorPrgrama, Cargos cargos, Funcionarios funcionarios,
			Programas programas, Date dtEntradaPrograma, Date dtSaidaPrograma) {
		this.idColaboradorPrgrama = idColaboradorPrgrama;
		this.cargos = cargos;
		this.funcionarios = funcionarios;
		this.programas = programas;
		this.dtEntradaPrograma = dtEntradaPrograma;
		this.dtSaidaPrograma = dtSaidaPrograma;
	}

	public long getIdColaboradorPrgrama() {
		return this.idColaboradorPrgrama;
	}

	public void setIdColaboradorPrgrama(long idColaboradorPrgrama) {
		this.idColaboradorPrgrama = idColaboradorPrgrama;
	}

	public Cargos getCargos() {
		return this.cargos;
	}

	public void setCargos(Cargos cargos) {
		this.cargos = cargos;
	}

	public Funcionarios getFuncionarios() {
		return this.funcionarios;
	}

	public void setFuncionarios(Funcionarios funcionarios) {
		this.funcionarios = funcionarios;
	}

	public Programas getProgramas() {
		return this.programas;
	}

	public void setProgramas(Programas programas) {
		this.programas = programas;
	}

	public Date getDtEntradaPrograma() {
		return this.dtEntradaPrograma;
	}

	public void setDtEntradaPrograma(Date dtEntradaPrograma) {
		this.dtEntradaPrograma = dtEntradaPrograma;
	}

	public Date getDtSaidaPrograma() {
		return this.dtSaidaPrograma;
	}

	public void setDtSaidaPrograma(Date dtSaidaPrograma) {
		this.dtSaidaPrograma = dtSaidaPrograma;
	}

}
