package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * ColaboradoresProjetos generated by hbm2java
 */
public class ColaboradoresProjetos implements java.io.Serializable {

	private long idColaboradorProjeto;
	private Cargos cargos;
	private Funcionarios funcionarios;
	private Projetos projetos;
	private Date dtEntradaProjeto;
	private Date dtSaidaProjeto;

	public ColaboradoresProjetos() {
	}

	public ColaboradoresProjetos(long idColaboradorProjeto, Cargos cargos, Funcionarios funcionarios, Projetos projetos,
			Date dtEntradaProjeto) {
		this.idColaboradorProjeto = idColaboradorProjeto;
		this.cargos = cargos;
		this.funcionarios = funcionarios;
		this.projetos = projetos;
		this.dtEntradaProjeto = dtEntradaProjeto;
	}

	public ColaboradoresProjetos(long idColaboradorProjeto, Cargos cargos, Funcionarios funcionarios, Projetos projetos,
			Date dtEntradaProjeto, Date dtSaidaProjeto) {
		this.idColaboradorProjeto = idColaboradorProjeto;
		this.cargos = cargos;
		this.funcionarios = funcionarios;
		this.projetos = projetos;
		this.dtEntradaProjeto = dtEntradaProjeto;
		this.dtSaidaProjeto = dtSaidaProjeto;
	}

	public long getIdColaboradorProjeto() {
		return this.idColaboradorProjeto;
	}

	public void setIdColaboradorProjeto(long idColaboradorProjeto) {
		this.idColaboradorProjeto = idColaboradorProjeto;
	}

	public Cargos getCargos() {
		return this.cargos;
	}

	public void setCargos(Cargos cargos) {
		this.cargos = cargos;
	}

	public Funcionarios getFuncionarios() {
		return this.funcionarios;
	}

	public void setFuncionarios(Funcionarios funcionarios) {
		this.funcionarios = funcionarios;
	}

	public Projetos getProjetos() {
		return this.projetos;
	}

	public void setProjetos(Projetos projetos) {
		this.projetos = projetos;
	}

	public Date getDtEntradaProjeto() {
		return this.dtEntradaProjeto;
	}

	public void setDtEntradaProjeto(Date dtEntradaProjeto) {
		this.dtEntradaProjeto = dtEntradaProjeto;
	}

	public Date getDtSaidaProjeto() {
		return this.dtSaidaProjeto;
	}

	public void setDtSaidaProjeto(Date dtSaidaProjeto) {
		this.dtSaidaProjeto = dtSaidaProjeto;
	}

}
