package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * CondicoesMoradia generated by hbm2java
 */
public class CondicoesMoradia implements java.io.Serializable {

	private long idCondicaoMoradia;
	private String dsCondicaoMoradia;
	private Set pessoasFisicases = new HashSet(0);

	public CondicoesMoradia() {
	}

	public CondicoesMoradia(long idCondicaoMoradia, String dsCondicaoMoradia) {
		this.idCondicaoMoradia = idCondicaoMoradia;
		this.dsCondicaoMoradia = dsCondicaoMoradia;
	}

	public CondicoesMoradia(long idCondicaoMoradia, String dsCondicaoMoradia, Set pessoasFisicases) {
		this.idCondicaoMoradia = idCondicaoMoradia;
		this.dsCondicaoMoradia = dsCondicaoMoradia;
		this.pessoasFisicases = pessoasFisicases;
	}

	public long getIdCondicaoMoradia() {
		return this.idCondicaoMoradia;
	}

	public void setIdCondicaoMoradia(long idCondicaoMoradia) {
		this.idCondicaoMoradia = idCondicaoMoradia;
	}

	public String getDsCondicaoMoradia() {
		return this.dsCondicaoMoradia;
	}

	public void setDsCondicaoMoradia(String dsCondicaoMoradia) {
		this.dsCondicaoMoradia = dsCondicaoMoradia;
	}

	public Set getPessoasFisicases() {
		return this.pessoasFisicases;
	}

	public void setPessoasFisicases(Set pessoasFisicases) {
		this.pessoasFisicases = pessoasFisicases;
	}

}
