package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ContasBancarias generated by hbm2java
 */
public class ContasBancarias implements java.io.Serializable {

	private long idContaBancaria;
	private Unidades unidades;
	private String csTipoContaBancaria;
	private Date nrContaBancaria;
	private BigDecimal nrBanco;
	private String nmBanco;
	private String nrAgencia;
	private Set pagamentosFaturases = new HashSet(0);
	private Set movimentacoesContas = new HashSet(0);

	public ContasBancarias() {
	}

	public ContasBancarias(long idContaBancaria, Unidades unidades) {
		this.idContaBancaria = idContaBancaria;
		this.unidades = unidades;
	}

	public ContasBancarias(long idContaBancaria, Unidades unidades, String csTipoContaBancaria, Date nrContaBancaria,
			BigDecimal nrBanco, String nmBanco, String nrAgencia, Set pagamentosFaturases, Set movimentacoesContas) {
		this.idContaBancaria = idContaBancaria;
		this.unidades = unidades;
		this.csTipoContaBancaria = csTipoContaBancaria;
		this.nrContaBancaria = nrContaBancaria;
		this.nrBanco = nrBanco;
		this.nmBanco = nmBanco;
		this.nrAgencia = nrAgencia;
		this.pagamentosFaturases = pagamentosFaturases;
		this.movimentacoesContas = movimentacoesContas;
	}

	public long getIdContaBancaria() {
		return this.idContaBancaria;
	}

	public void setIdContaBancaria(long idContaBancaria) {
		this.idContaBancaria = idContaBancaria;
	}

	public Unidades getUnidades() {
		return this.unidades;
	}

	public void setUnidades(Unidades unidades) {
		this.unidades = unidades;
	}

	public String getCsTipoContaBancaria() {
		return this.csTipoContaBancaria;
	}

	public void setCsTipoContaBancaria(String csTipoContaBancaria) {
		this.csTipoContaBancaria = csTipoContaBancaria;
	}

	public Date getNrContaBancaria() {
		return this.nrContaBancaria;
	}

	public void setNrContaBancaria(Date nrContaBancaria) {
		this.nrContaBancaria = nrContaBancaria;
	}

	public BigDecimal getNrBanco() {
		return this.nrBanco;
	}

	public void setNrBanco(BigDecimal nrBanco) {
		this.nrBanco = nrBanco;
	}

	public String getNmBanco() {
		return this.nmBanco;
	}

	public void setNmBanco(String nmBanco) {
		this.nmBanco = nmBanco;
	}

	public String getNrAgencia() {
		return this.nrAgencia;
	}

	public void setNrAgencia(String nrAgencia) {
		this.nrAgencia = nrAgencia;
	}

	public Set getPagamentosFaturases() {
		return this.pagamentosFaturases;
	}

	public void setPagamentosFaturases(Set pagamentosFaturases) {
		this.pagamentosFaturases = pagamentosFaturases;
	}

	public Set getMovimentacoesContas() {
		return this.movimentacoesContas;
	}

	public void setMovimentacoesContas(Set movimentacoesContas) {
		this.movimentacoesContas = movimentacoesContas;
	}

}
