package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * ContatosEmpresa generated by hbm2java
 */
public class ContatosEmpresa implements java.io.Serializable {

	private long idContatoEmpresa;
	private Cargos cargos;
	private Empresas empresas;
	private PessoasFisicas pessoasFisicas;
	private String dsFimContato;
	private Date dtInicioContato;
	private Date dtFimContato;

	public ContatosEmpresa() {
	}

	public ContatosEmpresa(long idContatoEmpresa, Cargos cargos, Empresas empresas, PessoasFisicas pessoasFisicas) {
		this.idContatoEmpresa = idContatoEmpresa;
		this.cargos = cargos;
		this.empresas = empresas;
		this.pessoasFisicas = pessoasFisicas;
	}

	public ContatosEmpresa(long idContatoEmpresa, Cargos cargos, Empresas empresas, PessoasFisicas pessoasFisicas,
			String dsFimContato, Date dtInicioContato, Date dtFimContato) {
		this.idContatoEmpresa = idContatoEmpresa;
		this.cargos = cargos;
		this.empresas = empresas;
		this.pessoasFisicas = pessoasFisicas;
		this.dsFimContato = dsFimContato;
		this.dtInicioContato = dtInicioContato;
		this.dtFimContato = dtFimContato;
	}

	public long getIdContatoEmpresa() {
		return this.idContatoEmpresa;
	}

	public void setIdContatoEmpresa(long idContatoEmpresa) {
		this.idContatoEmpresa = idContatoEmpresa;
	}

	public Cargos getCargos() {
		return this.cargos;
	}

	public void setCargos(Cargos cargos) {
		this.cargos = cargos;
	}

	public Empresas getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Empresas empresas) {
		this.empresas = empresas;
	}

	public PessoasFisicas getPessoasFisicas() {
		return this.pessoasFisicas;
	}

	public void setPessoasFisicas(PessoasFisicas pessoasFisicas) {
		this.pessoasFisicas = pessoasFisicas;
	}

	public String getDsFimContato() {
		return this.dsFimContato;
	}

	public void setDsFimContato(String dsFimContato) {
		this.dsFimContato = dsFimContato;
	}

	public Date getDtInicioContato() {
		return this.dtInicioContato;
	}

	public void setDtInicioContato(Date dtInicioContato) {
		this.dtInicioContato = dtInicioContato;
	}

	public Date getDtFimContato() {
		return this.dtFimContato;
	}

	public void setDtFimContato(Date dtFimContato) {
		this.dtFimContato = dtFimContato;
	}

}
