package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * CursosFormacaoPf generated by hbm2java
 */
public class CursosFormacaoPf implements java.io.Serializable {

	private long idCurso;
	private PessoasFisicas pessoasFisicas;
	private String nmCurso;
	private String nmInstuicao;
	private Date dtInicioCurso;
	private Date dtFimCurso;

	public CursosFormacaoPf() {
	}

	public CursosFormacaoPf(long idCurso, PessoasFisicas pessoasFisicas, String nmCurso) {
		this.idCurso = idCurso;
		this.pessoasFisicas = pessoasFisicas;
		this.nmCurso = nmCurso;
	}

	public CursosFormacaoPf(long idCurso, PessoasFisicas pessoasFisicas, String nmCurso, String nmInstuicao,
			Date dtInicioCurso, Date dtFimCurso) {
		this.idCurso = idCurso;
		this.pessoasFisicas = pessoasFisicas;
		this.nmCurso = nmCurso;
		this.nmInstuicao = nmInstuicao;
		this.dtInicioCurso = dtInicioCurso;
		this.dtFimCurso = dtFimCurso;
	}

	public long getIdCurso() {
		return this.idCurso;
	}

	public void setIdCurso(long idCurso) {
		this.idCurso = idCurso;
	}

	public PessoasFisicas getPessoasFisicas() {
		return this.pessoasFisicas;
	}

	public void setPessoasFisicas(PessoasFisicas pessoasFisicas) {
		this.pessoasFisicas = pessoasFisicas;
	}

	public String getNmCurso() {
		return this.nmCurso;
	}

	public void setNmCurso(String nmCurso) {
		this.nmCurso = nmCurso;
	}

	public String getNmInstuicao() {
		return this.nmInstuicao;
	}

	public void setNmInstuicao(String nmInstuicao) {
		this.nmInstuicao = nmInstuicao;
	}

	public Date getDtInicioCurso() {
		return this.dtInicioCurso;
	}

	public void setDtInicioCurso(Date dtInicioCurso) {
		this.dtInicioCurso = dtInicioCurso;
	}

	public Date getDtFimCurso() {
		return this.dtFimCurso;
	}

	public void setDtFimCurso(Date dtFimCurso) {
		this.dtFimCurso = dtFimCurso;
	}

}
