package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * DepartamentosUnidades generated by hbm2java
 */
public class DepartamentosUnidades implements java.io.Serializable {

	private long idDepartamento;
	private DepartamentosUnidades departamentosUnidades;
	private Unidades unidades;
	private String cdUnidadeDepartamento;
	private String nmDepartamento;
	private String nrTelefoneDepartamento;
	private String dsEnderecoDepartamento;
	private Set departamentosUnidadeses = new HashSet(0);

	public DepartamentosUnidades() {
	}

	public DepartamentosUnidades(long idDepartamento, Unidades unidades, String cdUnidadeDepartamento,
			String nmDepartamento) {
		this.idDepartamento = idDepartamento;
		this.unidades = unidades;
		this.cdUnidadeDepartamento = cdUnidadeDepartamento;
		this.nmDepartamento = nmDepartamento;
	}

	public DepartamentosUnidades(long idDepartamento, DepartamentosUnidades departamentosUnidades, Unidades unidades,
			String cdUnidadeDepartamento, String nmDepartamento, String nrTelefoneDepartamento,
			String dsEnderecoDepartamento, Set departamentosUnidadeses) {
		this.idDepartamento = idDepartamento;
		this.departamentosUnidades = departamentosUnidades;
		this.unidades = unidades;
		this.cdUnidadeDepartamento = cdUnidadeDepartamento;
		this.nmDepartamento = nmDepartamento;
		this.nrTelefoneDepartamento = nrTelefoneDepartamento;
		this.dsEnderecoDepartamento = dsEnderecoDepartamento;
		this.departamentosUnidadeses = departamentosUnidadeses;
	}

	public long getIdDepartamento() {
		return this.idDepartamento;
	}

	public void setIdDepartamento(long idDepartamento) {
		this.idDepartamento = idDepartamento;
	}

	public DepartamentosUnidades getDepartamentosUnidades() {
		return this.departamentosUnidades;
	}

	public void setDepartamentosUnidades(DepartamentosUnidades departamentosUnidades) {
		this.departamentosUnidades = departamentosUnidades;
	}

	public Unidades getUnidades() {
		return this.unidades;
	}

	public void setUnidades(Unidades unidades) {
		this.unidades = unidades;
	}

	public String getCdUnidadeDepartamento() {
		return this.cdUnidadeDepartamento;
	}

	public void setCdUnidadeDepartamento(String cdUnidadeDepartamento) {
		this.cdUnidadeDepartamento = cdUnidadeDepartamento;
	}

	public String getNmDepartamento() {
		return this.nmDepartamento;
	}

	public void setNmDepartamento(String nmDepartamento) {
		this.nmDepartamento = nmDepartamento;
	}

	public String getNrTelefoneDepartamento() {
		return this.nrTelefoneDepartamento;
	}

	public void setNrTelefoneDepartamento(String nrTelefoneDepartamento) {
		this.nrTelefoneDepartamento = nrTelefoneDepartamento;
	}

	public String getDsEnderecoDepartamento() {
		return this.dsEnderecoDepartamento;
	}

	public void setDsEnderecoDepartamento(String dsEnderecoDepartamento) {
		this.dsEnderecoDepartamento = dsEnderecoDepartamento;
	}

	public Set getDepartamentosUnidadeses() {
		return this.departamentosUnidadeses;
	}

	public void setDepartamentosUnidadeses(Set departamentosUnidadeses) {
		this.departamentosUnidadeses = departamentosUnidadeses;
	}

}
