package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Diagnosticos generated by hbm2java
 */
public class Diagnosticos implements java.io.Serializable {

	private long idDiagnostico;
	private String dsDiagnostico;
	private Set atendimentoses = new HashSet(0);

	public Diagnosticos() {
	}

	public Diagnosticos(long idDiagnostico, String dsDiagnostico) {
		this.idDiagnostico = idDiagnostico;
		this.dsDiagnostico = dsDiagnostico;
	}

	public Diagnosticos(long idDiagnostico, String dsDiagnostico, Set atendimentoses) {
		this.idDiagnostico = idDiagnostico;
		this.dsDiagnostico = dsDiagnostico;
		this.atendimentoses = atendimentoses;
	}

	public long getIdDiagnostico() {
		return this.idDiagnostico;
	}

	public void setIdDiagnostico(long idDiagnostico) {
		this.idDiagnostico = idDiagnostico;
	}

	public String getDsDiagnostico() {
		return this.dsDiagnostico;
	}

	public void setDsDiagnostico(String dsDiagnostico) {
		this.dsDiagnostico = dsDiagnostico;
	}

	public Set getAtendimentoses() {
		return this.atendimentoses;
	}

	public void setAtendimentoses(Set atendimentoses) {
		this.atendimentoses = atendimentoses;
	}

}
