package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

/**
 * DocumentosAtividades generated by hbm2java
 */
public class DocumentosAtividades implements java.io.Serializable {

	private DocumentosAtividadesId id;
	private Atividades atividades;

	public DocumentosAtividades() {
	}

	public DocumentosAtividades(DocumentosAtividadesId id, Atividades atividades) {
		this.id = id;
		this.atividades = atividades;
	}

	public DocumentosAtividadesId getId() {
		return this.id;
	}

	public void setId(DocumentosAtividadesId id) {
		this.id = id;
	}

	public Atividades getAtividades() {
		return this.atividades;
	}

	public void setAtividades(Atividades atividades) {
		this.atividades = atividades;
	}

}
