package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

/**
 * DocumentosAtividadesId generated by hbm2java
 */
public class DocumentosAtividadesId implements java.io.Serializable {

	private long idDocumentoAtividade;
	private String dsDocumentoAtividade;
	private String txDocumentoAtividade;
	private long idAtividade;

	public DocumentosAtividadesId() {
	}

	public DocumentosAtividadesId(long idDocumentoAtividade, String dsDocumentoAtividade, long idAtividade) {
		this.idDocumentoAtividade = idDocumentoAtividade;
		this.dsDocumentoAtividade = dsDocumentoAtividade;
		this.idAtividade = idAtividade;
	}

	public DocumentosAtividadesId(long idDocumentoAtividade, String dsDocumentoAtividade, String txDocumentoAtividade,
			long idAtividade) {
		this.idDocumentoAtividade = idDocumentoAtividade;
		this.dsDocumentoAtividade = dsDocumentoAtividade;
		this.txDocumentoAtividade = txDocumentoAtividade;
		this.idAtividade = idAtividade;
	}

	public long getIdDocumentoAtividade() {
		return this.idDocumentoAtividade;
	}

	public void setIdDocumentoAtividade(long idDocumentoAtividade) {
		this.idDocumentoAtividade = idDocumentoAtividade;
	}

	public String getDsDocumentoAtividade() {
		return this.dsDocumentoAtividade;
	}

	public void setDsDocumentoAtividade(String dsDocumentoAtividade) {
		this.dsDocumentoAtividade = dsDocumentoAtividade;
	}

	public String getTxDocumentoAtividade() {
		return this.txDocumentoAtividade;
	}

	public void setTxDocumentoAtividade(String txDocumentoAtividade) {
		this.txDocumentoAtividade = txDocumentoAtividade;
	}

	public long getIdAtividade() {
		return this.idAtividade;
	}

	public void setIdAtividade(long idAtividade) {
		this.idAtividade = idAtividade;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DocumentosAtividadesId))
			return false;
		DocumentosAtividadesId castOther = (DocumentosAtividadesId) other;

		return (this.getIdDocumentoAtividade() == castOther.getIdDocumentoAtividade())
				&& ((this.getDsDocumentoAtividade() == castOther.getDsDocumentoAtividade())
						|| (this.getDsDocumentoAtividade() != null && castOther.getDsDocumentoAtividade() != null
								&& this.getDsDocumentoAtividade().equals(castOther.getDsDocumentoAtividade())))
				&& ((this.getTxDocumentoAtividade() == castOther.getTxDocumentoAtividade())
						|| (this.getTxDocumentoAtividade() != null && castOther.getTxDocumentoAtividade() != null
								&& this.getTxDocumentoAtividade().equals(castOther.getTxDocumentoAtividade())))
				&& (this.getIdAtividade() == castOther.getIdAtividade());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdDocumentoAtividade();
		result = 37 * result + (getDsDocumentoAtividade() == null ? 0 : this.getDsDocumentoAtividade().hashCode());
		result = 37 * result + (getTxDocumentoAtividade() == null ? 0 : this.getTxDocumentoAtividade().hashCode());
		result = 37 * result + (int) this.getIdAtividade();
		return result;
	}

}
