package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresas generated by hbm2java
 */
public class Empresas implements java.io.Serializable {

	private long idEmpresa;
	private String cdEmpresa;
	private String nmRazaoSocial;
	private String nmFantasia;
	private String nrCnpj;
	private String nrInscricaoEstadual;
	private String nrInscricaoMunicipal;
	private String stAtiva;
	private String csTipoEmpresa;
	private BigDecimal vlIcms;
	private String dsTipoEmpresa;
	private String csCategoriaEmpresa;
	private String dsCategoriaEmpresa;
	private String nrTelefone;
	private String dsEmail;
	private String stAutorizaEmail;
	private String dsHomePage;
	private String dsEndereco;
	private String dsBairro;
	private Integer nrCep;
	private String ufEmpresa;
	private String nmCidade;
	private Set contatosEmpresas = new HashSet(0);
	private Set funcionarioses = new HashSet(0);
	private Set entidadesSociaises = new HashSet(0);
	private Set faturases = new HashSet(0);

	public Empresas() {
	}

	public Empresas(long idEmpresa, String cdEmpresa, String nmRazaoSocial, String csTipoEmpresa, String nrTelefone,
			String dsEndereco) {
		this.idEmpresa = idEmpresa;
		this.cdEmpresa = cdEmpresa;
		this.nmRazaoSocial = nmRazaoSocial;
		this.csTipoEmpresa = csTipoEmpresa;
		this.nrTelefone = nrTelefone;
		this.dsEndereco = dsEndereco;
	}

	public Empresas(long idEmpresa, String cdEmpresa, String nmRazaoSocial, String nmFantasia, String nrCnpj,
			String nrInscricaoEstadual, String nrInscricaoMunicipal, String stAtiva, String csTipoEmpresa,
			BigDecimal vlIcms, String dsTipoEmpresa, String csCategoriaEmpresa, String dsCategoriaEmpresa,
			String nrTelefone, String dsEmail, String stAutorizaEmail, String dsHomePage, String dsEndereco,
			String dsBairro, Integer nrCep, String ufEmpresa, String nmCidade, Set contatosEmpresas, Set funcionarioses,
			Set entidadesSociaises, Set faturases) {
		this.idEmpresa = idEmpresa;
		this.cdEmpresa = cdEmpresa;
		this.nmRazaoSocial = nmRazaoSocial;
		this.nmFantasia = nmFantasia;
		this.nrCnpj = nrCnpj;
		this.nrInscricaoEstadual = nrInscricaoEstadual;
		this.nrInscricaoMunicipal = nrInscricaoMunicipal;
		this.stAtiva = stAtiva;
		this.csTipoEmpresa = csTipoEmpresa;
		this.vlIcms = vlIcms;
		this.dsTipoEmpresa = dsTipoEmpresa;
		this.csCategoriaEmpresa = csCategoriaEmpresa;
		this.dsCategoriaEmpresa = dsCategoriaEmpresa;
		this.nrTelefone = nrTelefone;
		this.dsEmail = dsEmail;
		this.stAutorizaEmail = stAutorizaEmail;
		this.dsHomePage = dsHomePage;
		this.dsEndereco = dsEndereco;
		this.dsBairro = dsBairro;
		this.nrCep = nrCep;
		this.ufEmpresa = ufEmpresa;
		this.nmCidade = nmCidade;
		this.contatosEmpresas = contatosEmpresas;
		this.funcionarioses = funcionarioses;
		this.entidadesSociaises = entidadesSociaises;
		this.faturases = faturases;
	}

	public long getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(long idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	public String getCdEmpresa() {
		return this.cdEmpresa;
	}

	public void setCdEmpresa(String cdEmpresa) {
		this.cdEmpresa = cdEmpresa;
	}

	public String getNmRazaoSocial() {
		return this.nmRazaoSocial;
	}

	public void setNmRazaoSocial(String nmRazaoSocial) {
		this.nmRazaoSocial = nmRazaoSocial;
	}

	public String getNmFantasia() {
		return this.nmFantasia;
	}

	public void setNmFantasia(String nmFantasia) {
		this.nmFantasia = nmFantasia;
	}

	public String getNrCnpj() {
		return this.nrCnpj;
	}

	public void setNrCnpj(String nrCnpj) {
		this.nrCnpj = nrCnpj;
	}

	public String getNrInscricaoEstadual() {
		return this.nrInscricaoEstadual;
	}

	public void setNrInscricaoEstadual(String nrInscricaoEstadual) {
		this.nrInscricaoEstadual = nrInscricaoEstadual;
	}

	public String getNrInscricaoMunicipal() {
		return this.nrInscricaoMunicipal;
	}

	public void setNrInscricaoMunicipal(String nrInscricaoMunicipal) {
		this.nrInscricaoMunicipal = nrInscricaoMunicipal;
	}

	public String getStAtiva() {
		return this.stAtiva;
	}

	public void setStAtiva(String stAtiva) {
		this.stAtiva = stAtiva;
	}

	public String getCsTipoEmpresa() {
		return this.csTipoEmpresa;
	}

	public void setCsTipoEmpresa(String csTipoEmpresa) {
		this.csTipoEmpresa = csTipoEmpresa;
	}

	public BigDecimal getVlIcms() {
		return this.vlIcms;
	}

	public void setVlIcms(BigDecimal vlIcms) {
		this.vlIcms = vlIcms;
	}

	public String getDsTipoEmpresa() {
		return this.dsTipoEmpresa;
	}

	public void setDsTipoEmpresa(String dsTipoEmpresa) {
		this.dsTipoEmpresa = dsTipoEmpresa;
	}

	public String getCsCategoriaEmpresa() {
		return this.csCategoriaEmpresa;
	}

	public void setCsCategoriaEmpresa(String csCategoriaEmpresa) {
		this.csCategoriaEmpresa = csCategoriaEmpresa;
	}

	public String getDsCategoriaEmpresa() {
		return this.dsCategoriaEmpresa;
	}

	public void setDsCategoriaEmpresa(String dsCategoriaEmpresa) {
		this.dsCategoriaEmpresa = dsCategoriaEmpresa;
	}

	public String getNrTelefone() {
		return this.nrTelefone;
	}

	public void setNrTelefone(String nrTelefone) {
		this.nrTelefone = nrTelefone;
	}

	public String getDsEmail() {
		return this.dsEmail;
	}

	public void setDsEmail(String dsEmail) {
		this.dsEmail = dsEmail;
	}

	public String getStAutorizaEmail() {
		return this.stAutorizaEmail;
	}

	public void setStAutorizaEmail(String stAutorizaEmail) {
		this.stAutorizaEmail = stAutorizaEmail;
	}

	public String getDsHomePage() {
		return this.dsHomePage;
	}

	public void setDsHomePage(String dsHomePage) {
		this.dsHomePage = dsHomePage;
	}

	public String getDsEndereco() {
		return this.dsEndereco;
	}

	public void setDsEndereco(String dsEndereco) {
		this.dsEndereco = dsEndereco;
	}

	public String getDsBairro() {
		return this.dsBairro;
	}

	public void setDsBairro(String dsBairro) {
		this.dsBairro = dsBairro;
	}

	public Integer getNrCep() {
		return this.nrCep;
	}

	public void setNrCep(Integer nrCep) {
		this.nrCep = nrCep;
	}

	public String getUfEmpresa() {
		return this.ufEmpresa;
	}

	public void setUfEmpresa(String ufEmpresa) {
		this.ufEmpresa = ufEmpresa;
	}

	public String getNmCidade() {
		return this.nmCidade;
	}

	public void setNmCidade(String nmCidade) {
		this.nmCidade = nmCidade;
	}

	public Set getContatosEmpresas() {
		return this.contatosEmpresas;
	}

	public void setContatosEmpresas(Set contatosEmpresas) {
		this.contatosEmpresas = contatosEmpresas;
	}

	public Set getFuncionarioses() {
		return this.funcionarioses;
	}

	public void setFuncionarioses(Set funcionarioses) {
		this.funcionarioses = funcionarioses;
	}

	public Set getEntidadesSociaises() {
		return this.entidadesSociaises;
	}

	public void setEntidadesSociaises(Set entidadesSociaises) {
		this.entidadesSociaises = entidadesSociaises;
	}

	public Set getFaturases() {
		return this.faturases;
	}

	public void setFaturases(Set faturases) {
		this.faturases = faturases;
	}

}
