package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

/**
 * EncaminhaAlunos generated by hbm2java
 */
public class EncaminhaAlunos implements java.io.Serializable {

	private long idEncaminhaAluno;
	private Alunos alunos;
	private EntidadesSociais entidadesSociais;
	private String dtEncaminhaAluno;
	private String dsEncaminhaAluno;

	public EncaminhaAlunos() {
	}

	public EncaminhaAlunos(long idEncaminhaAluno, Alunos alunos, EntidadesSociais entidadesSociais) {
		this.idEncaminhaAluno = idEncaminhaAluno;
		this.alunos = alunos;
		this.entidadesSociais = entidadesSociais;
	}

	public EncaminhaAlunos(long idEncaminhaAluno, Alunos alunos, EntidadesSociais entidadesSociais,
			String dtEncaminhaAluno, String dsEncaminhaAluno) {
		this.idEncaminhaAluno = idEncaminhaAluno;
		this.alunos = alunos;
		this.entidadesSociais = entidadesSociais;
		this.dtEncaminhaAluno = dtEncaminhaAluno;
		this.dsEncaminhaAluno = dsEncaminhaAluno;
	}

	public long getIdEncaminhaAluno() {
		return this.idEncaminhaAluno;
	}

	public void setIdEncaminhaAluno(long idEncaminhaAluno) {
		this.idEncaminhaAluno = idEncaminhaAluno;
	}

	public Alunos getAlunos() {
		return this.alunos;
	}

	public void setAlunos(Alunos alunos) {
		this.alunos = alunos;
	}

	public EntidadesSociais getEntidadesSociais() {
		return this.entidadesSociais;
	}

	public void setEntidadesSociais(EntidadesSociais entidadesSociais) {
		this.entidadesSociais = entidadesSociais;
	}

	public String getDtEncaminhaAluno() {
		return this.dtEncaminhaAluno;
	}

	public void setDtEncaminhaAluno(String dtEncaminhaAluno) {
		this.dtEncaminhaAluno = dtEncaminhaAluno;
	}

	public String getDsEncaminhaAluno() {
		return this.dsEncaminhaAluno;
	}

	public void setDsEncaminhaAluno(String dsEncaminhaAluno) {
		this.dsEncaminhaAluno = dsEncaminhaAluno;
	}

}
