package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EntidadesSociais generated by hbm2java
 */
public class EntidadesSociais implements java.io.Serializable {

	private long idEntidadeSocial;
	private Empresas empresas;
	private Date dtVinculoEntidadeSocial;
	private Date dtFimEntidadeSocial;
	private Set encaminhaAlunoses = new HashSet(0);

	public EntidadesSociais() {
	}

	public EntidadesSociais(long idEntidadeSocial, Empresas empresas) {
		this.idEntidadeSocial = idEntidadeSocial;
		this.empresas = empresas;
	}

	public EntidadesSociais(long idEntidadeSocial, Empresas empresas, Date dtVinculoEntidadeSocial,
			Date dtFimEntidadeSocial, Set encaminhaAlunoses) {
		this.idEntidadeSocial = idEntidadeSocial;
		this.empresas = empresas;
		this.dtVinculoEntidadeSocial = dtVinculoEntidadeSocial;
		this.dtFimEntidadeSocial = dtFimEntidadeSocial;
		this.encaminhaAlunoses = encaminhaAlunoses;
	}

	public long getIdEntidadeSocial() {
		return this.idEntidadeSocial;
	}

	public void setIdEntidadeSocial(long idEntidadeSocial) {
		this.idEntidadeSocial = idEntidadeSocial;
	}

	public Empresas getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Empresas empresas) {
		this.empresas = empresas;
	}

	public Date getDtVinculoEntidadeSocial() {
		return this.dtVinculoEntidadeSocial;
	}

	public void setDtVinculoEntidadeSocial(Date dtVinculoEntidadeSocial) {
		this.dtVinculoEntidadeSocial = dtVinculoEntidadeSocial;
	}

	public Date getDtFimEntidadeSocial() {
		return this.dtFimEntidadeSocial;
	}

	public void setDtFimEntidadeSocial(Date dtFimEntidadeSocial) {
		this.dtFimEntidadeSocial = dtFimEntidadeSocial;
	}

	public Set getEncaminhaAlunoses() {
		return this.encaminhaAlunoses;
	}

	public void setEncaminhaAlunoses(Set encaminhaAlunoses) {
		this.encaminhaAlunoses = encaminhaAlunoses;
	}

}
