package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Entidades generated by hbm2java
 */
public class Entidades implements java.io.Serializable {

	private long idEntidade;
	private Arquivos arquivos;
	private String cdEntidade;
	private String nmEntidade;
	private String dsVisao;
	private String dsMissao;
	private Set perspectivases = new HashSet(0);
	private Set unidadeses = new HashSet(0);

	public Entidades() {
	}

	public Entidades(long idEntidade, String cdEntidade, String nmEntidade, String dsVisao, String dsMissao) {
		this.idEntidade = idEntidade;
		this.cdEntidade = cdEntidade;
		this.nmEntidade = nmEntidade;
		this.dsVisao = dsVisao;
		this.dsMissao = dsMissao;
	}

	public Entidades(long idEntidade, Arquivos arquivos, String cdEntidade, String nmEntidade, String dsVisao,
			String dsMissao, Set perspectivases, Set unidadeses) {
		this.idEntidade = idEntidade;
		this.arquivos = arquivos;
		this.cdEntidade = cdEntidade;
		this.nmEntidade = nmEntidade;
		this.dsVisao = dsVisao;
		this.dsMissao = dsMissao;
		this.perspectivases = perspectivases;
		this.unidadeses = unidadeses;
	}

	public long getIdEntidade() {
		return this.idEntidade;
	}

	public void setIdEntidade(long idEntidade) {
		this.idEntidade = idEntidade;
	}

	public Arquivos getArquivos() {
		return this.arquivos;
	}

	public void setArquivos(Arquivos arquivos) {
		this.arquivos = arquivos;
	}

	public String getCdEntidade() {
		return this.cdEntidade;
	}

	public void setCdEntidade(String cdEntidade) {
		this.cdEntidade = cdEntidade;
	}

	public String getNmEntidade() {
		return this.nmEntidade;
	}

	public void setNmEntidade(String nmEntidade) {
		this.nmEntidade = nmEntidade;
	}

	public String getDsVisao() {
		return this.dsVisao;
	}

	public void setDsVisao(String dsVisao) {
		this.dsVisao = dsVisao;
	}

	public String getDsMissao() {
		return this.dsMissao;
	}

	public void setDsMissao(String dsMissao) {
		this.dsMissao = dsMissao;
	}

	public Set getPerspectivases() {
		return this.perspectivases;
	}

	public void setPerspectivases(Set perspectivases) {
		this.perspectivases = perspectivases;
	}

	public Set getUnidadeses() {
		return this.unidadeses;
	}

	public void setUnidadeses(Set unidadeses) {
		this.unidadeses = unidadeses;
	}

}
