package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;

/**
 * Estoques generated by hbm2java
 */
public class Estoques implements java.io.Serializable {

	private long idEstoque;
	private Funcionarios funcionarios;
	private Produtos produtos;
	private Unidades unidades;
	private BigDecimal qtMovEstoque;
	private Date dtMovEstoque;
	private String csTipoMovEstoque;
	private String dsMovEstoque;
	private BigDecimal qtEstoque;
	private Date dtAtzEstoque;

	public Estoques() {
	}

	public Estoques(long idEstoque, Funcionarios funcionarios, Produtos produtos, Unidades unidades) {
		this.idEstoque = idEstoque;
		this.funcionarios = funcionarios;
		this.produtos = produtos;
		this.unidades = unidades;
	}

	public Estoques(long idEstoque, Funcionarios funcionarios, Produtos produtos, Unidades unidades,
			BigDecimal qtMovEstoque, Date dtMovEstoque, String csTipoMovEstoque, String dsMovEstoque,
			BigDecimal qtEstoque, Date dtAtzEstoque) {
		this.idEstoque = idEstoque;
		this.funcionarios = funcionarios;
		this.produtos = produtos;
		this.unidades = unidades;
		this.qtMovEstoque = qtMovEstoque;
		this.dtMovEstoque = dtMovEstoque;
		this.csTipoMovEstoque = csTipoMovEstoque;
		this.dsMovEstoque = dsMovEstoque;
		this.qtEstoque = qtEstoque;
		this.dtAtzEstoque = dtAtzEstoque;
	}

	public long getIdEstoque() {
		return this.idEstoque;
	}

	public void setIdEstoque(long idEstoque) {
		this.idEstoque = idEstoque;
	}

	public Funcionarios getFuncionarios() {
		return this.funcionarios;
	}

	public void setFuncionarios(Funcionarios funcionarios) {
		this.funcionarios = funcionarios;
	}

	public Produtos getProdutos() {
		return this.produtos;
	}

	public void setProdutos(Produtos produtos) {
		this.produtos = produtos;
	}

	public Unidades getUnidades() {
		return this.unidades;
	}

	public void setUnidades(Unidades unidades) {
		this.unidades = unidades;
	}

	public BigDecimal getQtMovEstoque() {
		return this.qtMovEstoque;
	}

	public void setQtMovEstoque(BigDecimal qtMovEstoque) {
		this.qtMovEstoque = qtMovEstoque;
	}

	public Date getDtMovEstoque() {
		return this.dtMovEstoque;
	}

	public void setDtMovEstoque(Date dtMovEstoque) {
		this.dtMovEstoque = dtMovEstoque;
	}

	public String getCsTipoMovEstoque() {
		return this.csTipoMovEstoque;
	}

	public void setCsTipoMovEstoque(String csTipoMovEstoque) {
		this.csTipoMovEstoque = csTipoMovEstoque;
	}

	public String getDsMovEstoque() {
		return this.dsMovEstoque;
	}

	public void setDsMovEstoque(String dsMovEstoque) {
		this.dsMovEstoque = dsMovEstoque;
	}

	public BigDecimal getQtEstoque() {
		return this.qtEstoque;
	}

	public void setQtEstoque(BigDecimal qtEstoque) {
		this.qtEstoque = qtEstoque;
	}

	public Date getDtAtzEstoque() {
		return this.dtAtzEstoque;
	}

	public void setDtAtzEstoque(Date dtAtzEstoque) {
		this.dtAtzEstoque = dtAtzEstoque;
	}

}
