package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * FaltasFuncionarios generated by hbm2java
 */
public class FaltasFuncionarios implements java.io.Serializable {

	private long idFaltaFuncionario;
	private Funcionarios funcionariosByIdFuncionarioFalta;
	private Funcionarios funcionariosByIdFuncionarioCadastro;
	private String dsFaltaFuncionario;
	private String dsJutifiFalta;
	private Date dtFaltaFuncionario;
	private Date dtCadastro;

	public FaltasFuncionarios() {
	}

	public FaltasFuncionarios(long idFaltaFuncionario, Funcionarios funcionariosByIdFuncionarioFalta,
			Funcionarios funcionariosByIdFuncionarioCadastro, String dsFaltaFuncionario) {
		this.idFaltaFuncionario = idFaltaFuncionario;
		this.funcionariosByIdFuncionarioFalta = funcionariosByIdFuncionarioFalta;
		this.funcionariosByIdFuncionarioCadastro = funcionariosByIdFuncionarioCadastro;
		this.dsFaltaFuncionario = dsFaltaFuncionario;
	}

	public FaltasFuncionarios(long idFaltaFuncionario, Funcionarios funcionariosByIdFuncionarioFalta,
			Funcionarios funcionariosByIdFuncionarioCadastro, String dsFaltaFuncionario, String dsJutifiFalta,
			Date dtFaltaFuncionario, Date dtCadastro) {
		this.idFaltaFuncionario = idFaltaFuncionario;
		this.funcionariosByIdFuncionarioFalta = funcionariosByIdFuncionarioFalta;
		this.funcionariosByIdFuncionarioCadastro = funcionariosByIdFuncionarioCadastro;
		this.dsFaltaFuncionario = dsFaltaFuncionario;
		this.dsJutifiFalta = dsJutifiFalta;
		this.dtFaltaFuncionario = dtFaltaFuncionario;
		this.dtCadastro = dtCadastro;
	}

	public long getIdFaltaFuncionario() {
		return this.idFaltaFuncionario;
	}

	public void setIdFaltaFuncionario(long idFaltaFuncionario) {
		this.idFaltaFuncionario = idFaltaFuncionario;
	}

	public Funcionarios getFuncionariosByIdFuncionarioFalta() {
		return this.funcionariosByIdFuncionarioFalta;
	}

	public void setFuncionariosByIdFuncionarioFalta(Funcionarios funcionariosByIdFuncionarioFalta) {
		this.funcionariosByIdFuncionarioFalta = funcionariosByIdFuncionarioFalta;
	}

	public Funcionarios getFuncionariosByIdFuncionarioCadastro() {
		return this.funcionariosByIdFuncionarioCadastro;
	}

	public void setFuncionariosByIdFuncionarioCadastro(Funcionarios funcionariosByIdFuncionarioCadastro) {
		this.funcionariosByIdFuncionarioCadastro = funcionariosByIdFuncionarioCadastro;
	}

	public String getDsFaltaFuncionario() {
		return this.dsFaltaFuncionario;
	}

	public void setDsFaltaFuncionario(String dsFaltaFuncionario) {
		this.dsFaltaFuncionario = dsFaltaFuncionario;
	}

	public String getDsJutifiFalta() {
		return this.dsJutifiFalta;
	}

	public void setDsJutifiFalta(String dsJutifiFalta) {
		this.dsJutifiFalta = dsJutifiFalta;
	}

	public Date getDtFaltaFuncionario() {
		return this.dtFaltaFuncionario;
	}

	public void setDtFaltaFuncionario(Date dtFaltaFuncionario) {
		this.dtFaltaFuncionario = dtFaltaFuncionario;
	}

	public Date getDtCadastro() {
		return this.dtCadastro;
	}

	public void setDtCadastro(Date dtCadastro) {
		this.dtCadastro = dtCadastro;
	}

}
