package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Familiares generated by hbm2java
 */
public class Familiares implements java.io.Serializable {

	private long idFamiliar;
	private PessoasFisicas pessoasFisicas;
	private Responsaveis responsaveis;
	private Date dtCadastro;
	private String dsGrauParentesco;
	private String stSituacaoParentesco;
	private String dsOutrasInformacoes;
	private Date dtDesligamento;
	private String dsDesligamento;
	private Set atendimentoses = new HashSet(0);
	private Set vulnerabilidadesFamiliars = new HashSet(0);

	public Familiares() {
	}

	public Familiares(long idFamiliar, PessoasFisicas pessoasFisicas, Responsaveis responsaveis, Date dtCadastro) {
		this.idFamiliar = idFamiliar;
		this.pessoasFisicas = pessoasFisicas;
		this.responsaveis = responsaveis;
		this.dtCadastro = dtCadastro;
	}

	public Familiares(long idFamiliar, PessoasFisicas pessoasFisicas, Responsaveis responsaveis, Date dtCadastro,
			String dsGrauParentesco, String stSituacaoParentesco, String dsOutrasInformacoes, Date dtDesligamento,
			String dsDesligamento, Set atendimentoses, Set vulnerabilidadesFamiliars) {
		this.idFamiliar = idFamiliar;
		this.pessoasFisicas = pessoasFisicas;
		this.responsaveis = responsaveis;
		this.dtCadastro = dtCadastro;
		this.dsGrauParentesco = dsGrauParentesco;
		this.stSituacaoParentesco = stSituacaoParentesco;
		this.dsOutrasInformacoes = dsOutrasInformacoes;
		this.dtDesligamento = dtDesligamento;
		this.dsDesligamento = dsDesligamento;
		this.atendimentoses = atendimentoses;
		this.vulnerabilidadesFamiliars = vulnerabilidadesFamiliars;
	}

	public long getIdFamiliar() {
		return this.idFamiliar;
	}

	public void setIdFamiliar(long idFamiliar) {
		this.idFamiliar = idFamiliar;
	}

	public PessoasFisicas getPessoasFisicas() {
		return this.pessoasFisicas;
	}

	public void setPessoasFisicas(PessoasFisicas pessoasFisicas) {
		this.pessoasFisicas = pessoasFisicas;
	}

	public Responsaveis getResponsaveis() {
		return this.responsaveis;
	}

	public void setResponsaveis(Responsaveis responsaveis) {
		this.responsaveis = responsaveis;
	}

	public Date getDtCadastro() {
		return this.dtCadastro;
	}

	public void setDtCadastro(Date dtCadastro) {
		this.dtCadastro = dtCadastro;
	}

	public String getDsGrauParentesco() {
		return this.dsGrauParentesco;
	}

	public void setDsGrauParentesco(String dsGrauParentesco) {
		this.dsGrauParentesco = dsGrauParentesco;
	}

	public String getStSituacaoParentesco() {
		return this.stSituacaoParentesco;
	}

	public void setStSituacaoParentesco(String stSituacaoParentesco) {
		this.stSituacaoParentesco = stSituacaoParentesco;
	}

	public String getDsOutrasInformacoes() {
		return this.dsOutrasInformacoes;
	}

	public void setDsOutrasInformacoes(String dsOutrasInformacoes) {
		this.dsOutrasInformacoes = dsOutrasInformacoes;
	}

	public Date getDtDesligamento() {
		return this.dtDesligamento;
	}

	public void setDtDesligamento(Date dtDesligamento) {
		this.dtDesligamento = dtDesligamento;
	}

	public String getDsDesligamento() {
		return this.dsDesligamento;
	}

	public void setDsDesligamento(String dsDesligamento) {
		this.dsDesligamento = dsDesligamento;
	}

	public Set getAtendimentoses() {
		return this.atendimentoses;
	}

	public void setAtendimentoses(Set atendimentoses) {
		this.atendimentoses = atendimentoses;
	}

	public Set getVulnerabilidadesFamiliars() {
		return this.vulnerabilidadesFamiliars;
	}

	public void setVulnerabilidadesFamiliars(Set vulnerabilidadesFamiliars) {
		this.vulnerabilidadesFamiliars = vulnerabilidadesFamiliars;
	}

}
