package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Faturas generated by hbm2java
 */
public class Faturas implements java.io.Serializable {

	private long idFatura;
	private Empresas empresas;
	private Unidades unidades;
	private String csTipoFatura;
	private Date dtFatura;
	private BigDecimal vlFatura;
	private String dsFatura;
	private String nrDocFatura;
	private BigDecimal qtParcelas;
	private Date dtDocFatura;
	private Set pagamentosFaturases = new HashSet(0);
	private Set itensFaturases = new HashSet(0);

	public Faturas() {
	}

	public Faturas(long idFatura, Unidades unidades) {
		this.idFatura = idFatura;
		this.unidades = unidades;
	}

	public Faturas(long idFatura, Empresas empresas, Unidades unidades, String csTipoFatura, Date dtFatura,
			BigDecimal vlFatura, String dsFatura, String nrDocFatura, BigDecimal qtParcelas, Date dtDocFatura,
			Set pagamentosFaturases, Set itensFaturases) {
		this.idFatura = idFatura;
		this.empresas = empresas;
		this.unidades = unidades;
		this.csTipoFatura = csTipoFatura;
		this.dtFatura = dtFatura;
		this.vlFatura = vlFatura;
		this.dsFatura = dsFatura;
		this.nrDocFatura = nrDocFatura;
		this.qtParcelas = qtParcelas;
		this.dtDocFatura = dtDocFatura;
		this.pagamentosFaturases = pagamentosFaturases;
		this.itensFaturases = itensFaturases;
	}

	public long getIdFatura() {
		return this.idFatura;
	}

	public void setIdFatura(long idFatura) {
		this.idFatura = idFatura;
	}

	public Empresas getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Empresas empresas) {
		this.empresas = empresas;
	}

	public Unidades getUnidades() {
		return this.unidades;
	}

	public void setUnidades(Unidades unidades) {
		this.unidades = unidades;
	}

	public String getCsTipoFatura() {
		return this.csTipoFatura;
	}

	public void setCsTipoFatura(String csTipoFatura) {
		this.csTipoFatura = csTipoFatura;
	}

	public Date getDtFatura() {
		return this.dtFatura;
	}

	public void setDtFatura(Date dtFatura) {
		this.dtFatura = dtFatura;
	}

	public BigDecimal getVlFatura() {
		return this.vlFatura;
	}

	public void setVlFatura(BigDecimal vlFatura) {
		this.vlFatura = vlFatura;
	}

	public String getDsFatura() {
		return this.dsFatura;
	}

	public void setDsFatura(String dsFatura) {
		this.dsFatura = dsFatura;
	}

	public String getNrDocFatura() {
		return this.nrDocFatura;
	}

	public void setNrDocFatura(String nrDocFatura) {
		this.nrDocFatura = nrDocFatura;
	}

	public BigDecimal getQtParcelas() {
		return this.qtParcelas;
	}

	public void setQtParcelas(BigDecimal qtParcelas) {
		this.qtParcelas = qtParcelas;
	}

	public Date getDtDocFatura() {
		return this.dtDocFatura;
	}

	public void setDtDocFatura(Date dtDocFatura) {
		this.dtDocFatura = dtDocFatura;
	}

	public Set getPagamentosFaturases() {
		return this.pagamentosFaturases;
	}

	public void setPagamentosFaturases(Set pagamentosFaturases) {
		this.pagamentosFaturases = pagamentosFaturases;
	}

	public Set getItensFaturases() {
		return this.itensFaturases;
	}

	public void setItensFaturases(Set itensFaturases) {
		this.itensFaturases = itensFaturases;
	}

}
