package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * FrequenciasAlunos generated by hbm2java
 */
public class FrequenciasAlunos implements java.io.Serializable {

	private long idFrequenciaAluno;
	private AtividadesAluno atividadesAluno;
	private Date dtFrequencia;
	private String dsJustificativa;

	public FrequenciasAlunos() {
	}

	public FrequenciasAlunos(long idFrequenciaAluno, AtividadesAluno atividadesAluno) {
		this.idFrequenciaAluno = idFrequenciaAluno;
		this.atividadesAluno = atividadesAluno;
	}

	public FrequenciasAlunos(long idFrequenciaAluno, AtividadesAluno atividadesAluno, Date dtFrequencia,
			String dsJustificativa) {
		this.idFrequenciaAluno = idFrequenciaAluno;
		this.atividadesAluno = atividadesAluno;
		this.dtFrequencia = dtFrequencia;
		this.dsJustificativa = dsJustificativa;
	}

	public long getIdFrequenciaAluno() {
		return this.idFrequenciaAluno;
	}

	public void setIdFrequenciaAluno(long idFrequenciaAluno) {
		this.idFrequenciaAluno = idFrequenciaAluno;
	}

	public AtividadesAluno getAtividadesAluno() {
		return this.atividadesAluno;
	}

	public void setAtividadesAluno(AtividadesAluno atividadesAluno) {
		this.atividadesAluno = atividadesAluno;
	}

	public Date getDtFrequencia() {
		return this.dtFrequencia;
	}

	public void setDtFrequencia(Date dtFrequencia) {
		this.dtFrequencia = dtFrequencia;
	}

	public String getDsJustificativa() {
		return this.dsJustificativa;
	}

	public void setDsJustificativa(String dsJustificativa) {
		this.dsJustificativa = dsJustificativa;
	}

}
