package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Funcionarios generated by hbm2java
 */
public class Funcionarios implements java.io.Serializable {

	private long idFuncionario;
	private Cargos cargos;
	private Empresas empresas;
	private Funcionarios funcionarios;
	private PessoasFisicas pessoasFisicas;
	private Unidades unidades;
	private String nrMatricula;
	private Date dtAdmissao;
	private Date dtDemissao;
	private String stTipoFuncionario;
	private BigDecimal vlSalarioPretendido;
	private Date dtHrEntrevista;
	private String stParecerEntrevistador;
	private String dsParecerEntrevistador;
	private String stConclusaoParecer;
	private Set colaboradoresProgramases = new HashSet(0);
	private Set faltasFuncionariosesForIdFuncionarioFalta = new HashSet(0);
	private Set colaboradoresProjetoses = new HashSet(0);
	private Set pedidosesForIdFuncionarioRecPed = new HashSet(0);
	private Set funcionarioses = new HashSet(0);
	private Set estoqueses = new HashSet(0);
	private Set talentosPfs = new HashSet(0);
	private Set colaboradoresAtividadeses = new HashSet(0);
	private Set faltasFuncionariosesForIdFuncionarioCadastro = new HashSet(0);
	private Set atendimentoses = new HashSet(0);
	private Set pedidosesForIdFuncionarioPedido = new HashSet(0);
	private Set movimentacoesContas = new HashSet(0);

	public Funcionarios() {
	}

	public Funcionarios(long idFuncionario, Cargos cargos, Empresas empresas, PessoasFisicas pessoasFisicas,
			Unidades unidades, String nrMatricula, Date dtAdmissao) {
		this.idFuncionario = idFuncionario;
		this.cargos = cargos;
		this.empresas = empresas;
		this.pessoasFisicas = pessoasFisicas;
		this.unidades = unidades;
		this.nrMatricula = nrMatricula;
		this.dtAdmissao = dtAdmissao;
	}

	public Funcionarios(long idFuncionario, Cargos cargos, Empresas empresas, Funcionarios funcionarios,
			PessoasFisicas pessoasFisicas, Unidades unidades, String nrMatricula, Date dtAdmissao, Date dtDemissao,
			String stTipoFuncionario, BigDecimal vlSalarioPretendido, Date dtHrEntrevista,
			String stParecerEntrevistador, String dsParecerEntrevistador, String stConclusaoParecer,
			Set colaboradoresProgramases, Set faltasFuncionariosesForIdFuncionarioFalta, Set colaboradoresProjetoses,
			Set pedidosesForIdFuncionarioRecPed, Set funcionarioses, Set estoqueses, Set talentosPfs,
			Set colaboradoresAtividadeses, Set faltasFuncionariosesForIdFuncionarioCadastro, Set atendimentoses,
			Set pedidosesForIdFuncionarioPedido, Set movimentacoesContas) {
		this.idFuncionario = idFuncionario;
		this.cargos = cargos;
		this.empresas = empresas;
		this.funcionarios = funcionarios;
		this.pessoasFisicas = pessoasFisicas;
		this.unidades = unidades;
		this.nrMatricula = nrMatricula;
		this.dtAdmissao = dtAdmissao;
		this.dtDemissao = dtDemissao;
		this.stTipoFuncionario = stTipoFuncionario;
		this.vlSalarioPretendido = vlSalarioPretendido;
		this.dtHrEntrevista = dtHrEntrevista;
		this.stParecerEntrevistador = stParecerEntrevistador;
		this.dsParecerEntrevistador = dsParecerEntrevistador;
		this.stConclusaoParecer = stConclusaoParecer;
		this.colaboradoresProgramases = colaboradoresProgramases;
		this.faltasFuncionariosesForIdFuncionarioFalta = faltasFuncionariosesForIdFuncionarioFalta;
		this.colaboradoresProjetoses = colaboradoresProjetoses;
		this.pedidosesForIdFuncionarioRecPed = pedidosesForIdFuncionarioRecPed;
		this.funcionarioses = funcionarioses;
		this.estoqueses = estoqueses;
		this.talentosPfs = talentosPfs;
		this.colaboradoresAtividadeses = colaboradoresAtividadeses;
		this.faltasFuncionariosesForIdFuncionarioCadastro = faltasFuncionariosesForIdFuncionarioCadastro;
		this.atendimentoses = atendimentoses;
		this.pedidosesForIdFuncionarioPedido = pedidosesForIdFuncionarioPedido;
		this.movimentacoesContas = movimentacoesContas;
	}

	public long getIdFuncionario() {
		return this.idFuncionario;
	}

	public void setIdFuncionario(long idFuncionario) {
		this.idFuncionario = idFuncionario;
	}

	public Cargos getCargos() {
		return this.cargos;
	}

	public void setCargos(Cargos cargos) {
		this.cargos = cargos;
	}

	public Empresas getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Empresas empresas) {
		this.empresas = empresas;
	}

	public Funcionarios getFuncionarios() {
		return this.funcionarios;
	}

	public void setFuncionarios(Funcionarios funcionarios) {
		this.funcionarios = funcionarios;
	}

	public PessoasFisicas getPessoasFisicas() {
		return this.pessoasFisicas;
	}

	public void setPessoasFisicas(PessoasFisicas pessoasFisicas) {
		this.pessoasFisicas = pessoasFisicas;
	}

	public Unidades getUnidades() {
		return this.unidades;
	}

	public void setUnidades(Unidades unidades) {
		this.unidades = unidades;
	}

	public String getNrMatricula() {
		return this.nrMatricula;
	}

	public void setNrMatricula(String nrMatricula) {
		this.nrMatricula = nrMatricula;
	}

	public Date getDtAdmissao() {
		return this.dtAdmissao;
	}

	public void setDtAdmissao(Date dtAdmissao) {
		this.dtAdmissao = dtAdmissao;
	}

	public Date getDtDemissao() {
		return this.dtDemissao;
	}

	public void setDtDemissao(Date dtDemissao) {
		this.dtDemissao = dtDemissao;
	}

	public String getStTipoFuncionario() {
		return this.stTipoFuncionario;
	}

	public void setStTipoFuncionario(String stTipoFuncionario) {
		this.stTipoFuncionario = stTipoFuncionario;
	}

	public BigDecimal getVlSalarioPretendido() {
		return this.vlSalarioPretendido;
	}

	public void setVlSalarioPretendido(BigDecimal vlSalarioPretendido) {
		this.vlSalarioPretendido = vlSalarioPretendido;
	}

	public Date getDtHrEntrevista() {
		return this.dtHrEntrevista;
	}

	public void setDtHrEntrevista(Date dtHrEntrevista) {
		this.dtHrEntrevista = dtHrEntrevista;
	}

	public String getStParecerEntrevistador() {
		return this.stParecerEntrevistador;
	}

	public void setStParecerEntrevistador(String stParecerEntrevistador) {
		this.stParecerEntrevistador = stParecerEntrevistador;
	}

	public String getDsParecerEntrevistador() {
		return this.dsParecerEntrevistador;
	}

	public void setDsParecerEntrevistador(String dsParecerEntrevistador) {
		this.dsParecerEntrevistador = dsParecerEntrevistador;
	}

	public String getStConclusaoParecer() {
		return this.stConclusaoParecer;
	}

	public void setStConclusaoParecer(String stConclusaoParecer) {
		this.stConclusaoParecer = stConclusaoParecer;
	}

	public Set getColaboradoresProgramases() {
		return this.colaboradoresProgramases;
	}

	public void setColaboradoresProgramases(Set colaboradoresProgramases) {
		this.colaboradoresProgramases = colaboradoresProgramases;
	}

	public Set getFaltasFuncionariosesForIdFuncionarioFalta() {
		return this.faltasFuncionariosesForIdFuncionarioFalta;
	}

	public void setFaltasFuncionariosesForIdFuncionarioFalta(Set faltasFuncionariosesForIdFuncionarioFalta) {
		this.faltasFuncionariosesForIdFuncionarioFalta = faltasFuncionariosesForIdFuncionarioFalta;
	}

	public Set getColaboradoresProjetoses() {
		return this.colaboradoresProjetoses;
	}

	public void setColaboradoresProjetoses(Set colaboradoresProjetoses) {
		this.colaboradoresProjetoses = colaboradoresProjetoses;
	}

	public Set getPedidosesForIdFuncionarioRecPed() {
		return this.pedidosesForIdFuncionarioRecPed;
	}

	public void setPedidosesForIdFuncionarioRecPed(Set pedidosesForIdFuncionarioRecPed) {
		this.pedidosesForIdFuncionarioRecPed = pedidosesForIdFuncionarioRecPed;
	}

	public Set getFuncionarioses() {
		return this.funcionarioses;
	}

	public void setFuncionarioses(Set funcionarioses) {
		this.funcionarioses = funcionarioses;
	}

	public Set getEstoqueses() {
		return this.estoqueses;
	}

	public void setEstoqueses(Set estoqueses) {
		this.estoqueses = estoqueses;
	}

	public Set getTalentosPfs() {
		return this.talentosPfs;
	}

	public void setTalentosPfs(Set talentosPfs) {
		this.talentosPfs = talentosPfs;
	}

	public Set getColaboradoresAtividadeses() {
		return this.colaboradoresAtividadeses;
	}

	public void setColaboradoresAtividadeses(Set colaboradoresAtividadeses) {
		this.colaboradoresAtividadeses = colaboradoresAtividadeses;
	}

	public Set getFaltasFuncionariosesForIdFuncionarioCadastro() {
		return this.faltasFuncionariosesForIdFuncionarioCadastro;
	}

	public void setFaltasFuncionariosesForIdFuncionarioCadastro(Set faltasFuncionariosesForIdFuncionarioCadastro) {
		this.faltasFuncionariosesForIdFuncionarioCadastro = faltasFuncionariosesForIdFuncionarioCadastro;
	}

	public Set getAtendimentoses() {
		return this.atendimentoses;
	}

	public void setAtendimentoses(Set atendimentoses) {
		this.atendimentoses = atendimentoses;
	}

	public Set getPedidosesForIdFuncionarioPedido() {
		return this.pedidosesForIdFuncionarioPedido;
	}

	public void setPedidosesForIdFuncionarioPedido(Set pedidosesForIdFuncionarioPedido) {
		this.pedidosesForIdFuncionarioPedido = pedidosesForIdFuncionarioPedido;
	}

	public Set getMovimentacoesContas() {
		return this.movimentacoesContas;
	}

	public void setMovimentacoesContas(Set movimentacoesContas) {
		this.movimentacoesContas = movimentacoesContas;
	}

}
