package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * GrausInstrucao generated by hbm2java
 */
public class GrausInstrucao implements java.io.Serializable {

	private long idGrauInstrucao;
	private String dsGrauInstrucao;
	private Set pessoasFisicases = new HashSet(0);

	public GrausInstrucao() {
	}

	public GrausInstrucao(long idGrauInstrucao, String dsGrauInstrucao) {
		this.idGrauInstrucao = idGrauInstrucao;
		this.dsGrauInstrucao = dsGrauInstrucao;
	}

	public GrausInstrucao(long idGrauInstrucao, String dsGrauInstrucao, Set pessoasFisicases) {
		this.idGrauInstrucao = idGrauInstrucao;
		this.dsGrauInstrucao = dsGrauInstrucao;
		this.pessoasFisicases = pessoasFisicases;
	}

	public long getIdGrauInstrucao() {
		return this.idGrauInstrucao;
	}

	public void setIdGrauInstrucao(long idGrauInstrucao) {
		this.idGrauInstrucao = idGrauInstrucao;
	}

	public String getDsGrauInstrucao() {
		return this.dsGrauInstrucao;
	}

	public void setDsGrauInstrucao(String dsGrauInstrucao) {
		this.dsGrauInstrucao = dsGrauInstrucao;
	}

	public Set getPessoasFisicases() {
		return this.pessoasFisicases;
	}

	public void setPessoasFisicases(Set pessoasFisicases) {
		this.pessoasFisicases = pessoasFisicases;
	}

}
