package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * GruposModulos generated by hbm2java
 */
public class GruposModulos implements java.io.Serializable {

	private long idGrupoModulo;
	private Modulos modulos;
	private PerfisAcesso perfisAcesso;
	private String nmGrupoModulo;
	private String txGrupoModulo;
	private Set usuariosGrupos = new HashSet(0);

	public GruposModulos() {
	}

	public GruposModulos(long idGrupoModulo) {
		this.idGrupoModulo = idGrupoModulo;
	}

	public GruposModulos(long idGrupoModulo, Modulos modulos, PerfisAcesso perfisAcesso, String nmGrupoModulo,
			String txGrupoModulo, Set usuariosGrupos) {
		this.idGrupoModulo = idGrupoModulo;
		this.modulos = modulos;
		this.perfisAcesso = perfisAcesso;
		this.nmGrupoModulo = nmGrupoModulo;
		this.txGrupoModulo = txGrupoModulo;
		this.usuariosGrupos = usuariosGrupos;
	}

	public long getIdGrupoModulo() {
		return this.idGrupoModulo;
	}

	public void setIdGrupoModulo(long idGrupoModulo) {
		this.idGrupoModulo = idGrupoModulo;
	}

	public Modulos getModulos() {
		return this.modulos;
	}

	public void setModulos(Modulos modulos) {
		this.modulos = modulos;
	}

	public PerfisAcesso getPerfisAcesso() {
		return this.perfisAcesso;
	}

	public void setPerfisAcesso(PerfisAcesso perfisAcesso) {
		this.perfisAcesso = perfisAcesso;
	}

	public String getNmGrupoModulo() {
		return this.nmGrupoModulo;
	}

	public void setNmGrupoModulo(String nmGrupoModulo) {
		this.nmGrupoModulo = nmGrupoModulo;
	}

	public String getTxGrupoModulo() {
		return this.txGrupoModulo;
	}

	public void setTxGrupoModulo(String txGrupoModulo) {
		this.txGrupoModulo = txGrupoModulo;
	}

	public Set getUsuariosGrupos() {
		return this.usuariosGrupos;
	}

	public void setUsuariosGrupos(Set usuariosGrupos) {
		this.usuariosGrupos = usuariosGrupos;
	}

}
