package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

/**
 * GruposModulos generated by hbm2java
 */
public class GruposModulos {

	private Long idGrupoModulo;
	private Modulos modulos;
	private PerfisAcesso perfisAcesso;
	private String nmGrupoModulo;

	public GruposModulos() {
	}

	public long getIdGrupoModulo() {
		return this.idGrupoModulo;
	}

	public void setIdGrupoModulo(long idGrupoModulo) {
		this.idGrupoModulo = idGrupoModulo;
	}

	public Modulos getModulos() {
		return this.modulos;
	}

	public void setModulos(Modulos modulos) {
		this.modulos = modulos;
	}

	public PerfisAcesso getPerfisAcesso() {
		return this.perfisAcesso;
	}

	public void setPerfisAcesso(PerfisAcesso perfisAcesso) {
		this.perfisAcesso = perfisAcesso;
	}

	public String getNmGrupoModulo() {
		return this.nmGrupoModulo;
	}

	public void setNmGrupoModulo(String nmGrupoModulo) {
		this.nmGrupoModulo = nmGrupoModulo;
	}

}
