package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Indicadores generated by hbm2java
 */
public class Indicadores implements java.io.Serializable {

	private long idIndicador;
	private Objetivos objetivos;
	private String nmIndicador;
	private Date dtInicioIndicador;
	private Date dtFimIndicador;
	private Set metases = new HashSet(0);
	private Set causasEfeitoses = new HashSet(0);

	public Indicadores() {
	}

	public Indicadores(long idIndicador, Objetivos objetivos, String nmIndicador, Date dtInicioIndicador) {
		this.idIndicador = idIndicador;
		this.objetivos = objetivos;
		this.nmIndicador = nmIndicador;
		this.dtInicioIndicador = dtInicioIndicador;
	}

	public Indicadores(long idIndicador, Objetivos objetivos, String nmIndicador, Date dtInicioIndicador,
			Date dtFimIndicador, Set metases, Set causasEfeitoses) {
		this.idIndicador = idIndicador;
		this.objetivos = objetivos;
		this.nmIndicador = nmIndicador;
		this.dtInicioIndicador = dtInicioIndicador;
		this.dtFimIndicador = dtFimIndicador;
		this.metases = metases;
		this.causasEfeitoses = causasEfeitoses;
	}

	public long getIdIndicador() {
		return this.idIndicador;
	}

	public void setIdIndicador(long idIndicador) {
		this.idIndicador = idIndicador;
	}

	public Objetivos getObjetivos() {
		return this.objetivos;
	}

	public void setObjetivos(Objetivos objetivos) {
		this.objetivos = objetivos;
	}

	public String getNmIndicador() {
		return this.nmIndicador;
	}

	public void setNmIndicador(String nmIndicador) {
		this.nmIndicador = nmIndicador;
	}

	public Date getDtInicioIndicador() {
		return this.dtInicioIndicador;
	}

	public void setDtInicioIndicador(Date dtInicioIndicador) {
		this.dtInicioIndicador = dtInicioIndicador;
	}

	public Date getDtFimIndicador() {
		return this.dtFimIndicador;
	}

	public void setDtFimIndicador(Date dtFimIndicador) {
		this.dtFimIndicador = dtFimIndicador;
	}

	public Set getMetases() {
		return this.metases;
	}

	public void setMetases(Set metases) {
		this.metases = metases;
	}

	public Set getCausasEfeitoses() {
		return this.causasEfeitoses;
	}

	public void setCausasEfeitoses(Set causasEfeitoses) {
		this.causasEfeitoses = causasEfeitoses;
	}

}
