package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Iniciativas generated by hbm2java
 */
public class Iniciativas implements java.io.Serializable {

	private long idIniciativa;
	private Metas metas;
	private String dsIniciativa;
	private Date dtInicioIniciativa;
	private Date dtFimIniciativa;
	private Set projetoses = new HashSet(0);
	private Set planosAcaos = new HashSet(0);
	private Set programases = new HashSet(0);

	public Iniciativas() {
	}

	public Iniciativas(long idIniciativa, Metas metas, String dsIniciativa, Date dtInicioIniciativa) {
		this.idIniciativa = idIniciativa;
		this.metas = metas;
		this.dsIniciativa = dsIniciativa;
		this.dtInicioIniciativa = dtInicioIniciativa;
	}

	public Iniciativas(long idIniciativa, Metas metas, String dsIniciativa, Date dtInicioIniciativa,
			Date dtFimIniciativa, Set projetoses, Set planosAcaos, Set programases) {
		this.idIniciativa = idIniciativa;
		this.metas = metas;
		this.dsIniciativa = dsIniciativa;
		this.dtInicioIniciativa = dtInicioIniciativa;
		this.dtFimIniciativa = dtFimIniciativa;
		this.projetoses = projetoses;
		this.planosAcaos = planosAcaos;
		this.programases = programases;
	}

	public long getIdIniciativa() {
		return this.idIniciativa;
	}

	public void setIdIniciativa(long idIniciativa) {
		this.idIniciativa = idIniciativa;
	}

	public Metas getMetas() {
		return this.metas;
	}

	public void setMetas(Metas metas) {
		this.metas = metas;
	}

	public String getDsIniciativa() {
		return this.dsIniciativa;
	}

	public void setDsIniciativa(String dsIniciativa) {
		this.dsIniciativa = dsIniciativa;
	}

	public Date getDtInicioIniciativa() {
		return this.dtInicioIniciativa;
	}

	public void setDtInicioIniciativa(Date dtInicioIniciativa) {
		this.dtInicioIniciativa = dtInicioIniciativa;
	}

	public Date getDtFimIniciativa() {
		return this.dtFimIniciativa;
	}

	public void setDtFimIniciativa(Date dtFimIniciativa) {
		this.dtFimIniciativa = dtFimIniciativa;
	}

	public Set getProjetoses() {
		return this.projetoses;
	}

	public void setProjetoses(Set projetoses) {
		this.projetoses = projetoses;
	}

	public Set getPlanosAcaos() {
		return this.planosAcaos;
	}

	public void setPlanosAcaos(Set planosAcaos) {
		this.planosAcaos = planosAcaos;
	}

	public Set getProgramases() {
		return this.programases;
	}

	public void setProgramases(Set programases) {
		this.programases = programases;
	}

}
