package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;

/**
 * ItensFaturas generated by hbm2java
 */
public class ItensFaturas implements java.io.Serializable {

	private long idItemFatura;
	private CentrosCusto centrosCusto;
	private Faturas faturas;
	private Pedidos pedidos;
	private Produtos produtos;
	private Servicos servicos;
	private BigDecimal vlItemFatura;
	private String dsItemFatura;
	private BigDecimal qtItemFatura;

	public ItensFaturas() {
	}

	public ItensFaturas(long idItemFatura, CentrosCusto centrosCusto, Faturas faturas) {
		this.idItemFatura = idItemFatura;
		this.centrosCusto = centrosCusto;
		this.faturas = faturas;
	}

	public ItensFaturas(long idItemFatura, CentrosCusto centrosCusto, Faturas faturas, Pedidos pedidos,
			Produtos produtos, Servicos servicos, BigDecimal vlItemFatura, String dsItemFatura,
			BigDecimal qtItemFatura) {
		this.idItemFatura = idItemFatura;
		this.centrosCusto = centrosCusto;
		this.faturas = faturas;
		this.pedidos = pedidos;
		this.produtos = produtos;
		this.servicos = servicos;
		this.vlItemFatura = vlItemFatura;
		this.dsItemFatura = dsItemFatura;
		this.qtItemFatura = qtItemFatura;
	}

	public long getIdItemFatura() {
		return this.idItemFatura;
	}

	public void setIdItemFatura(long idItemFatura) {
		this.idItemFatura = idItemFatura;
	}

	public CentrosCusto getCentrosCusto() {
		return this.centrosCusto;
	}

	public void setCentrosCusto(CentrosCusto centrosCusto) {
		this.centrosCusto = centrosCusto;
	}

	public Faturas getFaturas() {
		return this.faturas;
	}

	public void setFaturas(Faturas faturas) {
		this.faturas = faturas;
	}

	public Pedidos getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Pedidos pedidos) {
		this.pedidos = pedidos;
	}

	public Produtos getProdutos() {
		return this.produtos;
	}

	public void setProdutos(Produtos produtos) {
		this.produtos = produtos;
	}

	public Servicos getServicos() {
		return this.servicos;
	}

	public void setServicos(Servicos servicos) {
		this.servicos = servicos;
	}

	public BigDecimal getVlItemFatura() {
		return this.vlItemFatura;
	}

	public void setVlItemFatura(BigDecimal vlItemFatura) {
		this.vlItemFatura = vlItemFatura;
	}

	public String getDsItemFatura() {
		return this.dsItemFatura;
	}

	public void setDsItemFatura(String dsItemFatura) {
		this.dsItemFatura = dsItemFatura;
	}

	public BigDecimal getQtItemFatura() {
		return this.qtItemFatura;
	}

	public void setQtItemFatura(BigDecimal qtItemFatura) {
		this.qtItemFatura = qtItemFatura;
	}

}
