package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Metas generated by hbm2java
 */
public class Metas implements java.io.Serializable {

	private long idMeta;
	private Indicadores indicadores;
	private String dsMeta;
	private Date dtInicioMeta;
	private Date dtFimMeta;
	private Set iniciativases = new HashSet(0);

	public Metas() {
	}

	public Metas(long idMeta, Indicadores indicadores, String dsMeta) {
		this.idMeta = idMeta;
		this.indicadores = indicadores;
		this.dsMeta = dsMeta;
	}

	public Metas(long idMeta, Indicadores indicadores, String dsMeta, Date dtInicioMeta, Date dtFimMeta,
			Set iniciativases) {
		this.idMeta = idMeta;
		this.indicadores = indicadores;
		this.dsMeta = dsMeta;
		this.dtInicioMeta = dtInicioMeta;
		this.dtFimMeta = dtFimMeta;
		this.iniciativases = iniciativases;
	}

	public long getIdMeta() {
		return this.idMeta;
	}

	public void setIdMeta(long idMeta) {
		this.idMeta = idMeta;
	}

	public Indicadores getIndicadores() {
		return this.indicadores;
	}

	public void setIndicadores(Indicadores indicadores) {
		this.indicadores = indicadores;
	}

	public String getDsMeta() {
		return this.dsMeta;
	}

	public void setDsMeta(String dsMeta) {
		this.dsMeta = dsMeta;
	}

	public Date getDtInicioMeta() {
		return this.dtInicioMeta;
	}

	public void setDtInicioMeta(Date dtInicioMeta) {
		this.dtInicioMeta = dtInicioMeta;
	}

	public Date getDtFimMeta() {
		return this.dtFimMeta;
	}

	public void setDtFimMeta(Date dtFimMeta) {
		this.dtFimMeta = dtFimMeta;
	}

	public Set getIniciativases() {
		return this.iniciativases;
	}

	public void setIniciativases(Set iniciativases) {
		this.iniciativases = iniciativases;
	}

}
