package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Modulos generated by hbm2java
 */
public class Modulos implements java.io.Serializable {

	private long idModulo;
	private String nmModulo;
	private Set perfisUsuarioses = new HashSet(0);
	private Set gruposModuloses = new HashSet(0);

	public Modulos() {
	}

	public Modulos(long idModulo) {
		this.idModulo = idModulo;
	}

	public Modulos(long idModulo, String nmModulo, Set perfisUsuarioses, Set gruposModuloses) {
		this.idModulo = idModulo;
		this.nmModulo = nmModulo;
		this.perfisUsuarioses = perfisUsuarioses;
		this.gruposModuloses = gruposModuloses;
	}

	public long getIdModulo() {
		return this.idModulo;
	}

	public void setIdModulo(long idModulo) {
		this.idModulo = idModulo;
	}

	public String getNmModulo() {
		return this.nmModulo;
	}

	public void setNmModulo(String nmModulo) {
		this.nmModulo = nmModulo;
	}

	public Set getPerfisUsuarioses() {
		return this.perfisUsuarioses;
	}

	public void setPerfisUsuarioses(Set perfisUsuarioses) {
		this.perfisUsuarioses = perfisUsuarioses;
	}

	public Set getGruposModuloses() {
		return this.gruposModuloses;
	}

	public void setGruposModuloses(Set gruposModuloses) {
		this.gruposModuloses = gruposModuloses;
	}

}
