package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

/**
 * Modulos generated by hbm2java
 */
public class Modulos {

	private Long idModulo;
	private String nmModulo;

	public Modulos() {
	}

	public Long getIdModulo() {
		return this.idModulo;
	}

	public void setIdModulo(Long idModulo) {
		this.idModulo = idModulo;
	}

	public String getNmModulo() {
		return this.nmModulo;
	}

}
