package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;

/**
 * MovimentacoesConta generated by hbm2java
 */
public class MovimentacoesConta implements java.io.Serializable {

	private long idMovConta;
	private ContasBancarias contasBancarias;
	private Funcionarios funcionarios;
	private PagamentosFaturas pagamentosFaturas;
	private BigDecimal vlMovConta;
	private Date dtMovConta;
	private String csTipoMovConta;
	private String dsMovConta;
	private Date dtEfetMovConta;
	private BigDecimal vlSaldoMovConta;
	private Date dtSaldoMovConta;

	public MovimentacoesConta() {
	}

	public MovimentacoesConta(long idMovConta, ContasBancarias contasBancarias, Funcionarios funcionarios,
			PagamentosFaturas pagamentosFaturas) {
		this.idMovConta = idMovConta;
		this.contasBancarias = contasBancarias;
		this.funcionarios = funcionarios;
		this.pagamentosFaturas = pagamentosFaturas;
	}

	public MovimentacoesConta(long idMovConta, ContasBancarias contasBancarias, Funcionarios funcionarios,
			PagamentosFaturas pagamentosFaturas, BigDecimal vlMovConta, Date dtMovConta, String csTipoMovConta,
			String dsMovConta, Date dtEfetMovConta, BigDecimal vlSaldoMovConta, Date dtSaldoMovConta) {
		this.idMovConta = idMovConta;
		this.contasBancarias = contasBancarias;
		this.funcionarios = funcionarios;
		this.pagamentosFaturas = pagamentosFaturas;
		this.vlMovConta = vlMovConta;
		this.dtMovConta = dtMovConta;
		this.csTipoMovConta = csTipoMovConta;
		this.dsMovConta = dsMovConta;
		this.dtEfetMovConta = dtEfetMovConta;
		this.vlSaldoMovConta = vlSaldoMovConta;
		this.dtSaldoMovConta = dtSaldoMovConta;
	}

	public long getIdMovConta() {
		return this.idMovConta;
	}

	public void setIdMovConta(long idMovConta) {
		this.idMovConta = idMovConta;
	}

	public ContasBancarias getContasBancarias() {
		return this.contasBancarias;
	}

	public void setContasBancarias(ContasBancarias contasBancarias) {
		this.contasBancarias = contasBancarias;
	}

	public Funcionarios getFuncionarios() {
		return this.funcionarios;
	}

	public void setFuncionarios(Funcionarios funcionarios) {
		this.funcionarios = funcionarios;
	}

	public PagamentosFaturas getPagamentosFaturas() {
		return this.pagamentosFaturas;
	}

	public void setPagamentosFaturas(PagamentosFaturas pagamentosFaturas) {
		this.pagamentosFaturas = pagamentosFaturas;
	}

	public BigDecimal getVlMovConta() {
		return this.vlMovConta;
	}

	public void setVlMovConta(BigDecimal vlMovConta) {
		this.vlMovConta = vlMovConta;
	}

	public Date getDtMovConta() {
		return this.dtMovConta;
	}

	public void setDtMovConta(Date dtMovConta) {
		this.dtMovConta = dtMovConta;
	}

	public String getCsTipoMovConta() {
		return this.csTipoMovConta;
	}

	public void setCsTipoMovConta(String csTipoMovConta) {
		this.csTipoMovConta = csTipoMovConta;
	}

	public String getDsMovConta() {
		return this.dsMovConta;
	}

	public void setDsMovConta(String dsMovConta) {
		this.dsMovConta = dsMovConta;
	}

	public Date getDtEfetMovConta() {
		return this.dtEfetMovConta;
	}

	public void setDtEfetMovConta(Date dtEfetMovConta) {
		this.dtEfetMovConta = dtEfetMovConta;
	}

	public BigDecimal getVlSaldoMovConta() {
		return this.vlSaldoMovConta;
	}

	public void setVlSaldoMovConta(BigDecimal vlSaldoMovConta) {
		this.vlSaldoMovConta = vlSaldoMovConta;
	}

	public Date getDtSaldoMovConta() {
		return this.dtSaldoMovConta;
	}

	public void setDtSaldoMovConta(Date dtSaldoMovConta) {
		this.dtSaldoMovConta = dtSaldoMovConta;
	}

}
