package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Objetivos generated by hbm2java
 */
public class Objetivos implements java.io.Serializable {

	private long idObjetivo;
	private Perspectivas perspectivas;
	private String nmObjetivo;
	private Date dtImplantacao;
	private Date dtTermino;
	private Set indicadoreses = new HashSet(0);

	public Objetivos() {
	}

	public Objetivos(long idObjetivo, Perspectivas perspectivas, String nmObjetivo, Date dtImplantacao) {
		this.idObjetivo = idObjetivo;
		this.perspectivas = perspectivas;
		this.nmObjetivo = nmObjetivo;
		this.dtImplantacao = dtImplantacao;
	}

	public Objetivos(long idObjetivo, Perspectivas perspectivas, String nmObjetivo, Date dtImplantacao, Date dtTermino,
			Set indicadoreses) {
		this.idObjetivo = idObjetivo;
		this.perspectivas = perspectivas;
		this.nmObjetivo = nmObjetivo;
		this.dtImplantacao = dtImplantacao;
		this.dtTermino = dtTermino;
		this.indicadoreses = indicadoreses;
	}

	public long getIdObjetivo() {
		return this.idObjetivo;
	}

	public void setIdObjetivo(long idObjetivo) {
		this.idObjetivo = idObjetivo;
	}

	public Perspectivas getPerspectivas() {
		return this.perspectivas;
	}

	public void setPerspectivas(Perspectivas perspectivas) {
		this.perspectivas = perspectivas;
	}

	public String getNmObjetivo() {
		return this.nmObjetivo;
	}

	public void setNmObjetivo(String nmObjetivo) {
		this.nmObjetivo = nmObjetivo;
	}

	public Date getDtImplantacao() {
		return this.dtImplantacao;
	}

	public void setDtImplantacao(Date dtImplantacao) {
		this.dtImplantacao = dtImplantacao;
	}

	public Date getDtTermino() {
		return this.dtTermino;
	}

	public void setDtTermino(Date dtTermino) {
		this.dtTermino = dtTermino;
	}

	public Set getIndicadoreses() {
		return this.indicadoreses;
	}

	public void setIndicadoreses(Set indicadoreses) {
		this.indicadoreses = indicadoreses;
	}

}
