package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos implements java.io.Serializable {

	private long idPedido;
	private CentrosCusto centrosCusto;
	private Funcionarios funcionariosByIdFuncionarioRecPed;
	private Funcionarios funcionariosByIdFuncionarioPedido;
	private Produtos produtos;
	private Servicos servicos;
	private Unidades unidades;
	private Date dtPedido;
	private String dsPedido;
	private Date dtEntrega;
	private BigDecimal vlPedido;
	private BigDecimal qtdPedido;
	private Date dtEnvio;
	private Set itensFaturases = new HashSet(0);

	public Pedidos() {
	}

	public Pedidos(long idPedido, CentrosCusto centrosCusto, Funcionarios funcionariosByIdFuncionarioRecPed,
			Funcionarios funcionariosByIdFuncionarioPedido, Unidades unidades) {
		this.idPedido = idPedido;
		this.centrosCusto = centrosCusto;
		this.funcionariosByIdFuncionarioRecPed = funcionariosByIdFuncionarioRecPed;
		this.funcionariosByIdFuncionarioPedido = funcionariosByIdFuncionarioPedido;
		this.unidades = unidades;
	}

	public Pedidos(long idPedido, CentrosCusto centrosCusto, Funcionarios funcionariosByIdFuncionarioRecPed,
			Funcionarios funcionariosByIdFuncionarioPedido, Produtos produtos, Servicos servicos, Unidades unidades,
			Date dtPedido, String dsPedido, Date dtEntrega, BigDecimal vlPedido, BigDecimal qtdPedido, Date dtEnvio,
			Set itensFaturases) {
		this.idPedido = idPedido;
		this.centrosCusto = centrosCusto;
		this.funcionariosByIdFuncionarioRecPed = funcionariosByIdFuncionarioRecPed;
		this.funcionariosByIdFuncionarioPedido = funcionariosByIdFuncionarioPedido;
		this.produtos = produtos;
		this.servicos = servicos;
		this.unidades = unidades;
		this.dtPedido = dtPedido;
		this.dsPedido = dsPedido;
		this.dtEntrega = dtEntrega;
		this.vlPedido = vlPedido;
		this.qtdPedido = qtdPedido;
		this.dtEnvio = dtEnvio;
		this.itensFaturases = itensFaturases;
	}

	public long getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(long idPedido) {
		this.idPedido = idPedido;
	}

	public CentrosCusto getCentrosCusto() {
		return this.centrosCusto;
	}

	public void setCentrosCusto(CentrosCusto centrosCusto) {
		this.centrosCusto = centrosCusto;
	}

	public Funcionarios getFuncionariosByIdFuncionarioRecPed() {
		return this.funcionariosByIdFuncionarioRecPed;
	}

	public void setFuncionariosByIdFuncionarioRecPed(Funcionarios funcionariosByIdFuncionarioRecPed) {
		this.funcionariosByIdFuncionarioRecPed = funcionariosByIdFuncionarioRecPed;
	}

	public Funcionarios getFuncionariosByIdFuncionarioPedido() {
		return this.funcionariosByIdFuncionarioPedido;
	}

	public void setFuncionariosByIdFuncionarioPedido(Funcionarios funcionariosByIdFuncionarioPedido) {
		this.funcionariosByIdFuncionarioPedido = funcionariosByIdFuncionarioPedido;
	}

	public Produtos getProdutos() {
		return this.produtos;
	}

	public void setProdutos(Produtos produtos) {
		this.produtos = produtos;
	}

	public Servicos getServicos() {
		return this.servicos;
	}

	public void setServicos(Servicos servicos) {
		this.servicos = servicos;
	}

	public Unidades getUnidades() {
		return this.unidades;
	}

	public void setUnidades(Unidades unidades) {
		this.unidades = unidades;
	}

	public Date getDtPedido() {
		return this.dtPedido;
	}

	public void setDtPedido(Date dtPedido) {
		this.dtPedido = dtPedido;
	}

	public String getDsPedido() {
		return this.dsPedido;
	}

	public void setDsPedido(String dsPedido) {
		this.dsPedido = dsPedido;
	}

	public Date getDtEntrega() {
		return this.dtEntrega;
	}

	public void setDtEntrega(Date dtEntrega) {
		this.dtEntrega = dtEntrega;
	}

	public BigDecimal getVlPedido() {
		return this.vlPedido;
	}

	public void setVlPedido(BigDecimal vlPedido) {
		this.vlPedido = vlPedido;
	}

	public BigDecimal getQtdPedido() {
		return this.qtdPedido;
	}

	public void setQtdPedido(BigDecimal qtdPedido) {
		this.qtdPedido = qtdPedido;
	}

	public Date getDtEnvio() {
		return this.dtEnvio;
	}

	public void setDtEnvio(Date dtEnvio) {
		this.dtEnvio = dtEnvio;
	}

	public Set getItensFaturases() {
		return this.itensFaturases;
	}

	public void setItensFaturases(Set itensFaturases) {
		this.itensFaturases = itensFaturases;
	}

}
