package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * PerfisAcesso generated by hbm2java
 */
public class PerfisAcesso implements java.io.Serializable {

	private long idPerfilAcesso;
	private String nmPerfilAcesso;
	private String csPerfilConsulta;
	private String csPerfilAltera;
	private String csPerfilDeleta;
	private String csPerfilInsere;
	private Set perfisUsuarioses = new HashSet(0);
	private Set gruposModuloses = new HashSet(0);

	public PerfisAcesso() {
	}

	public PerfisAcesso(long idPerfilAcesso) {
		this.idPerfilAcesso = idPerfilAcesso;
	}

	public PerfisAcesso(long idPerfilAcesso, String nmPerfilAcesso, String csPerfilConsulta, String csPerfilAltera,
			String csPerfilDeleta, String csPerfilInsere, Set perfisUsuarioses, Set gruposModuloses) {
		this.idPerfilAcesso = idPerfilAcesso;
		this.nmPerfilAcesso = nmPerfilAcesso;
		this.csPerfilConsulta = csPerfilConsulta;
		this.csPerfilAltera = csPerfilAltera;
		this.csPerfilDeleta = csPerfilDeleta;
		this.csPerfilInsere = csPerfilInsere;
		this.perfisUsuarioses = perfisUsuarioses;
		this.gruposModuloses = gruposModuloses;
	}

	public long getIdPerfilAcesso() {
		return this.idPerfilAcesso;
	}

	public void setIdPerfilAcesso(long idPerfilAcesso) {
		this.idPerfilAcesso = idPerfilAcesso;
	}

	public String getNmPerfilAcesso() {
		return this.nmPerfilAcesso;
	}

	public void setNmPerfilAcesso(String nmPerfilAcesso) {
		this.nmPerfilAcesso = nmPerfilAcesso;
	}

	public String getCsPerfilConsulta() {
		return this.csPerfilConsulta;
	}

	public void setCsPerfilConsulta(String csPerfilConsulta) {
		this.csPerfilConsulta = csPerfilConsulta;
	}

	public String getCsPerfilAltera() {
		return this.csPerfilAltera;
	}

	public void setCsPerfilAltera(String csPerfilAltera) {
		this.csPerfilAltera = csPerfilAltera;
	}

	public String getCsPerfilDeleta() {
		return this.csPerfilDeleta;
	}

	public void setCsPerfilDeleta(String csPerfilDeleta) {
		this.csPerfilDeleta = csPerfilDeleta;
	}

	public String getCsPerfilInsere() {
		return this.csPerfilInsere;
	}

	public void setCsPerfilInsere(String csPerfilInsere) {
		this.csPerfilInsere = csPerfilInsere;
	}

	public Set getPerfisUsuarioses() {
		return this.perfisUsuarioses;
	}

	public void setPerfisUsuarioses(Set perfisUsuarioses) {
		this.perfisUsuarioses = perfisUsuarioses;
	}

	public Set getGruposModuloses() {
		return this.gruposModuloses;
	}

	public void setGruposModuloses(Set gruposModuloses) {
		this.gruposModuloses = gruposModuloses;
	}

}
