package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

/**
 * PerfisUsuarios generated by hbm2java
 */
public class PerfisUsuarios implements java.io.Serializable {

	private long idPerfilUsuario;
	private Modulos modulos;
	private PerfisAcesso perfisAcesso;
	private UsuariosSistema usuariosSistema;

	public PerfisUsuarios() {
	}

	public PerfisUsuarios(long idPerfilUsuario, Modulos modulos, PerfisAcesso perfisAcesso,
			UsuariosSistema usuariosSistema) {
		this.idPerfilUsuario = idPerfilUsuario;
		this.modulos = modulos;
		this.perfisAcesso = perfisAcesso;
		this.usuariosSistema = usuariosSistema;
	}

	public long getIdPerfilUsuario() {
		return this.idPerfilUsuario;
	}

	public void setIdPerfilUsuario(long idPerfilUsuario) {
		this.idPerfilUsuario = idPerfilUsuario;
	}

	public Modulos getModulos() {
		return this.modulos;
	}

	public void setModulos(Modulos modulos) {
		this.modulos = modulos;
	}

	public PerfisAcesso getPerfisAcesso() {
		return this.perfisAcesso;
	}

	public void setPerfisAcesso(PerfisAcesso perfisAcesso) {
		this.perfisAcesso = perfisAcesso;
	}

	public UsuariosSistema getUsuariosSistema() {
		return this.usuariosSistema;
	}

	public void setUsuariosSistema(UsuariosSistema usuariosSistema) {
		this.usuariosSistema = usuariosSistema;
	}

}
