package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

/**
 * PerfisAcesso generated by hbm2java
 */
public class PerfisAcesso {

	private long idPerfilAcesso;
	private String nmPerfilAcesso;
	private String csPerfilConsulta;
	private String csPerfilAltera;
	private String csPerfilDeleta;
	private String csPerfilInsere;

	public PerfisAcesso() {
	}

	public long getIdPerfilAcesso() {
		return this.idPerfilAcesso;
	}

	public void setIdPerfilAcesso(long idPerfilAcesso) {
		this.idPerfilAcesso = idPerfilAcesso;
	}

	public String getNmPerfilAcesso() {
		return this.nmPerfilAcesso;
	}

	public void setNmPerfilAcesso(String nmPerfilAcesso) {
		this.nmPerfilAcesso = nmPerfilAcesso;
	}

	public String getCsPerfilConsulta() {
		return this.csPerfilConsulta;
	}

	public void setCsPerfilConsulta(String csPerfilConsulta) {
		this.csPerfilConsulta = csPerfilConsulta;
	}

	public String getCsPerfilAltera() {
		return this.csPerfilAltera;
	}

	public void setCsPerfilAltera(String csPerfilAltera) {
		this.csPerfilAltera = csPerfilAltera;
	}

	public String getCsPerfilDeleta() {
		return this.csPerfilDeleta;
	}

	public void setCsPerfilDeleta(String csPerfilDeleta) {
		this.csPerfilDeleta = csPerfilDeleta;
	}

	public String getCsPerfilInsere() {
		return this.csPerfilInsere;
	}

	public void setCsPerfilInsere(String csPerfilInsere) {
		this.csPerfilInsere = csPerfilInsere;
	}

}
