package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Perspectivas generated by hbm2java
 */
public class Perspectivas implements java.io.Serializable {

	private long idPerspectiva;
	private Entidades entidades;
	private String nmPerspectiva;
	private Date dtImplantacao;
	private Date dtTermino;
	private Set objetivoses = new HashSet(0);

	public Perspectivas() {
	}

	public Perspectivas(long idPerspectiva, Entidades entidades, String nmPerspectiva, Date dtImplantacao) {
		this.idPerspectiva = idPerspectiva;
		this.entidades = entidades;
		this.nmPerspectiva = nmPerspectiva;
		this.dtImplantacao = dtImplantacao;
	}

	public Perspectivas(long idPerspectiva, Entidades entidades, String nmPerspectiva, Date dtImplantacao,
			Date dtTermino, Set objetivoses) {
		this.idPerspectiva = idPerspectiva;
		this.entidades = entidades;
		this.nmPerspectiva = nmPerspectiva;
		this.dtImplantacao = dtImplantacao;
		this.dtTermino = dtTermino;
		this.objetivoses = objetivoses;
	}

	public long getIdPerspectiva() {
		return this.idPerspectiva;
	}

	public void setIdPerspectiva(long idPerspectiva) {
		this.idPerspectiva = idPerspectiva;
	}

	public Entidades getEntidades() {
		return this.entidades;
	}

	public void setEntidades(Entidades entidades) {
		this.entidades = entidades;
	}

	public String getNmPerspectiva() {
		return this.nmPerspectiva;
	}

	public void setNmPerspectiva(String nmPerspectiva) {
		this.nmPerspectiva = nmPerspectiva;
	}

	public Date getDtImplantacao() {
		return this.dtImplantacao;
	}

	public void setDtImplantacao(Date dtImplantacao) {
		this.dtImplantacao = dtImplantacao;
	}

	public Date getDtTermino() {
		return this.dtTermino;
	}

	public void setDtTermino(Date dtTermino) {
		this.dtTermino = dtTermino;
	}

	public Set getObjetivoses() {
		return this.objetivoses;
	}

	public void setObjetivoses(Set objetivoses) {
		this.objetivoses = objetivoses;
	}

}
