package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PessoasFisicas generated by hbm2java
 */
public class PessoasFisicas implements java.io.Serializable {

	private long idPessoaFisica;
	private Arquivos arquivos;
	private CondicoesMoradia condicoesMoradia;
	private GrausInstrucao grausInstrucao;
	private String nmPessoaFisica;
	private String dsSexo;
	private long nrCpf;
	private String nrCi;
	private String cdOrgaoCi;
	private String sgUfCi;
	private String nmMae;
	private String nmPai;
	private Date dtNascimento;
	private String dsCidadeNaturalidade;
	private String sgUfNascimento;
	private String dsCor;
	private String dsEstadoCivil;
	private String dsEmail;
	private Integer nrCep;
	private String dsEndereco;
	private String dsBairro;
	private String sgUfEndereco;
	private String dsPontoReferencia;
	private String nrFoneCelular;
	private String nrTelefoneResidencial;
	private String nrTelefoneComercial;
	private String dsProfissao;
	private String nrCts;
	private String nrSerieCtps;
	private String nrTituloEleitor;
	private String nrZonaTitulo;
	private String nrSessaoTitulo;
	private String dsProblemaSaude;
	private String dsMedicamentosControlados;
	private String nmEmpresaTrabalho;
	private String stAutorizaEmail;
	private String dsAtendidoOrgaoRede;
	private String dsRedeApoioSocial;
	private String nrNis;
	private String stBenBolsaFamilia;
	private BigDecimal vlBolsaFamilia;
	private String dsOutrosBenSoc;
	private String vlOutrosBenerficiosSoc;
	private String dsAtendidoOrgaoRede1;
	private String stAtendidoOrgaoRede;
	private String dsRedeApoioSocial1;
	private String dsFormaIngressoEntidade;
	private String dsRedeApSocRelev;
	private String dsCondicaoMoradia;
	private BigDecimal vlAluguel;
	private BigDecimal vlRenda;
	private String dsSituacaoTrabalho;
	private String dsEscola;
	private String dsTurno;
	private String dsCursoEscola;
	private String dsPeriodoEscola;
	private String dsSerieEscola;
	private String dsTipoEscola;
	private String dsEscolaridade;
	private String dsNivelEscolaridade;
	private String dsRegiaoEscola;
	private String txObservacoes;
	private String csMotivoNaoTrab;
	private String dsMotivoNaoTrab;
	private Set alunoses = new HashSet(0);
	private Set cadastroReservaAtividadeses = new HashSet(0);
	private Set responsaveises = new HashSet(0);
	private Set talentosPfs = new HashSet(0);
	private Set familiareses = new HashSet(0);
	private Set contatosEmpresas = new HashSet(0);
	private Set usuariosSistemas = new HashSet(0);
	private Set funcionarioses = new HashSet(0);
	private Set cursosFormacaoPfs = new HashSet(0);

	public PessoasFisicas() {
	}

	public PessoasFisicas(long idPessoaFisica, CondicoesMoradia condicoesMoradia, GrausInstrucao grausInstrucao,
			String nmPessoaFisica, long nrCpf, String nrCi, String cdOrgaoCi, String sgUfCi, String nmMae,
			String dsEndereco, String nrFoneCelular, String nrTelefoneResidencial) {
		this.idPessoaFisica = idPessoaFisica;
		this.condicoesMoradia = condicoesMoradia;
		this.grausInstrucao = grausInstrucao;
		this.nmPessoaFisica = nmPessoaFisica;
		this.nrCpf = nrCpf;
		this.nrCi = nrCi;
		this.cdOrgaoCi = cdOrgaoCi;
		this.sgUfCi = sgUfCi;
		this.nmMae = nmMae;
		this.dsEndereco = dsEndereco;
		this.nrFoneCelular = nrFoneCelular;
		this.nrTelefoneResidencial = nrTelefoneResidencial;
	}

	public PessoasFisicas(long idPessoaFisica, Arquivos arquivos, CondicoesMoradia condicoesMoradia,
			GrausInstrucao grausInstrucao, String nmPessoaFisica, String dsSexo, long nrCpf, String nrCi,
			String cdOrgaoCi, String sgUfCi, String nmMae, String nmPai, Date dtNascimento, String dsCidadeNaturalidade,
			String sgUfNascimento, String dsCor, String dsEstadoCivil, String dsEmail, Integer nrCep, String dsEndereco,
			String dsBairro, String sgUfEndereco, String dsPontoReferencia, String nrFoneCelular,
			String nrTelefoneResidencial, String nrTelefoneComercial, String dsProfissao, String nrCts,
			String nrSerieCtps, String nrTituloEleitor, String nrZonaTitulo, String nrSessaoTitulo,
			String dsProblemaSaude, String dsMedicamentosControlados, String nmEmpresaTrabalho, String stAutorizaEmail,
			String dsAtendidoOrgaoRede, String dsRedeApoioSocial, String nrNis, String stBenBolsaFamilia,
			BigDecimal vlBolsaFamilia, String dsOutrosBenSoc, String vlOutrosBenerficiosSoc,
			String dsAtendidoOrgaoRede1, String stAtendidoOrgaoRede, String dsRedeApoioSocial1,
			String dsFormaIngressoEntidade, String dsRedeApSocRelev, String dsCondicaoMoradia, BigDecimal vlAluguel,
			BigDecimal vlRenda, String dsSituacaoTrabalho, String dsEscola, String dsTurno, String dsCursoEscola,
			String dsPeriodoEscola, String dsSerieEscola, String dsTipoEscola, String dsEscolaridade,
			String dsNivelEscolaridade, String dsRegiaoEscola, String txObservacoes, String csMotivoNaoTrab,
			String dsMotivoNaoTrab, Set alunoses, Set cadastroReservaAtividadeses, Set responsaveises, Set talentosPfs,
			Set familiareses, Set contatosEmpresas, Set usuariosSistemas, Set funcionarioses, Set cursosFormacaoPfs) {
		this.idPessoaFisica = idPessoaFisica;
		this.arquivos = arquivos;
		this.condicoesMoradia = condicoesMoradia;
		this.grausInstrucao = grausInstrucao;
		this.nmPessoaFisica = nmPessoaFisica;
		this.dsSexo = dsSexo;
		this.nrCpf = nrCpf;
		this.nrCi = nrCi;
		this.cdOrgaoCi = cdOrgaoCi;
		this.sgUfCi = sgUfCi;
		this.nmMae = nmMae;
		this.nmPai = nmPai;
		this.dtNascimento = dtNascimento;
		this.dsCidadeNaturalidade = dsCidadeNaturalidade;
		this.sgUfNascimento = sgUfNascimento;
		this.dsCor = dsCor;
		this.dsEstadoCivil = dsEstadoCivil;
		this.dsEmail = dsEmail;
		this.nrCep = nrCep;
		this.dsEndereco = dsEndereco;
		this.dsBairro = dsBairro;
		this.sgUfEndereco = sgUfEndereco;
		this.dsPontoReferencia = dsPontoReferencia;
		this.nrFoneCelular = nrFoneCelular;
		this.nrTelefoneResidencial = nrTelefoneResidencial;
		this.nrTelefoneComercial = nrTelefoneComercial;
		this.dsProfissao = dsProfissao;
		this.nrCts = nrCts;
		this.nrSerieCtps = nrSerieCtps;
		this.nrTituloEleitor = nrTituloEleitor;
		this.nrZonaTitulo = nrZonaTitulo;
		this.nrSessaoTitulo = nrSessaoTitulo;
		this.dsProblemaSaude = dsProblemaSaude;
		this.dsMedicamentosControlados = dsMedicamentosControlados;
		this.nmEmpresaTrabalho = nmEmpresaTrabalho;
		this.stAutorizaEmail = stAutorizaEmail;
		this.dsAtendidoOrgaoRede = dsAtendidoOrgaoRede;
		this.dsRedeApoioSocial = dsRedeApoioSocial;
		this.nrNis = nrNis;
		this.stBenBolsaFamilia = stBenBolsaFamilia;
		this.vlBolsaFamilia = vlBolsaFamilia;
		this.dsOutrosBenSoc = dsOutrosBenSoc;
		this.vlOutrosBenerficiosSoc = vlOutrosBenerficiosSoc;
		this.dsAtendidoOrgaoRede1 = dsAtendidoOrgaoRede1;
		this.stAtendidoOrgaoRede = stAtendidoOrgaoRede;
		this.dsRedeApoioSocial1 = dsRedeApoioSocial1;
		this.dsFormaIngressoEntidade = dsFormaIngressoEntidade;
		this.dsRedeApSocRelev = dsRedeApSocRelev;
		this.dsCondicaoMoradia = dsCondicaoMoradia;
		this.vlAluguel = vlAluguel;
		this.vlRenda = vlRenda;
		this.dsSituacaoTrabalho = dsSituacaoTrabalho;
		this.dsEscola = dsEscola;
		this.dsTurno = dsTurno;
		this.dsCursoEscola = dsCursoEscola;
		this.dsPeriodoEscola = dsPeriodoEscola;
		this.dsSerieEscola = dsSerieEscola;
		this.dsTipoEscola = dsTipoEscola;
		this.dsEscolaridade = dsEscolaridade;
		this.dsNivelEscolaridade = dsNivelEscolaridade;
		this.dsRegiaoEscola = dsRegiaoEscola;
		this.txObservacoes = txObservacoes;
		this.csMotivoNaoTrab = csMotivoNaoTrab;
		this.dsMotivoNaoTrab = dsMotivoNaoTrab;
		this.alunoses = alunoses;
		this.cadastroReservaAtividadeses = cadastroReservaAtividadeses;
		this.responsaveises = responsaveises;
		this.talentosPfs = talentosPfs;
		this.familiareses = familiareses;
		this.contatosEmpresas = contatosEmpresas;
		this.usuariosSistemas = usuariosSistemas;
		this.funcionarioses = funcionarioses;
		this.cursosFormacaoPfs = cursosFormacaoPfs;
	}

	public long getIdPessoaFisica() {
		return this.idPessoaFisica;
	}

	public void setIdPessoaFisica(long idPessoaFisica) {
		this.idPessoaFisica = idPessoaFisica;
	}

	public Arquivos getArquivos() {
		return this.arquivos;
	}

	public void setArquivos(Arquivos arquivos) {
		this.arquivos = arquivos;
	}

	public CondicoesMoradia getCondicoesMoradia() {
		return this.condicoesMoradia;
	}

	public void setCondicoesMoradia(CondicoesMoradia condicoesMoradia) {
		this.condicoesMoradia = condicoesMoradia;
	}

	public GrausInstrucao getGrausInstrucao() {
		return this.grausInstrucao;
	}

	public void setGrausInstrucao(GrausInstrucao grausInstrucao) {
		this.grausInstrucao = grausInstrucao;
	}

	public String getNmPessoaFisica() {
		return this.nmPessoaFisica;
	}

	public void setNmPessoaFisica(String nmPessoaFisica) {
		this.nmPessoaFisica = nmPessoaFisica;
	}

	public String getDsSexo() {
		return this.dsSexo;
	}

	public void setDsSexo(String dsSexo) {
		this.dsSexo = dsSexo;
	}

	public long getNrCpf() {
		return this.nrCpf;
	}

	public void setNrCpf(long nrCpf) {
		this.nrCpf = nrCpf;
	}

	public String getNrCi() {
		return this.nrCi;
	}

	public void setNrCi(String nrCi) {
		this.nrCi = nrCi;
	}

	public String getCdOrgaoCi() {
		return this.cdOrgaoCi;
	}

	public void setCdOrgaoCi(String cdOrgaoCi) {
		this.cdOrgaoCi = cdOrgaoCi;
	}

	public String getSgUfCi() {
		return this.sgUfCi;
	}

	public void setSgUfCi(String sgUfCi) {
		this.sgUfCi = sgUfCi;
	}

	public String getNmMae() {
		return this.nmMae;
	}

	public void setNmMae(String nmMae) {
		this.nmMae = nmMae;
	}

	public String getNmPai() {
		return this.nmPai;
	}

	public void setNmPai(String nmPai) {
		this.nmPai = nmPai;
	}

	public Date getDtNascimento() {
		return this.dtNascimento;
	}

	public void setDtNascimento(Date dtNascimento) {
		this.dtNascimento = dtNascimento;
	}

	public String getDsCidadeNaturalidade() {
		return this.dsCidadeNaturalidade;
	}

	public void setDsCidadeNaturalidade(String dsCidadeNaturalidade) {
		this.dsCidadeNaturalidade = dsCidadeNaturalidade;
	}

	public String getSgUfNascimento() {
		return this.sgUfNascimento;
	}

	public void setSgUfNascimento(String sgUfNascimento) {
		this.sgUfNascimento = sgUfNascimento;
	}

	public String getDsCor() {
		return this.dsCor;
	}

	public void setDsCor(String dsCor) {
		this.dsCor = dsCor;
	}

	public String getDsEstadoCivil() {
		return this.dsEstadoCivil;
	}

	public void setDsEstadoCivil(String dsEstadoCivil) {
		this.dsEstadoCivil = dsEstadoCivil;
	}

	public String getDsEmail() {
		return this.dsEmail;
	}

	public void setDsEmail(String dsEmail) {
		this.dsEmail = dsEmail;
	}

	public Integer getNrCep() {
		return this.nrCep;
	}

	public void setNrCep(Integer nrCep) {
		this.nrCep = nrCep;
	}

	public String getDsEndereco() {
		return this.dsEndereco;
	}

	public void setDsEndereco(String dsEndereco) {
		this.dsEndereco = dsEndereco;
	}

	public String getDsBairro() {
		return this.dsBairro;
	}

	public void setDsBairro(String dsBairro) {
		this.dsBairro = dsBairro;
	}

	public String getSgUfEndereco() {
		return this.sgUfEndereco;
	}

	public void setSgUfEndereco(String sgUfEndereco) {
		this.sgUfEndereco = sgUfEndereco;
	}

	public String getDsPontoReferencia() {
		return this.dsPontoReferencia;
	}

	public void setDsPontoReferencia(String dsPontoReferencia) {
		this.dsPontoReferencia = dsPontoReferencia;
	}

	public String getNrFoneCelular() {
		return this.nrFoneCelular;
	}

	public void setNrFoneCelular(String nrFoneCelular) {
		this.nrFoneCelular = nrFoneCelular;
	}

	public String getNrTelefoneResidencial() {
		return this.nrTelefoneResidencial;
	}

	public void setNrTelefoneResidencial(String nrTelefoneResidencial) {
		this.nrTelefoneResidencial = nrTelefoneResidencial;
	}

	public String getNrTelefoneComercial() {
		return this.nrTelefoneComercial;
	}

	public void setNrTelefoneComercial(String nrTelefoneComercial) {
		this.nrTelefoneComercial = nrTelefoneComercial;
	}

	public String getDsProfissao() {
		return this.dsProfissao;
	}

	public void setDsProfissao(String dsProfissao) {
		this.dsProfissao = dsProfissao;
	}

	public String getNrCts() {
		return this.nrCts;
	}

	public void setNrCts(String nrCts) {
		this.nrCts = nrCts;
	}

	public String getNrSerieCtps() {
		return this.nrSerieCtps;
	}

	public void setNrSerieCtps(String nrSerieCtps) {
		this.nrSerieCtps = nrSerieCtps;
	}

	public String getNrTituloEleitor() {
		return this.nrTituloEleitor;
	}

	public void setNrTituloEleitor(String nrTituloEleitor) {
		this.nrTituloEleitor = nrTituloEleitor;
	}

	public String getNrZonaTitulo() {
		return this.nrZonaTitulo;
	}

	public void setNrZonaTitulo(String nrZonaTitulo) {
		this.nrZonaTitulo = nrZonaTitulo;
	}

	public String getNrSessaoTitulo() {
		return this.nrSessaoTitulo;
	}

	public void setNrSessaoTitulo(String nrSessaoTitulo) {
		this.nrSessaoTitulo = nrSessaoTitulo;
	}

	public String getDsProblemaSaude() {
		return this.dsProblemaSaude;
	}

	public void setDsProblemaSaude(String dsProblemaSaude) {
		this.dsProblemaSaude = dsProblemaSaude;
	}

	public String getDsMedicamentosControlados() {
		return this.dsMedicamentosControlados;
	}

	public void setDsMedicamentosControlados(String dsMedicamentosControlados) {
		this.dsMedicamentosControlados = dsMedicamentosControlados;
	}

	public String getNmEmpresaTrabalho() {
		return this.nmEmpresaTrabalho;
	}

	public void setNmEmpresaTrabalho(String nmEmpresaTrabalho) {
		this.nmEmpresaTrabalho = nmEmpresaTrabalho;
	}

	public String getStAutorizaEmail() {
		return this.stAutorizaEmail;
	}

	public void setStAutorizaEmail(String stAutorizaEmail) {
		this.stAutorizaEmail = stAutorizaEmail;
	}

	public String getDsAtendidoOrgaoRede() {
		return this.dsAtendidoOrgaoRede;
	}

	public void setDsAtendidoOrgaoRede(String dsAtendidoOrgaoRede) {
		this.dsAtendidoOrgaoRede = dsAtendidoOrgaoRede;
	}

	public String getDsRedeApoioSocial() {
		return this.dsRedeApoioSocial;
	}

	public void setDsRedeApoioSocial(String dsRedeApoioSocial) {
		this.dsRedeApoioSocial = dsRedeApoioSocial;
	}

	public String getNrNis() {
		return this.nrNis;
	}

	public void setNrNis(String nrNis) {
		this.nrNis = nrNis;
	}

	public String getStBenBolsaFamilia() {
		return this.stBenBolsaFamilia;
	}

	public void setStBenBolsaFamilia(String stBenBolsaFamilia) {
		this.stBenBolsaFamilia = stBenBolsaFamilia;
	}

	public BigDecimal getVlBolsaFamilia() {
		return this.vlBolsaFamilia;
	}

	public void setVlBolsaFamilia(BigDecimal vlBolsaFamilia) {
		this.vlBolsaFamilia = vlBolsaFamilia;
	}

	public String getDsOutrosBenSoc() {
		return this.dsOutrosBenSoc;
	}

	public void setDsOutrosBenSoc(String dsOutrosBenSoc) {
		this.dsOutrosBenSoc = dsOutrosBenSoc;
	}

	public String getVlOutrosBenerficiosSoc() {
		return this.vlOutrosBenerficiosSoc;
	}

	public void setVlOutrosBenerficiosSoc(String vlOutrosBenerficiosSoc) {
		this.vlOutrosBenerficiosSoc = vlOutrosBenerficiosSoc;
	}

	public String getDsAtendidoOrgaoRede1() {
		return this.dsAtendidoOrgaoRede1;
	}

	public void setDsAtendidoOrgaoRede1(String dsAtendidoOrgaoRede1) {
		this.dsAtendidoOrgaoRede1 = dsAtendidoOrgaoRede1;
	}

	public String getStAtendidoOrgaoRede() {
		return this.stAtendidoOrgaoRede;
	}

	public void setStAtendidoOrgaoRede(String stAtendidoOrgaoRede) {
		this.stAtendidoOrgaoRede = stAtendidoOrgaoRede;
	}

	public String getDsRedeApoioSocial1() {
		return this.dsRedeApoioSocial1;
	}

	public void setDsRedeApoioSocial1(String dsRedeApoioSocial1) {
		this.dsRedeApoioSocial1 = dsRedeApoioSocial1;
	}

	public String getDsFormaIngressoEntidade() {
		return this.dsFormaIngressoEntidade;
	}

	public void setDsFormaIngressoEntidade(String dsFormaIngressoEntidade) {
		this.dsFormaIngressoEntidade = dsFormaIngressoEntidade;
	}

	public String getDsRedeApSocRelev() {
		return this.dsRedeApSocRelev;
	}

	public void setDsRedeApSocRelev(String dsRedeApSocRelev) {
		this.dsRedeApSocRelev = dsRedeApSocRelev;
	}

	public String getDsCondicaoMoradia() {
		return this.dsCondicaoMoradia;
	}

	public void setDsCondicaoMoradia(String dsCondicaoMoradia) {
		this.dsCondicaoMoradia = dsCondicaoMoradia;
	}

	public BigDecimal getVlAluguel() {
		return this.vlAluguel;
	}

	public void setVlAluguel(BigDecimal vlAluguel) {
		this.vlAluguel = vlAluguel;
	}

	public BigDecimal getVlRenda() {
		return this.vlRenda;
	}

	public void setVlRenda(BigDecimal vlRenda) {
		this.vlRenda = vlRenda;
	}

	public String getDsSituacaoTrabalho() {
		return this.dsSituacaoTrabalho;
	}

	public void setDsSituacaoTrabalho(String dsSituacaoTrabalho) {
		this.dsSituacaoTrabalho = dsSituacaoTrabalho;
	}

	public String getDsEscola() {
		return this.dsEscola;
	}

	public void setDsEscola(String dsEscola) {
		this.dsEscola = dsEscola;
	}

	public String getDsTurno() {
		return this.dsTurno;
	}

	public void setDsTurno(String dsTurno) {
		this.dsTurno = dsTurno;
	}

	public String getDsCursoEscola() {
		return this.dsCursoEscola;
	}

	public void setDsCursoEscola(String dsCursoEscola) {
		this.dsCursoEscola = dsCursoEscola;
	}

	public String getDsPeriodoEscola() {
		return this.dsPeriodoEscola;
	}

	public void setDsPeriodoEscola(String dsPeriodoEscola) {
		this.dsPeriodoEscola = dsPeriodoEscola;
	}

	public String getDsSerieEscola() {
		return this.dsSerieEscola;
	}

	public void setDsSerieEscola(String dsSerieEscola) {
		this.dsSerieEscola = dsSerieEscola;
	}

	public String getDsTipoEscola() {
		return this.dsTipoEscola;
	}

	public void setDsTipoEscola(String dsTipoEscola) {
		this.dsTipoEscola = dsTipoEscola;
	}

	public String getDsEscolaridade() {
		return this.dsEscolaridade;
	}

	public void setDsEscolaridade(String dsEscolaridade) {
		this.dsEscolaridade = dsEscolaridade;
	}

	public String getDsNivelEscolaridade() {
		return this.dsNivelEscolaridade;
	}

	public void setDsNivelEscolaridade(String dsNivelEscolaridade) {
		this.dsNivelEscolaridade = dsNivelEscolaridade;
	}

	public String getDsRegiaoEscola() {
		return this.dsRegiaoEscola;
	}

	public void setDsRegiaoEscola(String dsRegiaoEscola) {
		this.dsRegiaoEscola = dsRegiaoEscola;
	}

	public String getTxObservacoes() {
		return this.txObservacoes;
	}

	public void setTxObservacoes(String txObservacoes) {
		this.txObservacoes = txObservacoes;
	}

	public String getCsMotivoNaoTrab() {
		return this.csMotivoNaoTrab;
	}

	public void setCsMotivoNaoTrab(String csMotivoNaoTrab) {
		this.csMotivoNaoTrab = csMotivoNaoTrab;
	}

	public String getDsMotivoNaoTrab() {
		return this.dsMotivoNaoTrab;
	}

	public void setDsMotivoNaoTrab(String dsMotivoNaoTrab) {
		this.dsMotivoNaoTrab = dsMotivoNaoTrab;
	}

	public Set getAlunoses() {
		return this.alunoses;
	}

	public void setAlunoses(Set alunoses) {
		this.alunoses = alunoses;
	}

	public Set getCadastroReservaAtividadeses() {
		return this.cadastroReservaAtividadeses;
	}

	public void setCadastroReservaAtividadeses(Set cadastroReservaAtividadeses) {
		this.cadastroReservaAtividadeses = cadastroReservaAtividadeses;
	}

	public Set getResponsaveises() {
		return this.responsaveises;
	}

	public void setResponsaveises(Set responsaveises) {
		this.responsaveises = responsaveises;
	}

	public Set getTalentosPfs() {
		return this.talentosPfs;
	}

	public void setTalentosPfs(Set talentosPfs) {
		this.talentosPfs = talentosPfs;
	}

	public Set getFamiliareses() {
		return this.familiareses;
	}

	public void setFamiliareses(Set familiareses) {
		this.familiareses = familiareses;
	}

	public Set getContatosEmpresas() {
		return this.contatosEmpresas;
	}

	public void setContatosEmpresas(Set contatosEmpresas) {
		this.contatosEmpresas = contatosEmpresas;
	}

	public Set getUsuariosSistemas() {
		return this.usuariosSistemas;
	}

	public void setUsuariosSistemas(Set usuariosSistemas) {
		this.usuariosSistemas = usuariosSistemas;
	}

	public Set getFuncionarioses() {
		return this.funcionarioses;
	}

	public void setFuncionarioses(Set funcionarioses) {
		this.funcionarioses = funcionarioses;
	}

	public Set getCursosFormacaoPfs() {
		return this.cursosFormacaoPfs;
	}

	public void setCursosFormacaoPfs(Set cursosFormacaoPfs) {
		this.cursosFormacaoPfs = cursosFormacaoPfs;
	}

}
