package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PlanosAcao generated by hbm2java
 */
public class PlanosAcao implements java.io.Serializable {

	private long idPlanoAcao;
	private Iniciativas iniciativas;
	private String nmPlanoAcao;
	private Date dtInicioPlanoAcao;
	private Date dtFimPlanoAcao;
	private Set atividadeses = new HashSet(0);

	public PlanosAcao() {
	}

	public PlanosAcao(long idPlanoAcao, Iniciativas iniciativas, String nmPlanoAcao, Date dtInicioPlanoAcao) {
		this.idPlanoAcao = idPlanoAcao;
		this.iniciativas = iniciativas;
		this.nmPlanoAcao = nmPlanoAcao;
		this.dtInicioPlanoAcao = dtInicioPlanoAcao;
	}

	public PlanosAcao(long idPlanoAcao, Iniciativas iniciativas, String nmPlanoAcao, Date dtInicioPlanoAcao,
			Date dtFimPlanoAcao, Set atividadeses) {
		this.idPlanoAcao = idPlanoAcao;
		this.iniciativas = iniciativas;
		this.nmPlanoAcao = nmPlanoAcao;
		this.dtInicioPlanoAcao = dtInicioPlanoAcao;
		this.dtFimPlanoAcao = dtFimPlanoAcao;
		this.atividadeses = atividadeses;
	}

	public long getIdPlanoAcao() {
		return this.idPlanoAcao;
	}

	public void setIdPlanoAcao(long idPlanoAcao) {
		this.idPlanoAcao = idPlanoAcao;
	}

	public Iniciativas getIniciativas() {
		return this.iniciativas;
	}

	public void setIniciativas(Iniciativas iniciativas) {
		this.iniciativas = iniciativas;
	}

	public String getNmPlanoAcao() {
		return this.nmPlanoAcao;
	}

	public void setNmPlanoAcao(String nmPlanoAcao) {
		this.nmPlanoAcao = nmPlanoAcao;
	}

	public Date getDtInicioPlanoAcao() {
		return this.dtInicioPlanoAcao;
	}

	public void setDtInicioPlanoAcao(Date dtInicioPlanoAcao) {
		this.dtInicioPlanoAcao = dtInicioPlanoAcao;
	}

	public Date getDtFimPlanoAcao() {
		return this.dtFimPlanoAcao;
	}

	public void setDtFimPlanoAcao(Date dtFimPlanoAcao) {
		this.dtFimPlanoAcao = dtFimPlanoAcao;
	}

	public Set getAtividadeses() {
		return this.atividadeses;
	}

	public void setAtividadeses(Set atividadeses) {
		this.atividadeses = atividadeses;
	}

}
