package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;

/**
 * ProdutosAtividades generated by hbm2java
 */
public class ProdutosAtividades implements java.io.Serializable {

	private long idProdutoAtividade;
	private Atividades atividades;
	private Produtos produtos;
	private String dsProdutoAtividade;
	private String txProdutoAtividade;
	private Date dtAquisicao;
	private BigDecimal vlProduto;
	private Date dtVendaProduto;
	private String dsOrigemProduto;
	private BigDecimal qtdProduto;
	private BigDecimal qtdProdutoVendida;
	private String dsFormaPagamento;

	public ProdutosAtividades() {
	}

	public ProdutosAtividades(long idProdutoAtividade, Atividades atividades, Produtos produtos,
			String dsProdutoAtividade) {
		this.idProdutoAtividade = idProdutoAtividade;
		this.atividades = atividades;
		this.produtos = produtos;
		this.dsProdutoAtividade = dsProdutoAtividade;
	}

	public ProdutosAtividades(long idProdutoAtividade, Atividades atividades, Produtos produtos,
			String dsProdutoAtividade, String txProdutoAtividade, Date dtAquisicao, BigDecimal vlProduto,
			Date dtVendaProduto, String dsOrigemProduto, BigDecimal qtdProduto, BigDecimal qtdProdutoVendida,
			String dsFormaPagamento) {
		this.idProdutoAtividade = idProdutoAtividade;
		this.atividades = atividades;
		this.produtos = produtos;
		this.dsProdutoAtividade = dsProdutoAtividade;
		this.txProdutoAtividade = txProdutoAtividade;
		this.dtAquisicao = dtAquisicao;
		this.vlProduto = vlProduto;
		this.dtVendaProduto = dtVendaProduto;
		this.dsOrigemProduto = dsOrigemProduto;
		this.qtdProduto = qtdProduto;
		this.qtdProdutoVendida = qtdProdutoVendida;
		this.dsFormaPagamento = dsFormaPagamento;
	}

	public long getIdProdutoAtividade() {
		return this.idProdutoAtividade;
	}

	public void setIdProdutoAtividade(long idProdutoAtividade) {
		this.idProdutoAtividade = idProdutoAtividade;
	}

	public Atividades getAtividades() {
		return this.atividades;
	}

	public void setAtividades(Atividades atividades) {
		this.atividades = atividades;
	}

	public Produtos getProdutos() {
		return this.produtos;
	}

	public void setProdutos(Produtos produtos) {
		this.produtos = produtos;
	}

	public String getDsProdutoAtividade() {
		return this.dsProdutoAtividade;
	}

	public void setDsProdutoAtividade(String dsProdutoAtividade) {
		this.dsProdutoAtividade = dsProdutoAtividade;
	}

	public String getTxProdutoAtividade() {
		return this.txProdutoAtividade;
	}

	public void setTxProdutoAtividade(String txProdutoAtividade) {
		this.txProdutoAtividade = txProdutoAtividade;
	}

	public Date getDtAquisicao() {
		return this.dtAquisicao;
	}

	public void setDtAquisicao(Date dtAquisicao) {
		this.dtAquisicao = dtAquisicao;
	}

	public BigDecimal getVlProduto() {
		return this.vlProduto;
	}

	public void setVlProduto(BigDecimal vlProduto) {
		this.vlProduto = vlProduto;
	}

	public Date getDtVendaProduto() {
		return this.dtVendaProduto;
	}

	public void setDtVendaProduto(Date dtVendaProduto) {
		this.dtVendaProduto = dtVendaProduto;
	}

	public String getDsOrigemProduto() {
		return this.dsOrigemProduto;
	}

	public void setDsOrigemProduto(String dsOrigemProduto) {
		this.dsOrigemProduto = dsOrigemProduto;
	}

	public BigDecimal getQtdProduto() {
		return this.qtdProduto;
	}

	public void setQtdProduto(BigDecimal qtdProduto) {
		this.qtdProduto = qtdProduto;
	}

	public BigDecimal getQtdProdutoVendida() {
		return this.qtdProdutoVendida;
	}

	public void setQtdProdutoVendida(BigDecimal qtdProdutoVendida) {
		this.qtdProdutoVendida = qtdProdutoVendida;
	}

	public String getDsFormaPagamento() {
		return this.dsFormaPagamento;
	}

	public void setDsFormaPagamento(String dsFormaPagamento) {
		this.dsFormaPagamento = dsFormaPagamento;
	}

}
