package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Produtos generated by hbm2java
 */
public class Produtos implements java.io.Serializable {

	private long idProduto;
	private String nmProduto;
	private String nmProdutoNf;
	private String cdUnidadeMedida;
	private String dsUnidadeMedida;
	private Set estoqueses = new HashSet(0);
	private Set produtosAtividadeses = new HashSet(0);
	private Set itensFaturases = new HashSet(0);
	private Set pedidoses = new HashSet(0);

	public Produtos() {
	}

	public Produtos(long idProduto) {
		this.idProduto = idProduto;
	}

	public Produtos(long idProduto, String nmProduto, String nmProdutoNf, String cdUnidadeMedida,
			String dsUnidadeMedida, Set estoqueses, Set produtosAtividadeses, Set itensFaturases, Set pedidoses) {
		this.idProduto = idProduto;
		this.nmProduto = nmProduto;
		this.nmProdutoNf = nmProdutoNf;
		this.cdUnidadeMedida = cdUnidadeMedida;
		this.dsUnidadeMedida = dsUnidadeMedida;
		this.estoqueses = estoqueses;
		this.produtosAtividadeses = produtosAtividadeses;
		this.itensFaturases = itensFaturases;
		this.pedidoses = pedidoses;
	}

	public long getIdProduto() {
		return this.idProduto;
	}

	public void setIdProduto(long idProduto) {
		this.idProduto = idProduto;
	}

	public String getNmProduto() {
		return this.nmProduto;
	}

	public void setNmProduto(String nmProduto) {
		this.nmProduto = nmProduto;
	}

	public String getNmProdutoNf() {
		return this.nmProdutoNf;
	}

	public void setNmProdutoNf(String nmProdutoNf) {
		this.nmProdutoNf = nmProdutoNf;
	}

	public String getCdUnidadeMedida() {
		return this.cdUnidadeMedida;
	}

	public void setCdUnidadeMedida(String cdUnidadeMedida) {
		this.cdUnidadeMedida = cdUnidadeMedida;
	}

	public String getDsUnidadeMedida() {
		return this.dsUnidadeMedida;
	}

	public void setDsUnidadeMedida(String dsUnidadeMedida) {
		this.dsUnidadeMedida = dsUnidadeMedida;
	}

	public Set getEstoqueses() {
		return this.estoqueses;
	}

	public void setEstoqueses(Set estoqueses) {
		this.estoqueses = estoqueses;
	}

	public Set getProdutosAtividadeses() {
		return this.produtosAtividadeses;
	}

	public void setProdutosAtividadeses(Set produtosAtividadeses) {
		this.produtosAtividadeses = produtosAtividadeses;
	}

	public Set getItensFaturases() {
		return this.itensFaturases;
	}

	public void setItensFaturases(Set itensFaturases) {
		this.itensFaturases = itensFaturases;
	}

	public Set getPedidoses() {
		return this.pedidoses;
	}

	public void setPedidoses(Set pedidoses) {
		this.pedidoses = pedidoses;
	}

}
