package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Programas generated by hbm2java
 */
public class Programas implements java.io.Serializable {

	private long idPrograma;
	private Iniciativas iniciativas;
	private long idObjetivo;
	private Long idCoordenador;
	private String nmPrograma;
	private String dsPrograma;
	private Byte nrFaixaEtariaIni;
	private Byte nrFaixaEtariaFim;
	private Date dtImplantacao;
	private Date dtTermino;
	private Set projetoses = new HashSet(0);
	private Set colaboradoresProgramases = new HashSet(0);

	public Programas() {
	}

	public Programas(long idPrograma, Iniciativas iniciativas, long idObjetivo, String nmPrograma, Date dtImplantacao) {
		this.idPrograma = idPrograma;
		this.iniciativas = iniciativas;
		this.idObjetivo = idObjetivo;
		this.nmPrograma = nmPrograma;
		this.dtImplantacao = dtImplantacao;
	}

	public Programas(long idPrograma, Iniciativas iniciativas, long idObjetivo, Long idCoordenador, String nmPrograma,
			String dsPrograma, Byte nrFaixaEtariaIni, Byte nrFaixaEtariaFim, Date dtImplantacao, Date dtTermino,
			Set projetoses, Set colaboradoresProgramases) {
		this.idPrograma = idPrograma;
		this.iniciativas = iniciativas;
		this.idObjetivo = idObjetivo;
		this.idCoordenador = idCoordenador;
		this.nmPrograma = nmPrograma;
		this.dsPrograma = dsPrograma;
		this.nrFaixaEtariaIni = nrFaixaEtariaIni;
		this.nrFaixaEtariaFim = nrFaixaEtariaFim;
		this.dtImplantacao = dtImplantacao;
		this.dtTermino = dtTermino;
		this.projetoses = projetoses;
		this.colaboradoresProgramases = colaboradoresProgramases;
	}

	public long getIdPrograma() {
		return this.idPrograma;
	}

	public void setIdPrograma(long idPrograma) {
		this.idPrograma = idPrograma;
	}

	public Iniciativas getIniciativas() {
		return this.iniciativas;
	}

	public void setIniciativas(Iniciativas iniciativas) {
		this.iniciativas = iniciativas;
	}

	public long getIdObjetivo() {
		return this.idObjetivo;
	}

	public void setIdObjetivo(long idObjetivo) {
		this.idObjetivo = idObjetivo;
	}

	public Long getIdCoordenador() {
		return this.idCoordenador;
	}

	public void setIdCoordenador(Long idCoordenador) {
		this.idCoordenador = idCoordenador;
	}

	public String getNmPrograma() {
		return this.nmPrograma;
	}

	public void setNmPrograma(String nmPrograma) {
		this.nmPrograma = nmPrograma;
	}

	public String getDsPrograma() {
		return this.dsPrograma;
	}

	public void setDsPrograma(String dsPrograma) {
		this.dsPrograma = dsPrograma;
	}

	public Byte getNrFaixaEtariaIni() {
		return this.nrFaixaEtariaIni;
	}

	public void setNrFaixaEtariaIni(Byte nrFaixaEtariaIni) {
		this.nrFaixaEtariaIni = nrFaixaEtariaIni;
	}

	public Byte getNrFaixaEtariaFim() {
		return this.nrFaixaEtariaFim;
	}

	public void setNrFaixaEtariaFim(Byte nrFaixaEtariaFim) {
		this.nrFaixaEtariaFim = nrFaixaEtariaFim;
	}

	public Date getDtImplantacao() {
		return this.dtImplantacao;
	}

	public void setDtImplantacao(Date dtImplantacao) {
		this.dtImplantacao = dtImplantacao;
	}

	public Date getDtTermino() {
		return this.dtTermino;
	}

	public void setDtTermino(Date dtTermino) {
		this.dtTermino = dtTermino;
	}

	public Set getProjetoses() {
		return this.projetoses;
	}

	public void setProjetoses(Set projetoses) {
		this.projetoses = projetoses;
	}

	public Set getColaboradoresProgramases() {
		return this.colaboradoresProgramases;
	}

	public void setColaboradoresProgramases(Set colaboradoresProgramases) {
		this.colaboradoresProgramases = colaboradoresProgramases;
	}

}
