package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Projetos generated by hbm2java
 */
public class Projetos implements java.io.Serializable {

	private long idProjeto;
	private Iniciativas iniciativas;
	private Programas programas;
	private String nmProjeto;
	private String dsProjeto;
	private Date dtPrevProjeto;
	private Date dtPrevTermino;
	private Date dtInicioProjeto;
	private Date dtFimProjeto;
	private Set atividadeses = new HashSet(0);
	private Set colaboradoresProjetoses = new HashSet(0);

	public Projetos() {
	}

	public Projetos(long idProjeto, String nmProjeto, Date dtPrevProjeto) {
		this.idProjeto = idProjeto;
		this.nmProjeto = nmProjeto;
		this.dtPrevProjeto = dtPrevProjeto;
	}

	public Projetos(long idProjeto, Iniciativas iniciativas, Programas programas, String nmProjeto, String dsProjeto,
			Date dtPrevProjeto, Date dtPrevTermino, Date dtInicioProjeto, Date dtFimProjeto, Set atividadeses,
			Set colaboradoresProjetoses) {
		this.idProjeto = idProjeto;
		this.iniciativas = iniciativas;
		this.programas = programas;
		this.nmProjeto = nmProjeto;
		this.dsProjeto = dsProjeto;
		this.dtPrevProjeto = dtPrevProjeto;
		this.dtPrevTermino = dtPrevTermino;
		this.dtInicioProjeto = dtInicioProjeto;
		this.dtFimProjeto = dtFimProjeto;
		this.atividadeses = atividadeses;
		this.colaboradoresProjetoses = colaboradoresProjetoses;
	}

	public long getIdProjeto() {
		return this.idProjeto;
	}

	public void setIdProjeto(long idProjeto) {
		this.idProjeto = idProjeto;
	}

	public Iniciativas getIniciativas() {
		return this.iniciativas;
	}

	public void setIniciativas(Iniciativas iniciativas) {
		this.iniciativas = iniciativas;
	}

	public Programas getProgramas() {
		return this.programas;
	}

	public void setProgramas(Programas programas) {
		this.programas = programas;
	}

	public String getNmProjeto() {
		return this.nmProjeto;
	}

	public void setNmProjeto(String nmProjeto) {
		this.nmProjeto = nmProjeto;
	}

	public String getDsProjeto() {
		return this.dsProjeto;
	}

	public void setDsProjeto(String dsProjeto) {
		this.dsProjeto = dsProjeto;
	}

	public Date getDtPrevProjeto() {
		return this.dtPrevProjeto;
	}

	public void setDtPrevProjeto(Date dtPrevProjeto) {
		this.dtPrevProjeto = dtPrevProjeto;
	}

	public Date getDtPrevTermino() {
		return this.dtPrevTermino;
	}

	public void setDtPrevTermino(Date dtPrevTermino) {
		this.dtPrevTermino = dtPrevTermino;
	}

	public Date getDtInicioProjeto() {
		return this.dtInicioProjeto;
	}

	public void setDtInicioProjeto(Date dtInicioProjeto) {
		this.dtInicioProjeto = dtInicioProjeto;
	}

	public Date getDtFimProjeto() {
		return this.dtFimProjeto;
	}

	public void setDtFimProjeto(Date dtFimProjeto) {
		this.dtFimProjeto = dtFimProjeto;
	}

	public Set getAtividadeses() {
		return this.atividadeses;
	}

	public void setAtividadeses(Set atividadeses) {
		this.atividadeses = atividadeses;
	}

	public Set getColaboradoresProjetoses() {
		return this.colaboradoresProjetoses;
	}

	public void setColaboradoresProjetoses(Set colaboradoresProjetoses) {
		this.colaboradoresProjetoses = colaboradoresProjetoses;
	}

}
