package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Questionarios generated by hbm2java
 */
public class Questionarios implements java.io.Serializable {

	private long idQuetionario;
	private String dsQuestionario;
	private Date dtInicioQuestionario;
	private Date dtFimQuestionario;
	private String dsTipoQuestionario;
	private Set talentosPfs = new HashSet(0);

	public Questionarios() {
	}

	public Questionarios(long idQuetionario, String dsQuestionario) {
		this.idQuetionario = idQuetionario;
		this.dsQuestionario = dsQuestionario;
	}

	public Questionarios(long idQuetionario, String dsQuestionario, Date dtInicioQuestionario, Date dtFimQuestionario,
			String dsTipoQuestionario, Set talentosPfs) {
		this.idQuetionario = idQuetionario;
		this.dsQuestionario = dsQuestionario;
		this.dtInicioQuestionario = dtInicioQuestionario;
		this.dtFimQuestionario = dtFimQuestionario;
		this.dsTipoQuestionario = dsTipoQuestionario;
		this.talentosPfs = talentosPfs;
	}

	public long getIdQuetionario() {
		return this.idQuetionario;
	}

	public void setIdQuetionario(long idQuetionario) {
		this.idQuetionario = idQuetionario;
	}

	public String getDsQuestionario() {
		return this.dsQuestionario;
	}

	public void setDsQuestionario(String dsQuestionario) {
		this.dsQuestionario = dsQuestionario;
	}

	public Date getDtInicioQuestionario() {
		return this.dtInicioQuestionario;
	}

	public void setDtInicioQuestionario(Date dtInicioQuestionario) {
		this.dtInicioQuestionario = dtInicioQuestionario;
	}

	public Date getDtFimQuestionario() {
		return this.dtFimQuestionario;
	}

	public void setDtFimQuestionario(Date dtFimQuestionario) {
		this.dtFimQuestionario = dtFimQuestionario;
	}

	public String getDsTipoQuestionario() {
		return this.dsTipoQuestionario;
	}

	public void setDsTipoQuestionario(String dsTipoQuestionario) {
		this.dsTipoQuestionario = dsTipoQuestionario;
	}

	public Set getTalentosPfs() {
		return this.talentosPfs;
	}

	public void setTalentosPfs(Set talentosPfs) {
		this.talentosPfs = talentosPfs;
	}

}
