package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

/**
 * ReprovacoesAluno generated by hbm2java
 */
public class ReprovacoesAluno implements java.io.Serializable {

	private long idReprovacaoAluno;
	private Alunos alunos;
	private String dtReprovacaoAluno;
	private String dsReprovacaoAluno;
	private String dsSerieReprovacao;
	private Long qtdReprovacao;

	public ReprovacoesAluno() {
	}

	public ReprovacoesAluno(long idReprovacaoAluno, Alunos alunos) {
		this.idReprovacaoAluno = idReprovacaoAluno;
		this.alunos = alunos;
	}

	public ReprovacoesAluno(long idReprovacaoAluno, Alunos alunos, String dtReprovacaoAluno, String dsReprovacaoAluno,
			String dsSerieReprovacao, Long qtdReprovacao) {
		this.idReprovacaoAluno = idReprovacaoAluno;
		this.alunos = alunos;
		this.dtReprovacaoAluno = dtReprovacaoAluno;
		this.dsReprovacaoAluno = dsReprovacaoAluno;
		this.dsSerieReprovacao = dsSerieReprovacao;
		this.qtdReprovacao = qtdReprovacao;
	}

	public long getIdReprovacaoAluno() {
		return this.idReprovacaoAluno;
	}

	public void setIdReprovacaoAluno(long idReprovacaoAluno) {
		this.idReprovacaoAluno = idReprovacaoAluno;
	}

	public Alunos getAlunos() {
		return this.alunos;
	}

	public void setAlunos(Alunos alunos) {
		this.alunos = alunos;
	}

	public String getDtReprovacaoAluno() {
		return this.dtReprovacaoAluno;
	}

	public void setDtReprovacaoAluno(String dtReprovacaoAluno) {
		this.dtReprovacaoAluno = dtReprovacaoAluno;
	}

	public String getDsReprovacaoAluno() {
		return this.dsReprovacaoAluno;
	}

	public void setDsReprovacaoAluno(String dsReprovacaoAluno) {
		this.dsReprovacaoAluno = dsReprovacaoAluno;
	}

	public String getDsSerieReprovacao() {
		return this.dsSerieReprovacao;
	}

	public void setDsSerieReprovacao(String dsSerieReprovacao) {
		this.dsSerieReprovacao = dsSerieReprovacao;
	}

	public Long getQtdReprovacao() {
		return this.qtdReprovacao;
	}

	public void setQtdReprovacao(Long qtdReprovacao) {
		this.qtdReprovacao = qtdReprovacao;
	}

}
