package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Responsaveis generated by hbm2java
 */
public class Responsaveis implements java.io.Serializable {

	private long idResponsavel;
	private PessoasFisicas pessoasFisicas;
	private Date dtCadastro;
	private String dsOutrasInformacoes;
	private Date dtDesligamento;
	private String dsDesligamento;
	private Set atendimentoses = new HashSet(0);
	private Set familiareses = new HashSet(0);
	private Set vulnerabilidadesResponsavels = new HashSet(0);
	private Set responsaveisAlunoses = new HashSet(0);

	public Responsaveis() {
	}

	public Responsaveis(long idResponsavel, PessoasFisicas pessoasFisicas, Date dtCadastro) {
		this.idResponsavel = idResponsavel;
		this.pessoasFisicas = pessoasFisicas;
		this.dtCadastro = dtCadastro;
	}

	public Responsaveis(long idResponsavel, PessoasFisicas pessoasFisicas, Date dtCadastro, String dsOutrasInformacoes,
			Date dtDesligamento, String dsDesligamento, Set atendimentoses, Set familiareses,
			Set vulnerabilidadesResponsavels, Set responsaveisAlunoses) {
		this.idResponsavel = idResponsavel;
		this.pessoasFisicas = pessoasFisicas;
		this.dtCadastro = dtCadastro;
		this.dsOutrasInformacoes = dsOutrasInformacoes;
		this.dtDesligamento = dtDesligamento;
		this.dsDesligamento = dsDesligamento;
		this.atendimentoses = atendimentoses;
		this.familiareses = familiareses;
		this.vulnerabilidadesResponsavels = vulnerabilidadesResponsavels;
		this.responsaveisAlunoses = responsaveisAlunoses;
	}

	public long getIdResponsavel() {
		return this.idResponsavel;
	}

	public void setIdResponsavel(long idResponsavel) {
		this.idResponsavel = idResponsavel;
	}

	public PessoasFisicas getPessoasFisicas() {
		return this.pessoasFisicas;
	}

	public void setPessoasFisicas(PessoasFisicas pessoasFisicas) {
		this.pessoasFisicas = pessoasFisicas;
	}

	public Date getDtCadastro() {
		return this.dtCadastro;
	}

	public void setDtCadastro(Date dtCadastro) {
		this.dtCadastro = dtCadastro;
	}

	public String getDsOutrasInformacoes() {
		return this.dsOutrasInformacoes;
	}

	public void setDsOutrasInformacoes(String dsOutrasInformacoes) {
		this.dsOutrasInformacoes = dsOutrasInformacoes;
	}

	public Date getDtDesligamento() {
		return this.dtDesligamento;
	}

	public void setDtDesligamento(Date dtDesligamento) {
		this.dtDesligamento = dtDesligamento;
	}

	public String getDsDesligamento() {
		return this.dsDesligamento;
	}

	public void setDsDesligamento(String dsDesligamento) {
		this.dsDesligamento = dsDesligamento;
	}

	public Set getAtendimentoses() {
		return this.atendimentoses;
	}

	public void setAtendimentoses(Set atendimentoses) {
		this.atendimentoses = atendimentoses;
	}

	public Set getFamiliareses() {
		return this.familiareses;
	}

	public void setFamiliareses(Set familiareses) {
		this.familiareses = familiareses;
	}

	public Set getVulnerabilidadesResponsavels() {
		return this.vulnerabilidadesResponsavels;
	}

	public void setVulnerabilidadesResponsavels(Set vulnerabilidadesResponsavels) {
		this.vulnerabilidadesResponsavels = vulnerabilidadesResponsavels;
	}

	public Set getResponsaveisAlunoses() {
		return this.responsaveisAlunoses;
	}

	public void setResponsaveisAlunoses(Set responsaveisAlunoses) {
		this.responsaveisAlunoses = responsaveisAlunoses;
	}

}
