package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Servicos generated by hbm2java
 */
public class Servicos implements java.io.Serializable {

	private long idServico;
	private String nmServico;
	private Set pedidoses = new HashSet(0);
	private Set itensFaturases = new HashSet(0);

	public Servicos() {
	}

	public Servicos(long idServico) {
		this.idServico = idServico;
	}

	public Servicos(long idServico, String nmServico, Set pedidoses, Set itensFaturases) {
		this.idServico = idServico;
		this.nmServico = nmServico;
		this.pedidoses = pedidoses;
		this.itensFaturases = itensFaturases;
	}

	public long getIdServico() {
		return this.idServico;
	}

	public void setIdServico(long idServico) {
		this.idServico = idServico;
	}

	public String getNmServico() {
		return this.nmServico;
	}

	public void setNmServico(String nmServico) {
		this.nmServico = nmServico;
	}

	public Set getPedidoses() {
		return this.pedidoses;
	}

	public void setPedidoses(Set pedidoses) {
		this.pedidoses = pedidoses;
	}

	public Set getItensFaturases() {
		return this.itensFaturases;
	}

	public void setItensFaturases(Set itensFaturases) {
		this.itensFaturases = itensFaturases;
	}

}
