package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * SituacoesVulnerabilidades generated by hbm2java
 */
public class SituacoesVulnerabilidades implements java.io.Serializable {

	private long idVulnerabilidade;
	private String dsSituacaoVulnerabilidade;
	private Set vulnerabilidadesAlunos = new HashSet(0);
	private Set vulnerabilidadesFamiliars = new HashSet(0);
	private Set vulnerabilidadesResponsavels = new HashSet(0);

	public SituacoesVulnerabilidades() {
	}

	public SituacoesVulnerabilidades(long idVulnerabilidade, String dsSituacaoVulnerabilidade) {
		this.idVulnerabilidade = idVulnerabilidade;
		this.dsSituacaoVulnerabilidade = dsSituacaoVulnerabilidade;
	}

	public SituacoesVulnerabilidades(long idVulnerabilidade, String dsSituacaoVulnerabilidade,
			Set vulnerabilidadesAlunos, Set vulnerabilidadesFamiliars, Set vulnerabilidadesResponsavels) {
		this.idVulnerabilidade = idVulnerabilidade;
		this.dsSituacaoVulnerabilidade = dsSituacaoVulnerabilidade;
		this.vulnerabilidadesAlunos = vulnerabilidadesAlunos;
		this.vulnerabilidadesFamiliars = vulnerabilidadesFamiliars;
		this.vulnerabilidadesResponsavels = vulnerabilidadesResponsavels;
	}

	public long getIdVulnerabilidade() {
		return this.idVulnerabilidade;
	}

	public void setIdVulnerabilidade(long idVulnerabilidade) {
		this.idVulnerabilidade = idVulnerabilidade;
	}

	public String getDsSituacaoVulnerabilidade() {
		return this.dsSituacaoVulnerabilidade;
	}

	public void setDsSituacaoVulnerabilidade(String dsSituacaoVulnerabilidade) {
		this.dsSituacaoVulnerabilidade = dsSituacaoVulnerabilidade;
	}

	public Set getVulnerabilidadesAlunos() {
		return this.vulnerabilidadesAlunos;
	}

	public void setVulnerabilidadesAlunos(Set vulnerabilidadesAlunos) {
		this.vulnerabilidadesAlunos = vulnerabilidadesAlunos;
	}

	public Set getVulnerabilidadesFamiliars() {
		return this.vulnerabilidadesFamiliars;
	}

	public void setVulnerabilidadesFamiliars(Set vulnerabilidadesFamiliars) {
		this.vulnerabilidadesFamiliars = vulnerabilidadesFamiliars;
	}

	public Set getVulnerabilidadesResponsavels() {
		return this.vulnerabilidadesResponsavels;
	}

	public void setVulnerabilidadesResponsavels(Set vulnerabilidadesResponsavels) {
		this.vulnerabilidadesResponsavels = vulnerabilidadesResponsavels;
	}

}
