package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Solucoes generated by hbm2java
 */
public class Solucoes implements java.io.Serializable {

	private long idSolucao;
	private String dsSolucao;
	private Set vulnerabilidadesResponsavels = new HashSet(0);
	private Set vulnerabilidadesAlunos = new HashSet(0);
	private Set atendimentoses = new HashSet(0);
	private Set vulnerabilidadesFamiliars = new HashSet(0);

	public Solucoes() {
	}

	public Solucoes(long idSolucao, String dsSolucao) {
		this.idSolucao = idSolucao;
		this.dsSolucao = dsSolucao;
	}

	public Solucoes(long idSolucao, String dsSolucao, Set vulnerabilidadesResponsavels, Set vulnerabilidadesAlunos,
			Set atendimentoses, Set vulnerabilidadesFamiliars) {
		this.idSolucao = idSolucao;
		this.dsSolucao = dsSolucao;
		this.vulnerabilidadesResponsavels = vulnerabilidadesResponsavels;
		this.vulnerabilidadesAlunos = vulnerabilidadesAlunos;
		this.atendimentoses = atendimentoses;
		this.vulnerabilidadesFamiliars = vulnerabilidadesFamiliars;
	}

	public long getIdSolucao() {
		return this.idSolucao;
	}

	public void setIdSolucao(long idSolucao) {
		this.idSolucao = idSolucao;
	}

	public String getDsSolucao() {
		return this.dsSolucao;
	}

	public void setDsSolucao(String dsSolucao) {
		this.dsSolucao = dsSolucao;
	}

	public Set getVulnerabilidadesResponsavels() {
		return this.vulnerabilidadesResponsavels;
	}

	public void setVulnerabilidadesResponsavels(Set vulnerabilidadesResponsavels) {
		this.vulnerabilidadesResponsavels = vulnerabilidadesResponsavels;
	}

	public Set getVulnerabilidadesAlunos() {
		return this.vulnerabilidadesAlunos;
	}

	public void setVulnerabilidadesAlunos(Set vulnerabilidadesAlunos) {
		this.vulnerabilidadesAlunos = vulnerabilidadesAlunos;
	}

	public Set getAtendimentoses() {
		return this.atendimentoses;
	}

	public void setAtendimentoses(Set atendimentoses) {
		this.atendimentoses = atendimentoses;
	}

	public Set getVulnerabilidadesFamiliars() {
		return this.vulnerabilidadesFamiliars;
	}

	public void setVulnerabilidadesFamiliars(Set vulnerabilidadesFamiliars) {
		this.vulnerabilidadesFamiliars = vulnerabilidadesFamiliars;
	}

}
