package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TalentosPf generated by hbm2java
 */
public class TalentosPf implements java.io.Serializable {

	private long idTalentoPf;
	private Funcionarios funcionarios;
	private PessoasFisicas pessoasFisicas;
	private Questionarios questionarios;
	private String dsRespostaTalento;
	private Date dtRespostaTalento;
	private Date nrNotaCompetencia;
	private String txObservacao;
	private Set acoesCompetenciases = new HashSet(0);

	public TalentosPf() {
	}

	public TalentosPf(long idTalentoPf, Funcionarios funcionarios, PessoasFisicas pessoasFisicas,
			Questionarios questionarios, String dsRespostaTalento) {
		this.idTalentoPf = idTalentoPf;
		this.funcionarios = funcionarios;
		this.pessoasFisicas = pessoasFisicas;
		this.questionarios = questionarios;
		this.dsRespostaTalento = dsRespostaTalento;
	}

	public TalentosPf(long idTalentoPf, Funcionarios funcionarios, PessoasFisicas pessoasFisicas,
			Questionarios questionarios, String dsRespostaTalento, Date dtRespostaTalento, Date nrNotaCompetencia,
			String txObservacao, Set acoesCompetenciases) {
		this.idTalentoPf = idTalentoPf;
		this.funcionarios = funcionarios;
		this.pessoasFisicas = pessoasFisicas;
		this.questionarios = questionarios;
		this.dsRespostaTalento = dsRespostaTalento;
		this.dtRespostaTalento = dtRespostaTalento;
		this.nrNotaCompetencia = nrNotaCompetencia;
		this.txObservacao = txObservacao;
		this.acoesCompetenciases = acoesCompetenciases;
	}

	public long getIdTalentoPf() {
		return this.idTalentoPf;
	}

	public void setIdTalentoPf(long idTalentoPf) {
		this.idTalentoPf = idTalentoPf;
	}

	public Funcionarios getFuncionarios() {
		return this.funcionarios;
	}

	public void setFuncionarios(Funcionarios funcionarios) {
		this.funcionarios = funcionarios;
	}

	public PessoasFisicas getPessoasFisicas() {
		return this.pessoasFisicas;
	}

	public void setPessoasFisicas(PessoasFisicas pessoasFisicas) {
		this.pessoasFisicas = pessoasFisicas;
	}

	public Questionarios getQuestionarios() {
		return this.questionarios;
	}

	public void setQuestionarios(Questionarios questionarios) {
		this.questionarios = questionarios;
	}

	public String getDsRespostaTalento() {
		return this.dsRespostaTalento;
	}

	public void setDsRespostaTalento(String dsRespostaTalento) {
		this.dsRespostaTalento = dsRespostaTalento;
	}

	public Date getDtRespostaTalento() {
		return this.dtRespostaTalento;
	}

	public void setDtRespostaTalento(Date dtRespostaTalento) {
		this.dtRespostaTalento = dtRespostaTalento;
	}

	public Date getNrNotaCompetencia() {
		return this.nrNotaCompetencia;
	}

	public void setNrNotaCompetencia(Date nrNotaCompetencia) {
		this.nrNotaCompetencia = nrNotaCompetencia;
	}

	public String getTxObservacao() {
		return this.txObservacao;
	}

	public void setTxObservacao(String txObservacao) {
		this.txObservacao = txObservacao;
	}

	public Set getAcoesCompetenciases() {
		return this.acoesCompetenciases;
	}

	public void setAcoesCompetenciases(Set acoesCompetenciases) {
		this.acoesCompetenciases = acoesCompetenciases;
	}

}
