package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Unidades generated by hbm2java
 */
public class Unidades implements java.io.Serializable {

	private long idUnidade;
	private Arquivos arquivos;
	private Entidades entidades;
	private String cdUnidade;
	private String nmUnidade;
	private String dsEndereco;
	private String nrTelefone;
	private String csSituacaoImovel;
	private String dsSituacaoImovel;
	private String dsEstruturaFisicaImovel;
	private Set estoqueses = new HashSet(0);
	private Set pedidoses = new HashSet(0);
	private Set alunoses = new HashSet(0);
	private Set departamentosUnidadeses = new HashSet(0);
	private Set faturases = new HashSet(0);
	private Set funcionarioses = new HashSet(0);
	private Set atividadeses = new HashSet(0);
	private Set contasBancariases = new HashSet(0);

	public Unidades() {
	}

	public Unidades(long idUnidade, Entidades entidades, String cdUnidade, String nmUnidade, String dsEndereco,
			String nrTelefone, String csSituacaoImovel) {
		this.idUnidade = idUnidade;
		this.entidades = entidades;
		this.cdUnidade = cdUnidade;
		this.nmUnidade = nmUnidade;
		this.dsEndereco = dsEndereco;
		this.nrTelefone = nrTelefone;
		this.csSituacaoImovel = csSituacaoImovel;
	}

	public Unidades(long idUnidade, Arquivos arquivos, Entidades entidades, String cdUnidade, String nmUnidade,
			String dsEndereco, String nrTelefone, String csSituacaoImovel, String dsSituacaoImovel,
			String dsEstruturaFisicaImovel, Set estoqueses, Set pedidoses, Set alunoses, Set departamentosUnidadeses,
			Set faturases, Set funcionarioses, Set atividadeses, Set contasBancariases) {
		this.idUnidade = idUnidade;
		this.arquivos = arquivos;
		this.entidades = entidades;
		this.cdUnidade = cdUnidade;
		this.nmUnidade = nmUnidade;
		this.dsEndereco = dsEndereco;
		this.nrTelefone = nrTelefone;
		this.csSituacaoImovel = csSituacaoImovel;
		this.dsSituacaoImovel = dsSituacaoImovel;
		this.dsEstruturaFisicaImovel = dsEstruturaFisicaImovel;
		this.estoqueses = estoqueses;
		this.pedidoses = pedidoses;
		this.alunoses = alunoses;
		this.departamentosUnidadeses = departamentosUnidadeses;
		this.faturases = faturases;
		this.funcionarioses = funcionarioses;
		this.atividadeses = atividadeses;
		this.contasBancariases = contasBancariases;
	}

	public long getIdUnidade() {
		return this.idUnidade;
	}

	public void setIdUnidade(long idUnidade) {
		this.idUnidade = idUnidade;
	}

	public Arquivos getArquivos() {
		return this.arquivos;
	}

	public void setArquivos(Arquivos arquivos) {
		this.arquivos = arquivos;
	}

	public Entidades getEntidades() {
		return this.entidades;
	}

	public void setEntidades(Entidades entidades) {
		this.entidades = entidades;
	}

	public String getCdUnidade() {
		return this.cdUnidade;
	}

	public void setCdUnidade(String cdUnidade) {
		this.cdUnidade = cdUnidade;
	}

	public String getNmUnidade() {
		return this.nmUnidade;
	}

	public void setNmUnidade(String nmUnidade) {
		this.nmUnidade = nmUnidade;
	}

	public String getDsEndereco() {
		return this.dsEndereco;
	}

	public void setDsEndereco(String dsEndereco) {
		this.dsEndereco = dsEndereco;
	}

	public String getNrTelefone() {
		return this.nrTelefone;
	}

	public void setNrTelefone(String nrTelefone) {
		this.nrTelefone = nrTelefone;
	}

	public String getCsSituacaoImovel() {
		return this.csSituacaoImovel;
	}

	public void setCsSituacaoImovel(String csSituacaoImovel) {
		this.csSituacaoImovel = csSituacaoImovel;
	}

	public String getDsSituacaoImovel() {
		return this.dsSituacaoImovel;
	}

	public void setDsSituacaoImovel(String dsSituacaoImovel) {
		this.dsSituacaoImovel = dsSituacaoImovel;
	}

	public String getDsEstruturaFisicaImovel() {
		return this.dsEstruturaFisicaImovel;
	}

	public void setDsEstruturaFisicaImovel(String dsEstruturaFisicaImovel) {
		this.dsEstruturaFisicaImovel = dsEstruturaFisicaImovel;
	}

	public Set getEstoqueses() {
		return this.estoqueses;
	}

	public void setEstoqueses(Set estoqueses) {
		this.estoqueses = estoqueses;
	}

	public Set getPedidoses() {
		return this.pedidoses;
	}

	public void setPedidoses(Set pedidoses) {
		this.pedidoses = pedidoses;
	}

	public Set getAlunoses() {
		return this.alunoses;
	}

	public void setAlunoses(Set alunoses) {
		this.alunoses = alunoses;
	}

	public Set getDepartamentosUnidadeses() {
		return this.departamentosUnidadeses;
	}

	public void setDepartamentosUnidadeses(Set departamentosUnidadeses) {
		this.departamentosUnidadeses = departamentosUnidadeses;
	}

	public Set getFaturases() {
		return this.faturases;
	}

	public void setFaturases(Set faturases) {
		this.faturases = faturases;
	}

	public Set getFuncionarioses() {
		return this.funcionarioses;
	}

	public void setFuncionarioses(Set funcionarioses) {
		this.funcionarioses = funcionarioses;
	}

	public Set getAtividadeses() {
		return this.atividadeses;
	}

	public void setAtividadeses(Set atividadeses) {
		this.atividadeses = atividadeses;
	}

	public Set getContasBancariases() {
		return this.contasBancariases;
	}

	public void setContasBancariases(Set contasBancariases) {
		this.contasBancariases = contasBancariases;
	}

}
