package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * UniformesAluno generated by hbm2java
 */
public class UniformesAluno implements java.io.Serializable {

	private long idUniformeAluno;
	private AtividadesAluno atividadesAluno;
	private String nmUniforme;
	private Date dtUniformeEntregue;
	private Long qtUniformeEntregue;

	public UniformesAluno() {
	}

	public UniformesAluno(long idUniformeAluno, AtividadesAluno atividadesAluno) {
		this.idUniformeAluno = idUniformeAluno;
		this.atividadesAluno = atividadesAluno;
	}

	public UniformesAluno(long idUniformeAluno, AtividadesAluno atividadesAluno, String nmUniforme,
			Date dtUniformeEntregue, Long qtUniformeEntregue) {
		this.idUniformeAluno = idUniformeAluno;
		this.atividadesAluno = atividadesAluno;
		this.nmUniforme = nmUniforme;
		this.dtUniformeEntregue = dtUniformeEntregue;
		this.qtUniformeEntregue = qtUniformeEntregue;
	}

	public long getIdUniformeAluno() {
		return this.idUniformeAluno;
	}

	public void setIdUniformeAluno(long idUniformeAluno) {
		this.idUniformeAluno = idUniformeAluno;
	}

	public AtividadesAluno getAtividadesAluno() {
		return this.atividadesAluno;
	}

	public void setAtividadesAluno(AtividadesAluno atividadesAluno) {
		this.atividadesAluno = atividadesAluno;
	}

	public String getNmUniforme() {
		return this.nmUniforme;
	}

	public void setNmUniforme(String nmUniforme) {
		this.nmUniforme = nmUniforme;
	}

	public Date getDtUniformeEntregue() {
		return this.dtUniformeEntregue;
	}

	public void setDtUniformeEntregue(Date dtUniformeEntregue) {
		this.dtUniformeEntregue = dtUniformeEntregue;
	}

	public Long getQtUniformeEntregue() {
		return this.qtUniformeEntregue;
	}

	public void setQtUniformeEntregue(Long qtUniformeEntregue) {
		this.qtUniformeEntregue = qtUniformeEntregue;
	}

}
