package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

/**
 * UsuariosGrupo generated by hbm2java
 */
public class UsuariosGrupo {

	private Long idUsuarioGrupo;
	private GruposModulos gruposModulos;

	public UsuariosGrupo() {
	}

	public Long getIdUsuarioGrupo() {
		return this.idUsuarioGrupo;
	}

	public void setIdUsuarioGrupo(Long idUsuarioGrupo) {
		this.idUsuarioGrupo = idUsuarioGrupo;
	}

	public GruposModulos getGruposModulos() {
		return this.gruposModulos;
	}

	public void setGruposModulos(GruposModulos gruposModulos) {
		this.gruposModulos = gruposModulos;
	}

}
