package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

/**
 * UsuariosSistema generated by hbm2java
 */
public class UsuariosSistema implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private String userName;
	private String senha;

	public UsuariosSistema() {
	}
	

	public UsuariosSistema(String userName, String senha) {
		super();
		this.userName = userName;
		this.senha = senha;
	}


	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getSenha() {
		return senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}



	
}
