package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

/**
 * UsuariosGrupo generated by hbm2java
 */
public class UsuariosGrupo implements java.io.Serializable {

	private long idUsuarioGrupo;
	private GruposModulos gruposModulos;
	private UsuariosSistema usuariosSistema;

	public UsuariosGrupo() {
	}

	public UsuariosGrupo(long idUsuarioGrupo, GruposModulos gruposModulos, UsuariosSistema usuariosSistema) {
		this.idUsuarioGrupo = idUsuarioGrupo;
		this.gruposModulos = gruposModulos;
		this.usuariosSistema = usuariosSistema;
	}

	public long getIdUsuarioGrupo() {
		return this.idUsuarioGrupo;
	}

	public void setIdUsuarioGrupo(long idUsuarioGrupo) {
		this.idUsuarioGrupo = idUsuarioGrupo;
	}

	public GruposModulos getGruposModulos() {
		return this.gruposModulos;
	}

	public void setGruposModulos(GruposModulos gruposModulos) {
		this.gruposModulos = gruposModulos;
	}

	public UsuariosSistema getUsuariosSistema() {
		return this.usuariosSistema;
	}

	public void setUsuariosSistema(UsuariosSistema usuariosSistema) {
		this.usuariosSistema = usuariosSistema;
	}

}
