package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UsuariosSistema generated by hbm2java
 */
public class UsuariosSistema implements java.io.Serializable {

	private long idUsuario;
	private PessoasFisicas pessoasFisicas;
	private String nmUsername;
	private Date dtInicioVigencia;
	private Date dtFimVigencia;
	private Date dsFimVigenciaUsuario;
	private String dsSenha;
	private String stAtivo;
	private Date dtUltimoAcesso;
	private Long qtdAcessoNegado;
	private String stTrocaSenha;
	private Set alunosesForIdUsuarioCadastro = new HashSet(0);
	private Set atividadesAlunosForUsAlteracaIdUsuario = new HashSet(0);
	private Set perfisUsuarioses = new HashSet(0);
	private Set alunosesForIdUsuarioAlteracao = new HashSet(0);
	private Set atividadesAlunosForUsCadastroIdUsuario = new HashSet(0);
	private Set cadastroReservaAtividadesesForUsAlteracaIdUsuario = new HashSet(0);
	private Set usuariosGrupos = new HashSet(0);
	private Set cadastroReservaAtividadesesForUsCadastroIdUsuario = new HashSet(0);

	public UsuariosSistema() {
	}

	public UsuariosSistema(long idUsuario, PessoasFisicas pessoasFisicas, String dsSenha) {
		this.idUsuario = idUsuario;
		this.pessoasFisicas = pessoasFisicas;
		this.dsSenha = dsSenha;
	}

	public UsuariosSistema(long idUsuario, PessoasFisicas pessoasFisicas, String nmUsername, Date dtInicioVigencia,
			Date dtFimVigencia, Date dsFimVigenciaUsuario, String dsSenha, String stAtivo, Date dtUltimoAcesso,
			Long qtdAcessoNegado, String stTrocaSenha, Set alunosesForIdUsuarioCadastro,
			Set atividadesAlunosForUsAlteracaIdUsuario, Set perfisUsuarioses, Set alunosesForIdUsuarioAlteracao,
			Set atividadesAlunosForUsCadastroIdUsuario, Set cadastroReservaAtividadesesForUsAlteracaIdUsuario,
			Set usuariosGrupos, Set cadastroReservaAtividadesesForUsCadastroIdUsuario) {
		this.idUsuario = idUsuario;
		this.pessoasFisicas = pessoasFisicas;
		this.nmUsername = nmUsername;
		this.dtInicioVigencia = dtInicioVigencia;
		this.dtFimVigencia = dtFimVigencia;
		this.dsFimVigenciaUsuario = dsFimVigenciaUsuario;
		this.dsSenha = dsSenha;
		this.stAtivo = stAtivo;
		this.dtUltimoAcesso = dtUltimoAcesso;
		this.qtdAcessoNegado = qtdAcessoNegado;
		this.stTrocaSenha = stTrocaSenha;
		this.alunosesForIdUsuarioCadastro = alunosesForIdUsuarioCadastro;
		this.atividadesAlunosForUsAlteracaIdUsuario = atividadesAlunosForUsAlteracaIdUsuario;
		this.perfisUsuarioses = perfisUsuarioses;
		this.alunosesForIdUsuarioAlteracao = alunosesForIdUsuarioAlteracao;
		this.atividadesAlunosForUsCadastroIdUsuario = atividadesAlunosForUsCadastroIdUsuario;
		this.cadastroReservaAtividadesesForUsAlteracaIdUsuario = cadastroReservaAtividadesesForUsAlteracaIdUsuario;
		this.usuariosGrupos = usuariosGrupos;
		this.cadastroReservaAtividadesesForUsCadastroIdUsuario = cadastroReservaAtividadesesForUsCadastroIdUsuario;
	}

	public long getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(long idUsuario) {
		this.idUsuario = idUsuario;
	}

	public PessoasFisicas getPessoasFisicas() {
		return this.pessoasFisicas;
	}

	public void setPessoasFisicas(PessoasFisicas pessoasFisicas) {
		this.pessoasFisicas = pessoasFisicas;
	}

	public String getNmUsername() {
		return this.nmUsername;
	}

	public void setNmUsername(String nmUsername) {
		this.nmUsername = nmUsername;
	}

	public Date getDtInicioVigencia() {
		return this.dtInicioVigencia;
	}

	public void setDtInicioVigencia(Date dtInicioVigencia) {
		this.dtInicioVigencia = dtInicioVigencia;
	}

	public Date getDtFimVigencia() {
		return this.dtFimVigencia;
	}

	public void setDtFimVigencia(Date dtFimVigencia) {
		this.dtFimVigencia = dtFimVigencia;
	}

	public Date getDsFimVigenciaUsuario() {
		return this.dsFimVigenciaUsuario;
	}

	public void setDsFimVigenciaUsuario(Date dsFimVigenciaUsuario) {
		this.dsFimVigenciaUsuario = dsFimVigenciaUsuario;
	}

	public String getDsSenha() {
		return this.dsSenha;
	}

	public void setDsSenha(String dsSenha) {
		this.dsSenha = dsSenha;
	}

	public String getStAtivo() {
		return this.stAtivo;
	}

	public void setStAtivo(String stAtivo) {
		this.stAtivo = stAtivo;
	}

	public Date getDtUltimoAcesso() {
		return this.dtUltimoAcesso;
	}

	public void setDtUltimoAcesso(Date dtUltimoAcesso) {
		this.dtUltimoAcesso = dtUltimoAcesso;
	}

	public Long getQtdAcessoNegado() {
		return this.qtdAcessoNegado;
	}

	public void setQtdAcessoNegado(Long qtdAcessoNegado) {
		this.qtdAcessoNegado = qtdAcessoNegado;
	}

	public String getStTrocaSenha() {
		return this.stTrocaSenha;
	}

	public void setStTrocaSenha(String stTrocaSenha) {
		this.stTrocaSenha = stTrocaSenha;
	}

	public Set getAlunosesForIdUsuarioCadastro() {
		return this.alunosesForIdUsuarioCadastro;
	}

	public void setAlunosesForIdUsuarioCadastro(Set alunosesForIdUsuarioCadastro) {
		this.alunosesForIdUsuarioCadastro = alunosesForIdUsuarioCadastro;
	}

	public Set getAtividadesAlunosForUsAlteracaIdUsuario() {
		return this.atividadesAlunosForUsAlteracaIdUsuario;
	}

	public void setAtividadesAlunosForUsAlteracaIdUsuario(Set atividadesAlunosForUsAlteracaIdUsuario) {
		this.atividadesAlunosForUsAlteracaIdUsuario = atividadesAlunosForUsAlteracaIdUsuario;
	}

	public Set getPerfisUsuarioses() {
		return this.perfisUsuarioses;
	}

	public void setPerfisUsuarioses(Set perfisUsuarioses) {
		this.perfisUsuarioses = perfisUsuarioses;
	}

	public Set getAlunosesForIdUsuarioAlteracao() {
		return this.alunosesForIdUsuarioAlteracao;
	}

	public void setAlunosesForIdUsuarioAlteracao(Set alunosesForIdUsuarioAlteracao) {
		this.alunosesForIdUsuarioAlteracao = alunosesForIdUsuarioAlteracao;
	}

	public Set getAtividadesAlunosForUsCadastroIdUsuario() {
		return this.atividadesAlunosForUsCadastroIdUsuario;
	}

	public void setAtividadesAlunosForUsCadastroIdUsuario(Set atividadesAlunosForUsCadastroIdUsuario) {
		this.atividadesAlunosForUsCadastroIdUsuario = atividadesAlunosForUsCadastroIdUsuario;
	}

	public Set getCadastroReservaAtividadesesForUsAlteracaIdUsuario() {
		return this.cadastroReservaAtividadesesForUsAlteracaIdUsuario;
	}

	public void setCadastroReservaAtividadesesForUsAlteracaIdUsuario(
			Set cadastroReservaAtividadesesForUsAlteracaIdUsuario) {
		this.cadastroReservaAtividadesesForUsAlteracaIdUsuario = cadastroReservaAtividadesesForUsAlteracaIdUsuario;
	}

	public Set getUsuariosGrupos() {
		return this.usuariosGrupos;
	}

	public void setUsuariosGrupos(Set usuariosGrupos) {
		this.usuariosGrupos = usuariosGrupos;
	}

	public Set getCadastroReservaAtividadesesForUsCadastroIdUsuario() {
		return this.cadastroReservaAtividadesesForUsCadastroIdUsuario;
	}

	public void setCadastroReservaAtividadesesForUsCadastroIdUsuario(
			Set cadastroReservaAtividadesesForUsCadastroIdUsuario) {
		this.cadastroReservaAtividadesesForUsCadastroIdUsuario = cadastroReservaAtividadesesForUsCadastroIdUsuario;
	}

}
