package br.com.crux.dto;
// Generated 12/08/2019 22:11:24 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * VulnerabilidadesAluno generated by hbm2java
 */
public class VulnerabilidadesAluno implements java.io.Serializable {

	private long idVulnerabilidadeAluno;
	private Alunos alunos;
	private SituacoesVulnerabilidades situacoesVulnerabilidades;
	private Solucoes solucoes;
	private Date dtIdentVulnerabilidade;
	private Date dtSolucaoVulnerabilidade;

	public VulnerabilidadesAluno() {
	}

	public VulnerabilidadesAluno(long idVulnerabilidadeAluno, Alunos alunos,
			SituacoesVulnerabilidades situacoesVulnerabilidades, Solucoes solucoes, Date dtIdentVulnerabilidade) {
		this.idVulnerabilidadeAluno = idVulnerabilidadeAluno;
		this.alunos = alunos;
		this.situacoesVulnerabilidades = situacoesVulnerabilidades;
		this.solucoes = solucoes;
		this.dtIdentVulnerabilidade = dtIdentVulnerabilidade;
	}

	public VulnerabilidadesAluno(long idVulnerabilidadeAluno, Alunos alunos,
			SituacoesVulnerabilidades situacoesVulnerabilidades, Solucoes solucoes, Date dtIdentVulnerabilidade,
			Date dtSolucaoVulnerabilidade) {
		this.idVulnerabilidadeAluno = idVulnerabilidadeAluno;
		this.alunos = alunos;
		this.situacoesVulnerabilidades = situacoesVulnerabilidades;
		this.solucoes = solucoes;
		this.dtIdentVulnerabilidade = dtIdentVulnerabilidade;
		this.dtSolucaoVulnerabilidade = dtSolucaoVulnerabilidade;
	}

	public long getIdVulnerabilidadeAluno() {
		return this.idVulnerabilidadeAluno;
	}

	public void setIdVulnerabilidadeAluno(long idVulnerabilidadeAluno) {
		this.idVulnerabilidadeAluno = idVulnerabilidadeAluno;
	}

	public Alunos getAlunos() {
		return this.alunos;
	}

	public void setAlunos(Alunos alunos) {
		this.alunos = alunos;
	}

	public SituacoesVulnerabilidades getSituacoesVulnerabilidades() {
		return this.situacoesVulnerabilidades;
	}

	public void setSituacoesVulnerabilidades(SituacoesVulnerabilidades situacoesVulnerabilidades) {
		this.situacoesVulnerabilidades = situacoesVulnerabilidades;
	}

	public Solucoes getSolucoes() {
		return this.solucoes;
	}

	public void setSolucoes(Solucoes solucoes) {
		this.solucoes = solucoes;
	}

	public Date getDtIdentVulnerabilidade() {
		return this.dtIdentVulnerabilidade;
	}

	public void setDtIdentVulnerabilidade(Date dtIdentVulnerabilidade) {
		this.dtIdentVulnerabilidade = dtIdentVulnerabilidade;
	}

	public Date getDtSolucaoVulnerabilidade() {
		return this.dtSolucaoVulnerabilidade;
	}

	public void setDtSolucaoVulnerabilidade(Date dtSolucaoVulnerabilidade) {
		this.dtSolucaoVulnerabilidade = dtSolucaoVulnerabilidade;
	}

}
